---
title: "shotgun_metagenomics_functional_jun2023"
author: "Jordi Rofes Herrera"
date: "2023-06-10"
output: html_document
params:
    input_dir: "../../inputs/Shotgun_Metagenomics/"
    output_dir: "../../outputs/Shotgun_Metagenomics/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required packages

```{r}
library(DESeq2)
source("../Utility_Functions/utilities.R")
library(ggplot2)
library(plotly)
library(mia)
library(SummarizedExperiment)
library(stringr)
```


## Loading the data

```{r}
functional_paths <- list.files(paste0(params$input_dir, "CNT_HFD_HFE_INT/P200045_NEW/report_functional/"), 
                               recursive = TRUE, pattern = "counts_all", full.names = TRUE)

functional_counts <- lapply(functional_paths, function(func_tool_path){
    read.table(func_tool_path, sep = "\t", header = TRUE, row.names = 1)
})
names(functional_counts) <- gsub("_counts_all.tsv", "", basename(functional_paths))
```

## Pre-processing

```{r}
organ_dt <- lapply(c("cecum", "colon"), function(organ){
    shotgun_data <- lapply(functional_counts, function(shotgun_table){
        colnames(shotgun_table)[38] <- paste0(colnames(shotgun_table)[38], "I")
        if(organ == "cecum"){
            shotgun_table <- shotgun_table[grepl("CE", colnames(shotgun_table))]
            colnames(shotgun_table) <- gsub("CE", "X", colnames(shotgun_table))
        } else if(organ == "colon"){
            shotgun_table <- shotgun_table[grepl("X", colnames(shotgun_table))]
        }
        shotgun_table <- shotgun_table[rowMeans(shotgun_table) != 0,]
        shotgun_table
    })
    shotgun_data
})
names(organ_dt) <- c("cecum", "colon")
```

```{r}
## Creating the metadata
metadata_list <- lapply(organ_dt, function(organ){
    lapply(organ, function(hierarchy){ 
        hierarchy <- data.frame("samplename" = colnames(hierarchy))
        hierarchy$group <- substr(x = hierarchy$samplename, start = 5, stop = 5)
        hierarchy$group <- factor(hierarchy$group, levels = c("C", "H", "I", "E"), 
                                      labels = c("CNT", "HFD", "INT", "HFE"))
        hierarchy
    })
})
```


```{r}
# Filtering taxons not present in atleast 80% of one group
organ_dt_list_proc <- lapply(names(organ_dt), function(organ_name){
    organ <- organ_dt[[organ_name]]
    organ_metadata <- metadata_list[[organ_name]]
    
    organ_filt <- lapply(names(organ), function(hierarchy_name){
        hierarchy_metadata <- organ_metadata[[hierarchy_name]]
        hierarchy <- organ[[hierarchy_name]]
        
        keep_vars <- apply(hierarchy, 1, function(dt_var){
            group_dt <- tapply(dt_var, INDEX = hierarchy_metadata$group, function(var_group){
                sum(var_group != 0)/length(var_group)
            })
            
            any(group_dt > 0.8)    
        })
        
        hierarchy[keep_vars,]
    })
    names(organ_filt) <- names(organ)
    organ_filt
})
names(organ_dt_list_proc) <- names(organ_dt)

# saveRDS(object = list("shotgun_data" = organ_dt_list_proc, "shotgun_metadata" = metadata_list), "./shotgun_functional_data_list.rds")
```

```{r}
# Combining duplicate rows
organ_dt_list_proc <- lapply(names(organ_dt_list_proc), function(organ_name){
    organ <- organ_dt_list_proc[[organ_name]]
    organ_metadata <- metadata_list[[organ_name]]
    
    organ_filt <- lapply(names(organ), function(hierarchy_name){
        hierarchy_metadata <- organ_metadata[[hierarchy_name]]
        hierarchy <- organ[[hierarchy_name]]
        
        hierarchy_d <- hierarchy[!duplicated(hierarchy),]
        dup_dt <- apply(hierarchy_d, 1, function(dt_var_d){
            found_d <- apply(hierarchy, 1, function(dt_var){
                all(dt_var == dt_var_d)
            })
            paste(rownames(hierarchy)[found_d], collapse = ";")
        })
        rownames(hierarchy_d) <- dup_dt
        hierarchy_d
    })
    names(organ_filt) <- names(organ)
    organ_filt
})
names(organ_dt_list_proc) <- names(organ_dt)
```


## Stats

```{r}
lapply(organ_dt_list_proc, function(organ_dt){
    lapply(organ_dt, function(funct_dt){
        boxplot(colSums(funct_dt))$out
    })
})
```

## Statistical Analysis

```{r}
stat_res <- lapply(names(organ_dt_list_proc), function(organ_name){
    organ_data <- organ_dt_list_proc[[organ_name]]
    organ_meta <- metadata_list[[organ_name]]

    organ_results <- lapply(names(organ_data), function(hierarchy_name){
        hierarchy <- organ_data[[hierarchy_name]]
        hierarchy_meta <- organ_meta[[hierarchy_name]]
        names_comp <- apply(t(combn(levels(hierarchy_meta$group), m = 2))[,2:1], 1, paste, collapse = "-")

        hierarchy <- as.data.frame(hierarchy)

        hierarchy_deseq <- DESeqDataSetFromMatrix(countData = hierarchy,
                                                  colData = hierarchy_meta, design = ~ group + 0)
        hierarchy_deseq <- DESeq(hierarchy_deseq, test = "Wald")
        results_list <- lapply(names_comp, function(comp_name){
            comp_vec <- c("group", strsplit(comp_name, "-")[[1]])
            results(hierarchy_deseq, contrast = comp_vec, pAdjustMethod = "fdr")
        })

        print(lapply(results_list, summary))

        names(results_list) <- names_comp
        results_list <- do.call(cbind, results_list)
        colnames(results_list) <- gsub("log2FoldChange", "log2FC", colnames(results_list))
        colnames(results_list) <- gsub("pvalue", "p.value", colnames(results_list))
        colnames(results_list) <- gsub("padj", "adj.p.value", colnames(results_list))

        SummarizedExperiment(assays = list("counts" = hierarchy),
                             rowData = results_list, colData = hierarchy_meta)
    })
    names(organ_results) <- names(organ_data)
    organ_results
})
names(stat_res) <- names(organ_dt_list_proc)
# 
# 
# stat_res2 <- lapply(names(organ_dt_list_proc), function(organ_name){
#     organ_data <- organ_dt_list_proc[[organ_name]]
#     organ_meta <- metadata_list[[organ_name]]
#   
#     organ_results <- lapply(names(organ_data), function(hierarchy_name){
#         hierarchy <- organ_data[[hierarchy_name]]
#         hierarchy_meta <- organ_meta[[hierarchy_name]]
#         names_comp <- apply(t(combn(levels(hierarchy_meta$group), m = 2))[,2:1], 1, paste, collapse = "-")
#         comp_matrix <- matrix(NA, nrow = length(names_comp), ncol = 2)
#         rownames(comp_matrix) <- names_comp
#         
#         hierarchy <- transformAssay(SummarizedExperiment(assays = list("counts" = as.data.frame(hierarchy))), 
#                                     assay.type = "counts", method = "clr", pseudocount = 1)
#         
#         results_list <- lapply(as.data.frame(t(assay(hierarchy, "clr"))),
#                             function(var_dt){
#             if(length(var_dt) != length(hierarchy_meta$group)){browser()}
# 
#             kru_res <- kruskal.test(var_dt ~ hierarchy_meta$group)
#             if(kru_res$p.value <= 0.05){
#                 return(DescTools::ConoverTest(x = var_dt, 
#                                             g = hierarchy_meta$group)[[1]])
#             } else{
#                 return(comp_matrix)
#             }
#         })
#         contrasts_results <- lapply(names_comp, function(ctrs_row){
#             ctrs_result_list <- lapply(results_list, function(ctrs){
#                 if(!(ctrs_row %in% rownames(ctrs))){return(rep(NA, 2))}
#                 ctrs[ctrs_row,]   
#             })
#             do.call(rbind, ctrs_result_list)
#         })
#         names(contrasts_results) <- names_comp
#         
#         contrasts_results <- lapply(contrasts_results, function(ctrs){
#             ctrs <- as.data.frame(ctrs)
#             colnames(ctrs) <- c("difference", "pvalue")
#             ctrs$adj.p.value <- p.adjust(ctrs[,"pvalue"], method = "fdr")
#             ctrs
#         })
#         
#         
#         contrasts_results <- do.call(cbind, contrasts_results)
#         colnames(contrasts_results) <- gsub("log2FoldChange", "log2FC",
#                                             colnames(contrasts_results))
#         colnames(contrasts_results) <- gsub("pvalue", "p.value",
#                                             colnames(contrasts_results))
#         colnames(contrasts_results) <- gsub("padj", "adj.p.value",
#                                             colnames(contrasts_results))
#         
#         SummarizedExperiment(assays = list("counts" = hierarchy), 
#                             rowData = contrasts_results, 
#                             colData = hierarchy_meta)
#     })
#     names(organ_results) <- names(organ_data)
#     organ_results
# })
# names(stat_res2) <- names(organ_dt_list_proc)
# ```
# 
# ```{r}
# lapply(stat_res, function(organ){
#     lapply(organ, function(ft_dt){
#         sum(!is.na(rowData(ft_dt)$`HFD-CNT.adj.p.value`) &
#             rowData(ft_dt)$`HFD-CNT.adj.p.value` <= 0.05)
#     })
# })
# lapply(stat_res2, function(organ){
#     lapply(organ, function(ft_dt){
#         sum(!is.na(rowData(ft_dt)$`HFD-CNT.adj.p.value`) &
#             rowData(ft_dt)$`HFD-CNT.adj.p.value` <= 0.05)
#     })
# })
# test_deseq <- stat_res$colon$metaerg_kegg
# 
# sig_hfd_d <- rownames(test_deseq)[!is.na(rowData(test_deseq)$`HFD-CNT.adj.p.value`) &
#                                       rowData(test_deseq)$`HFD-CNT.adj.p.value` <= 0.05]
# 
# 
# test_kruskal <- stat_res2[[2]]$metaerg_kegg
# 
# sig_hfd_k <- rownames(test_kruskal)[!is.na(rowData(test_kruskal)$`HFD-CNT.adj.p.value`) &
#                                         rowData(test_kruskal)$`HFD-CNT.adj.p.value` <= 0.05]
# 
# lapply(sig_hfd_k[1], function(var_id){
#     boxplot(as.numeric(organ_dt_list_proc$colon$metaerg_kegg[var_id,]) ~ metadata_list$colon$metaerg_kegg$group)    
# })
# 
# lapply(sig_hfd_d[1], function(var_id){
#     boxplot(as.numeric(organ_dt_list_proc$colon$metaerg_kegg[var_id,]) ~ metadata_list$colon$metaerg_kegg$group)    
# })
# 
# 
# clr_tfm <- transformAssay(stat_res$colon$metaerg_kegg, assay.type = "counts", 
#                         method = "clr", pseudocount = 1)
# 
# lapply(setdiff(sig_hfd_k, sig_hfd_d), function(var_id){
#     boxplot(as.numeric(assay(clr_tfm[var_id,], "clr")) ~ metadata_list$colon$metaerg_kegg$group)    
# })
# 
# 
# kruskal.test(as.numeric(organ_dt_list_proc$cecum$metaerg_kegg[sig_hfd_d,]) ~ metadata_list$cecum$metaerg_kegg$group)



```


##### Annotations

```{r}
annotation_list <- list.files(params$input_dir, pattern = "\\.txt$", full.names = TRUE)

annotation_list <- annotation_list[c(5, 1, 3)]
names(annotation_list) <- c("EC", "metaerg_pathway", "cogs")

# annotation_dt <- lapply(annotation_list, function(x){
#     read.table(x, header = TRUE, sep = "\t", row.names = NULL)
# })
#### EC
ec_dt <- readLines(annotation_list["EC"])
ec_dt <- ec_dt[25:length(ec_dt)]
ec_dt_list <- list()

for(ec_line in ec_dt){
    found_id <- grep("^ID", x = ec_line, value = TRUE)
    
    if(length(found_id)){
        ec_found <- data.frame("ID" = gsub("ID *", "", found_id))
    }
    found_de <- grep("^DE", x = ec_line, value = TRUE)
    
    if(length(found_de)){
        ec_found$Description <- gsub("DE *", "", found_de)
    }
    
    found_next <- grep(pattern = "^//", x = ec_line, value = TRUE)
    
    if(length(found_next)){
        ec_dt_list <- c(ec_dt_list, list(ec_found))
    }
}
ec_dt_list <- do.call(rbind, ec_dt_list)
###### COGs
cog_dt <- readLines(annotation_list["cogs"])
# cog_dt <- gsub('"', "", cog_dt)
cog_dt <- strsplit(cog_dt, "\t")

cog_dt <- lapply(cog_dt, function(x){
    x <- c(x, rep("", 7 - length(x)))
})

cog_dt <- do.call(rbind, cog_dt)
colnames(cog_dt) <- cog_dt[1,]
cog_dt <- cog_dt[-1,]

cog_dt <- as.data.frame(cog_dt)

cog_category <- readLines("../../inputs/Shotgun_Metagenomics/cog-24.fun.tab.txt")
cog_category <- strsplit(cog_category, "\t")

cog_type <- cog_category[lengths(cog_category) == 2]
cog_type <- do.call(rbind, cog_type)
colnames(cog_type) <- c("COG_Type_ID", "Type_Info")
cog_type <- as.data.frame(cog_type)

cog_fun <- cog_category[lengths(cog_category) != 2]
cog_fun[[16]] <- c(cog_fun[[16]][1:2], "", cog_fun[[16]][3])

cog_fun <- do.call(rbind, cog_fun)
colnames(cog_fun) <- c("COG_functional_category", "COG_Type_ID", 
                        "Color_ID", "Functional_Description")
cog_fun <- as.data.frame(cog_fun)
cog_fun$Type_Info <- cog_type$Type_Info[match(cog_fun$COG_Type_ID, cog_type$COG_Type_ID)]

cog_info_dt <- lapply(strsplit(cog_dt$COG_functional_category, ""), function(x){
    
    cog_fun_found <- cog_fun[cog_fun$COG_functional_category %in% x,]
    
    cog_desc_found <- paste(cog_fun_found$Functional_Description,
                            collapse = " / ")
    cog_info_found <- paste(unique(cog_fun_found$Type_Info), collapse = " / ")
    data.frame("COG_Functional_Category" = cog_desc_found, 
                "COG_Type_Info" = cog_info_found)
})
cog_info_dt <- do.call(rbind, cog_info_dt)

cog_dt <- cbind(cog_dt, cog_info_dt)

######
metacyc_dt <- read.table(annotation_list[1], sep = "\t", header = TRUE, row.names = NULL)

metacyc_dt3 <- readLines("../../inputs/Shotgun_Metagenomics/pwy.hierarchy")
metacyc_dt3 <- strsplit(metacyc_dt3, "\t")
metacyc_dt3 <- do.call(rbind, metacyc_dt3)
metacyc_dt3 <- as.data.frame(metacyc_dt3)

# metacyc_dt2 <- readLines("../../inputs/Shotgun_Metagenomics/ec.to.pwy")
# metacyc_dt2 <- strsplit(metacyc_dt2, "\t")
# metacyc_dt2 <- do.call(rbind, metacyc_dt2)
# metacyc_dt2 <- as.data.frame(metacyc_dt2)

#### metaerg_kegg
metaerg_dt <- readLines("../../inputs/Shotgun_Metagenomics/ecoli/27.5/data/pathways.dat")
metaerg_dt <- metaerg_dt[28:length(metaerg_dt)]
metaerg_dt_list <- list()

for(meta_line in metaerg_dt){
    found_id <- grep("^UNIQUE-ID", x = meta_line, value = TRUE)
    
    if(length(found_id)){
        meta_found <- data.frame("ID" = gsub("UNIQUE-ID - ", "", found_id))
    }
    found_de <- grep("^COMMON-NAME", x = meta_line, value = TRUE)
    
    if(length(found_de)){
        meta_found$Description <- gsub("COMMON-NAME - ", "", found_de)
    }
    
    found_next <- grep(pattern = "^//", x = meta_line, value = TRUE)
    
    if(length(found_next)){
        metaerg_dt_list <- c(metaerg_dt_list, list(meta_found))
    }
}
metaerg_dt_list_ecoli <- as.data.frame(do.call(rbind, metaerg_dt_list))

####
metaerg_dt <- readLines("../../inputs/Shotgun_Metagenomics/aplat/27.5/data/pathways.dat")
metaerg_dt <- metaerg_dt[21:length(metaerg_dt)]
metaerg_dt_list <- list()

for(meta_line in metaerg_dt){
    found_id <- grep("^UNIQUE-ID", x = meta_line, value = TRUE)
    
    if(length(found_id)){
        meta_found <- data.frame("ID" = gsub("UNIQUE-ID - ", "", found_id))
    }
    found_de <- grep("^COMMON-NAME", x = meta_line, value = TRUE)
    
    if(length(found_de)){
        meta_found$Description <- gsub("COMMON-NAME - ", "", found_de)
    }
    
    found_next <- grep(pattern = "^//", x = meta_line, value = TRUE)
    
    if(length(found_next)){
        metaerg_dt_list <- c(metaerg_dt_list, list(meta_found))
    }
}
metaerg_dt_list_aplat <- as.data.frame(do.call(rbind, metaerg_dt_list))


metacyc_sel <- metacyc_dt[,c("Geneid", "MetaCyc_id")]
colnames(metacyc_sel) <-  c("ID", "Description")

metacyc_2_sel <- metacyc_dt3[,c("V1", "V2")]
colnames(metacyc_2_sel) <- c("ID", "Description")

annotation_dt <- rbind(metacyc_sel, metacyc_2_sel, metaerg_dt_list_aplat, metaerg_dt_list_ecoli)
annotation_dt <- distinct(annotation_dt)
annotation_dt$Description <- gsub("^;|;$|<i>|</i>|<sub>|</sub>", "", annotation_dt$Description)
annotation_dt$Description <- gsub("; ", ";", annotation_dt$Description)
# annotation_list <- list("EC" = ec_dt_list, "cogs" = cog_dt, "metaerg_pathway" = annotation_dt)
```

```{r}
stat_res <- lapply(stat_res, function(organ){
    organ_res <- lapply(names(organ), function(dt_name){
        switch(dt_name, "EC" = {
            dt <- organ[[dt_name]]
            
            rowData(dt)$Old_Name <- rownames(dt)
            ids <- rownames(dt)
            ids_tr <- sapply(ids, function(id){
                
                id_vect <- strsplit(id, ";")[[1]]
                id_vect <- gsub("EC:", "", id_vect)
                
                found_id <- which(ec_dt_list$ID %in% id_vect)
                
                found_de <- ec_dt_list$Description[found_id]
                if(length(found_id) & all(found_de != "") & !any(is.na(found_de))){
                    return(paste(found_de[!is.na(found_de)], collapse = ";"))  
                } else{
                    return(id)
                }
            })
            if(all(!duplicated(ids_tr))){
                rownames(dt) <- ids_tr
            } 
            rowData(dt)$Description <- ids_tr
            
            return(dt)
        }, "cogs" = {
            dt <- organ[[dt_name]]
            ids <- rownames(dt)
            rowData(dt)$Old_Name <- rownames(dt)
            
            ids_df <- lapply(ids, function(id){
                id_vect <- strsplit(id, ";")[[1]]
                
                found_id <- which(cog_dt$COG_ID %in% id_vect)
                found_de <- cog_dt[found_id,]
                if(nrow(found_de)){
                    cog_info <- sapply(found_de, function(x){
                        paste(x, collapse = ";")
                    })
                    return(as.data.frame(t(cog_info)))
                } else{
                    return(id)
                }
            })
            ids_df <- do.call(rbind, ids_df)
            ids_df$Description <- ids_df$COG_Name
            if(all(!duplicated(ids_df$Description))){
                rownames(dt) <- ids_df$Description
            } 
            rowData(dt) <- cbind(rowData(dt), ids_df)
            
            return(dt)
        }, "metaerg_pathway" = {
            dt <- organ[[dt_name]]
            ids <- rownames(dt)
            rowData(dt)$Old_Name <- rownames(dt)
            
            ids_tr <- sapply(ids, function(id){
                id_vect <- strsplit(id, ";")[[1]]
                found_id <- which(annotation_dt$ID %in% id_vect)
                found_de <- annotation_dt$Description[found_id]
                if(length(found_id) & any(found_de != "") & !all(is.na(found_de))){
                    return(paste(found_de[!is.na(found_de)], collapse = ";"))    
                } else{
                    return(id)
                }
                
            })
            if(all(!duplicated(ids_tr))){
                rownames(dt) <- ids_tr
            } 
            rowData(dt)$Description <- ids_tr
            
            return(dt)
        }, "metaerg_kegg" = {
            
            rowData(organ[[dt_name]])$Description <- rownames(rowData(organ[[dt_name]]))  
            
            return(organ[[dt_name]])
        })
    })
    names(organ_res) <- names(organ)
    organ_res
})

stat_res <- lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    organ_res <- lapply(organ, function(dt){
        rowData(dt)$readable_name <- str_replace(paste(organ_name, rowData(dt)$Description),
                                                "^\\w{1}", toupper)
        return(dt)
    })
    names(organ_res) <- names(organ)
    organ_res
})

names(stat_res) <- names(organ_dt_list_proc)

saveRDS(stat_res, paste0(params$output_dir, "Shotgun_Metagenomics_Functional_exp_lima.rds"))
```

##### PCA 

```{r, message=FALSE}
lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]][,colData(organ[[hierarchy_name]])$group != "HFE"]
        hierarchy <- hierarchy[rowSums(assay(hierarchy)) != 0,]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + group)
        vst_dt <- t(assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE)))
        vst_pca <- prcomp(vst_dt, scale. = TRUE)
        
        p1 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                group_var = hierarchy$group, 
                ellipse_var = hierarchy$group, allElipse = TRUE, interactive = FALSE) + 
            ggtitle(paste(organ_name, hierarchy_name, "PCA"))
        print(p1)
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
        return(NULL)
    })
})
```


```{r}
a <- lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]][,colData(organ[[hierarchy_name]])$group != "HFE"]
        hierarchy <- hierarchy[rowSums(assay(hierarchy)) != 0,]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + group)
        vst_dt <- t(assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE)))
        pheatmap::pheatmap(scale(vst_dt), show_colnames = FALSE, annotation_row = as.data.frame(colData(hierarchy))["group"])
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
    })
})

```


```{r}
a <- lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]][,colData(organ[[hierarchy_name]])$group != "HFE"]
        hierarchy <- hierarchy[rowSums(assay(hierarchy)) != 0,]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + group)
        vst_dt <- t(assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE)))
        pheatmap::pheatmap(scale(vst_dt), show_colnames = FALSE, annotation_row = as.data.frame(colData(hierarchy))["group"])
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
    })
    
})
```

```{r}
a <- lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        colSums(assay(organ[[hierarchy_name]]))
    })
})
```


### PCA clr

```{r, message=FALSE}
lapply(names(stat_res), function(organ_name){
    organ <- stat_res[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]][,rownames(colData(organ[[hierarchy_name]]))[colData(organ[[hierarchy_name]])$group != "HFE"]]
        hierarchy <- hierarchy[rowSums(assay(hierarchy)) != 0,]
        # raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
        #                               colData = colData(hierarchy),
        #                               design= ~ 0 + group)
        hierarchy <- transformAssay(hierarchy, assay.type = "counts", 
                                         method = "relabundance")
        vst_dt <- t(assay(transformAssay(hierarchy, assay.type = "relabundance", 
                                         method = "rclr"), "rclr"))
        vst_pca <- prcomp(vst_dt, scale. = TRUE)
        
        p1 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                group_var = hierarchy$group, 
                ellipse_var = hierarchy$group, allElipse = TRUE, interactive = FALSE) + 
            ggtitle(paste(organ_name, hierarchy_name, "PCA"))
        print(p1)
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
        return(NULL)
    })
})
```

##### Alpha diversities (Shannon Index)

```{r}
lapply(names(stat_res), function(organ_names){
    organ <- stat_res[[organ_names]]
    lapply(names(organ), function(hierarchy_names){
        hierarchy <- organ[[hierarchy_names]]
        group_var <- hierarchy$group
    
        alpha_div <- vegan::diversity(x = assay(hierarchy), index = "shannon", MARGIN = 2)
        
        boxplot(alpha_div ~ group_var, main = paste(organ_names, hierarchy_names, sep = "_"), 
                xlab = "Group", ylab = "Shannon Index")
    })
})
```

