---
title: "16S_jan2023"
author: "Jordi Rofes Herrera"
date: "2023-01-30"
output: html_document
params:
    input_dir: "../../inputs/X16S_Metagenomics/"
    output_dir: "../../outputs/X16S_Metagenomics/"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages

```{r}
library(dplyr)
library(stringi)
library(stringr)
library(mixOmics)
library(sva)
library(SummarizedExperiment)
library(mia)
library(TreeSummarizedExperiment)
library(DESeq2)
library(plotly)
library(miaViz)
library(scater)
library(patchwork)
source("../../scripts/Utility_Functions/utilities.R")
```

## Initial processing

### GF/CV

```{r}
names_dict <- c("Phylum", "Class", "Order", "Family", "Genus", "Species")
names(names_dict) <- paste0("level-", 2:7)

organ_dir <- list.dirs(params$input_dir, full.names = TRUE, recursive = FALSE)

organ_dt_list <- lapply(organ_dir[1], function(organ_dt){
    meta_files <- list.files(organ_dt, pattern = ".txt$|.csv$", full.names = TRUE)
    
    meta_files_proc <- lapply(meta_files, function(meta_file_path){
        col_names <- readLines(meta_file_path, n = 1)
        col_names <- strsplit(col_names, ",")[[1]]
        col_names <- col_names[2:length(col_names)]
        
        meta_f <- read.table(file = meta_file_path, sep = ",", row.names = 1, header = TRUE)
        # rownames(meta_f) <- sapply(strsplit(rownames(meta_f), "-"), function(x){x[2]})
        # 
        # meta_f <- subset(meta_f, rownames(meta_f) != "667")
        meta_f <- subset(meta_f, grepl("GF", x = project))

        num_cols <- sapply(meta_f, is.numeric)

        meta_f <- meta_f[,num_cols]
        colnames(meta_f) <- col_names[num_cols]
        
        # rownames(meta_f) <- name_vect[rownames(meta_f)]
        meta_f <- meta_f %>% select_if(colSums(.) != 0 & !grepl("Unassigned", colnames(.)))
        as.data.frame(t(meta_f))
    })
    names(meta_files_proc) <- gsub(pattern = ".txt$|.csv$", "", basename(meta_files))
    names(meta_files_proc) <- names_dict[names(meta_files_proc)]
    meta_files_proc
})
names(organ_dt_list) <- basename(organ_dir[1])

# saveRDS(organ_dt_list, "16S_data_list.rds")
```

```{r}
# name_vect <- colnames(organ_dt_list[[1]]$Phylum)
# names(name_vect) <- substr(name_vect, start = 2, stop = 4)

gfcv_colon_dt <- lapply(organ_dir[2], function(organ_dt){
    
    meta_files <- list.files(grep("P190161", list.dirs(organ_dt), value = TRUE), full.names = TRUE)
    
    meta_files_proc <- lapply(meta_files, function(meta_file_path){
        col_names <- readLines(meta_file_path, n = 1)
        col_names <- strsplit(col_names, ",")[[1]]
        col_names <- col_names[2:length(col_names)]
        
        meta_f <- read.table(file = meta_file_path, sep = ",", row.names = 1, header = TRUE)
        # rownames(meta_f) <- sapply(strsplit(rownames(meta_f), "-"), function(x){x[2]})
        # 
        # meta_f <- subset(meta_f, rownames(meta_f) != "667")
        # meta_f <- subset(meta_f, grepl("GF", x = project))

        num_cols <- sapply(meta_f, is.numeric)

        meta_f <- meta_f[,num_cols]
        colnames(meta_f) <- col_names[num_cols]
        
        # rownames(meta_f) <- name_vect[rownames(meta_f)]
        meta_f <- meta_f %>% select_if(colSums(.) != 0 & !grepl("Unassigned", colnames(.)))
        as.data.frame(t(meta_f))
    })
    names(meta_files_proc) <- gsub(pattern = "\\.txt$|\\.csv$", "", basename(meta_files))
    names(meta_files_proc) <- names_dict[names(meta_files_proc)]

    meta_files_proc
})
names(gfcv_colon_dt) <- "colon"
organ_dt_list <- c(organ_dt_list, gfcv_colon_dt)
```


```{r}

metadata_list <- lapply(organ_dt_list, function(organ_dt){
    gfcv_16s_cond <- data.frame(samplename= colnames(organ_dt$Phylum))

    gfcv_16s_cond$type_gfcv <- stri_sub(gfcv_16s_cond$samplename,1,2)
    
    gfcv_16s_cond$group <- stri_sub(gfcv_16s_cond$samplename,1,1)
    
    gfcv_16s_cond$sex <- stri_sub(gfcv_16s_cond$samplename,2,2)
    
    gfcv_16s_cond$batch <- stri_sub(gfcv_16s_cond$samplename,4,4)
    
    gfcv_16s_cond$all <- paste0(gfcv_16s_cond$type_gfcv,stri_sub(gfcv_16s_cond$samplename,4,4))
    
    rownames(gfcv_16s_cond) <- gfcv_16s_cond$samplename
    
    gfcv_16s_cond_cec <- dplyr::select(gfcv_16s_cond, -samplename)
    gfcv_16s_cond_cec
})
```

```{r}
organ_exp <- lapply(names(organ_dt_list), function(organ_name){
    organ <- organ_dt_list[[organ_name]]
    
    organ_tree <- lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        hierarchy_metadata <- metadata_list[[organ_name]]
        
        hierarchy_ids <- c("D_0", "D_1", "D_2", "D_3", "D_4", "D_5", "D_6")
        hierarchy_ranks <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
        
        max_rank <- grep(stringr::str_to_title(hierarchy_name), hierarchy_ranks)
        
        hierarchy_ids <- hierarchy_ids[seq_len(max_rank)]
        hierarchy_ranks <- hierarchy_ranks[seq_len(max_rank)]
        hierarchycal_tree <- lapply(rownames(hierarchy), function(sp_name){

            hierarchy_found <- c()
            
            for(h_id_num in seq_along(hierarchy_ids)){
                h_id <- hierarchy_ids[h_id_num]
                
                found_id <- grep(paste0("^", h_id, "__"), 
                                strsplit(sp_name, ";")[[1]], value = TRUE)
                
                if(length(found_id)){
                    found_dt <- gsub(paste0(h_id, "__"), "", found_id)
                    found_dt <- gsub("\\[|\\]", "", found_dt)

                    if(found_dt == "" || grepl("uncultured|unknown|unidentified|metagenome", found_dt, ignore.case = TRUE)){
                        # hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]),
                        #                                     hierarchy_found[h_id_num - 1],
                        #                                     paste("Unknown", hierarchy_found[h_id_num - 1]))
                        hierarchy_found[h_id_num] <- NA
                    } else{
                        hierarchy_found[h_id_num] <- found_dt
                    }
                } else{
                    # hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]),
                    #                                         hierarchy_found[h_id_num - 1],
                    #                                         paste("Unknown", hierarchy_found[h_id_num - 1]))
                    hierarchy_found[h_id_num] <- NA

                }    
            }
            return(hierarchy_found)
        })

        hierarchycal_tree <- do.call(rbind, hierarchycal_tree)
        colnames(hierarchycal_tree) <- hierarchy_ranks
        hierarchy <- TreeSummarizedExperiment(assays = list("counts" = as.matrix(hierarchy)),
                            colData = hierarchy_metadata,
                            rowData = hierarchycal_tree)
        rowData(hierarchy)$old_names <- rownames(hierarchy)

        hierarchy <- mia::agglomerateByRank(x = hierarchy, rank = hierarchy_ranks[max_rank])
        hierarchy <- mia::addTaxonomyTree(hierarchy)
        
        rowData(hierarchy)$prevalence <- getPrevalence(hierarchy, 
                                                    detection = 1/100, 
                                                    sort = FALSE,
                                                    assay.type = "counts", 
                                                    as_relative = TRUE)
        
        rowData(hierarchy)$specie_names <- rownames(hierarchy)
        rowData(hierarchy)$readable_name <- str_replace(paste("16S", organ_name, rownames(hierarchy)), 
                                                        "^\\w{1}", toupper)

        
        hierarchy
    })
    # names(organ) <- sapply(strsplit(names(organ), "_"), function(x){x[[3]]})

    names(organ_tree) <- names(organ)
    organ_tree
})
names(organ_exp) <- names(organ_dt_list)
```


```{r}
organ_exp <- lapply(names(organ_dt_list), function(organ_name){
    organ <- organ_dt_list[[organ_name]]
    
    organ_tree <- lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        hierarchy_metadata <- metadata_list[[organ_name]]
        
        hierarchy_ids <- c("D_0", "D_1", "D_2", "D_3", "D_4", "D_5", "D_6")
        hierarchy_ranks <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
        
        max_rank <- grep(stringr::str_to_title(hierarchy_name), hierarchy_ranks)
        
        hierarchy_ids <- hierarchy_ids[seq_len(max_rank)]
        hierarchy_ranks <- hierarchy_ranks[seq_len(max_rank)]
        hierarchycal_tree <- lapply(rownames(hierarchy), function(sp_name){
            hierarchy_found <- c()
            
            for(h_id_num in seq_along(hierarchy_ids)){
                h_id <- hierarchy_ids[h_id_num]
                
                found_id <- grep(paste0("^", h_id, "__"), 
                                strsplit(sp_name, "\\;")[[1]], value = TRUE)
                
                if(length(found_id)){
                    found_dt <- gsub(paste0(h_id, "__"), "", found_id)
                    found_dt <- gsub("\\[|\\]", "", found_dt)

                    if(found_dt == "" || grepl("uncultured|unknown|unidentified|metagenome", found_dt, ignore.case = TRUE)){
                        hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]), 
                                                            hierarchy_found[h_id_num - 1], 
                                                            paste("Unknown", hierarchy_found[h_id_num - 1]))
                    } else{
                        hierarchy_found[h_id_num] <- found_dt
                    }
                } else{
                    hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]), 
                                                            hierarchy_found[h_id_num - 1], 
                                                            paste("Unknown", hierarchy_found[h_id_num - 1]))
                }    
            }
            return(hierarchy_found)
        })

        hierarchycal_tree <- do.call(rbind, hierarchycal_tree)
        colnames(hierarchycal_tree) <- hierarchy_ranks
        hierarchy <- TreeSummarizedExperiment(assays = list("counts" = as.matrix(hierarchy)),
                            colData = hierarchy_metadata,
                            rowData = hierarchycal_tree)
        rowData(hierarchy)$old_names <- rownames(hierarchy)
        rowData(hierarchy)$readable_name <- paste(organ_name, rownames(hierarchy))

        
        hierarchy <- mia::agglomerateByRank(x = hierarchy, rank = hierarchy_ranks[max_rank])
        hierarchy <- mia::addTaxonomyTree(hierarchy)
        
        rowData(hierarchy)$specie_names <- rownames(hierarchy)
        hierarchy
    })
    # names(organ) <- sapply(strsplit(names(organ), "_"), function(x){x[[3]]})

    names(organ_tree) <- names(organ)
    organ_tree
})
names(organ_exp) <- names(organ_dt_list)
```


```{r, message=FALSE}
lapply(names(organ_exp), function(organ_name){
    organ <- organ_exp[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + type_gfcv)
        vst_dt <- t(assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE)))
        vst_pca <- prcomp(vst_dt, scale. = TRUE)
        
        p1 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                group_var = hierarchy$group, 
                ellipse_var = hierarchy$group, allElipse = TRUE)
        print(p1)
        p2 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                 group_var = hierarchy$batch, 
                 ellipse_var = hierarchy$batch, allElipse = TRUE)
        print(p2)
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
        return(NULL)
    })
})

```

```{r}
lapply(names(organ_exp), function(organ_names){
    organ <- organ_exp[[organ_names]]
    lapply(names(organ), function(hierarchy_names){
        
        group_var <- colData(organ[[hierarchy_names]])[["type_gfcv"]]
        hierarchy <- organ[[hierarchy_names]]
        alpha_div <- vegan::diversity(x = assay(hierarchy), index = "shannon", MARGIN = 2)
        
        boxplot(alpha_div ~ group_var, main = paste(organ_names, hierarchy_names, sep = "_"), 
                xlab = "Group", ylab = "Shannon Index")
    })
})
```

```{r}
perc_thr <- 0.8
group_var <- "type_gfcv"

organ_dt_list_fil <- lapply(seq_along(organ_exp), function(organ_id){
    organ <- organ_exp[[organ_id]]
    lapply(organ, function(hierarchy){
        zero_mat <- assay(hierarchy) == 0
        organ_meta <- colData(hierarchy)
        
        group_levels <- unique(organ_meta[[group_var]])
        
        row_keep <- matrix(nrow = nrow(hierarchy), ncol = length(group_levels))
        
        for(gr_id in seq_along(group_levels)){
            group_zero_mat <- zero_mat[,organ_meta[[group_var]] == group_levels[gr_id]]
            row_keep[,gr_id] <- rowSums(group_zero_mat) < (ncol(group_zero_mat)*perc_thr)
        }
        row_keep <- apply(row_keep, 1, any)
        hierarchy[row_keep,]
    })
})

names(organ_dt_list_fil) <- names(organ_exp)

# saveRDS(organ_dt_list_fil, "16S_data_list.rds")
```

```{r, message=FALSE}
lapply(names(organ_dt_list_fil), function(organ_name){
    organ <- organ_dt_list_fil[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + type_gfcv)
        vst_dt <- t(assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE)))
        vst_pca <- prcomp(vst_dt, scale. = FALSE)
        
        p1 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                group_var = hierarchy$group, 
                ellipse_var = hierarchy$group, allElipse = TRUE)
        print(p1)
        p2 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                 group_var = hierarchy$batch, 
                 ellipse_var = hierarchy$batch, allElipse = TRUE)
        print(p2)
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
        return(NULL)
    })
})
```

### Batch corrected

```{r, message=FALSE}
lapply(names(organ_dt_list_fil), function(organ_name){
    organ <- organ_dt_list_fil[[organ_name]]
    lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        raw_lima_DESeq <- DESeqDataSetFromMatrix(countData = assay(hierarchy),
                                      colData = colData(hierarchy),
                                      design= ~ 0 + type_gfcv)
        vst_dt <- assay(varianceStabilizingTransformation(raw_lima_DESeq, blind = FALSE))
        vst_dt <- t(limma::removeBatchEffect(x = vst_dt, batch = hierarchy$batch, design = model.matrix(~ sex, data = colData(hierarchy))))
        
        vst_pca <- prcomp(vst_dt, scale. = FALSE)
        
        p1 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                group_var = hierarchy$type_gfcv, 
                ellipse_var = hierarchy$type_gfcv, allElipse = TRUE)
        print(p1)
        p2 <- pca_plot(pca_data = vst_pca, pc_x = 1, pc_y = 2, 
                 group_var = hierarchy$batch, 
                 ellipse_var = hierarchy$batch, allElipse = TRUE)
        print(p2)
        # pcvar <- round(vst_pca$sdev^2/sum(vst_pca$sdev^2)*100, 2)
        # 
        # d3plot <- plot_ly(x = vst_pca$x[,1], y = vst_pca$x[,2], z = vst_pca$x[,3], color = myGFCVfactors$group)
        # d3plot <- d3plot %>% add_markers()
        # d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
        #                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
        #                      zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
        # d3plot
        return(NULL)
    })
})
```

```{r}
lapply(names(organ_dt_list_fil), function(organ_names){
    organ <- organ_dt_list_fil[[organ_names]]
    lapply(names(organ), function(hierarchy_names){
        hierarchy <- organ[[hierarchy_names]]
        group_var <- hierarchy$type_gfcv
        
        hierarchy_corr <- ComBat_seq(counts = assay(hierarchy), batch = hierarchy$batch, group = hierarchy$type_gfcv)
        
        alpha_div <- vegan::diversity(x = hierarchy_corr, index = "shannon", MARGIN = 2)
        
        boxplot(alpha_div ~ group_var, main = paste(organ_names, hierarchy_names, sep = "_"), 
                xlab = "Group", ylab = "Shannon Index")
    })
})
```


### Statistical Analysis

```{r}
# stat_res <- lapply(seq_along(organ_dt_list_fil), function(organ_id){
#     organ <- organ_dt_list_fil[[organ_id]]
#     organ_meta <- metadata_list[[organ_id]]
#     
#     names_comp <- t(combn(levels(organ_meta$group), 
#                                 m = 2))[,2:1, drop = FALSE]
#     comp_mat <- as.data.frame(matrix(NA, ncol = 2, nrow = length(names_comp)))
#     rownames(comp_mat) <- names_comp
#     colnames(comp_mat) <- c("mean rank diff", "p.value")
#     
#     lapply(organ, function(hierarchy){
#         hierarchy_batch <- ComBat(dat = hierarchy, batch = organ_meta$batch)
#         #hierarchy <- as.data.frame(clr(t(hierarchy)))
#         hierarchy_batch <- as.data.frame(t(hierarchy_batch))
#         #pca(mat = hierarchy, metadata = organ_meta, scale = FALSE)
#         var_results <- lapply(hierarchy_batch, function(dt_var){
#             comp_res <- apply(names_comp, 1, function(comp_name){
#                 wil_res <- wilcox.test(x = dt_var[comp_name[1] == organ_meta$group], 
#                                         y = dt_var[comp_name[2] == organ_meta$group])
#                 as.data.frame(wil_res[c("statistic", "p.value")])
#             })
#             comp_res <- as.data.frame(do.call(rbind, comp_res))
#             rownames(comp_res) <- paste(names_comp, collapse = "_")
#             
#             comp_res
#         })
#         
#         gf_comps <- lapply(levels(organ_meta$group), function(comp_group){
#             hierarchy_subset <- hierarchy_batch[comp_group == organ_meta$group,]
#             comp_res <- as.data.frame(do.call(rbind, lapply(hierarchy_subset, function(dt_var){
#                 as.data.frame(wilcox.test(dt_var, mu = 0)[c("statistic", "p.value")])
#             })))
#             comp_res$adj.p.value <- p.adjust(comp_res$p.value, "fdr")
#             comp_res
#         })
#         names(gf_comps) <- paste0(ifelse(grepl("M", levels(organ_meta$group)), "GFM", "GFF"), 
#                                     "_", levels(organ_meta$group))
#         
#         all_gfcv_comps <- lapply(unique(organ_meta$gfcv), function(comp_group){
#             hierarchy_subset <- hierarchy_batch[comp_group == organ_meta$gfcv,]
#             comp_res <- as.data.frame(do.call(rbind, lapply(hierarchy_subset, function(dt_var){
#                 as.data.frame(wilcox.test(dt_var, mu = 0)[c("statistic", "p.value")])
#             })))
#             comp_res$adj.p.value <- p.adjust(comp_res$p.value, "fdr")
#             comp_res
#         })
#         names(all_gfcv_comps) <- "GF_CV"
#         
#         names_comp_paste <- apply(names_comp, 1, paste0, collapse = "_")
#         comp_list <- lapply(names_comp_paste, function(idv_comp){
#             results_list <- lapply(var_results, function(results_mat){
#                 if(idv_comp %in% rownames(results_mat)){
#                     return(results_mat[idv_comp,])} 
#                 else{
#                     return(rep(NA, 2))
#                 }
#             })
#             results_list <- as.data.frame(do.call(rbind, results_list))
#             results_list$adj.p.value <- p.adjust(results_list$p.value, method = "fdr")
#             results_list
#         })
#         names(comp_list) <- names_comp_paste
#         result_dt <- do.call(cbind, c(all_gfcv_comps, gf_comps, comp_list))
#         
#         summ_exp <- TreeSummarizedExperiment(
#             assays = list("counts" = hierarchy), 
#             rowData = result_dt, 
#             colData = organ_meta)
#         
#         summ_exp
#     })
# })
# names(stat_res) <- names(organ_dt_list_fil)

# saveRDS(stat_res, "./16S_results_gfcv_list.rds")
```


```{r}
x16s_exp <- lapply(names(organ_dt_list_fil), function(organ_name){
    organ_data <- organ_dt_list_fil[[organ_name]]
  
    organ_results <- lapply(names(organ_data), function(hierarchy_name){
        hierarchy <- organ_data[[hierarchy_name]]
        hierarchy_meta <- colData(hierarchy)
        names_comp <- apply(t(combn(levels(as.factor(hierarchy_meta$type_gfcv)), m = 2))[,2:1, drop = FALSE], 
                            1, paste, collapse = "-")
        hierarchy_deseq <- DESeqDataSetFromMatrix(countData = as.data.frame(assay(hierarchy)),
                                                  colData = hierarchy_meta, design = ~ type_gfcv + batch + 0)
        hierarchy_deseq <- DESeq(hierarchy_deseq, test = "Wald")
        ## Pairwise
        results_list <- lapply(names_comp, function(comp_name){
            comp_vec <- c("type_gfcv", strsplit(comp_name, "-")[[1]])
            results(hierarchy_deseq, contrast = comp_vec, pAdjustMethod = "fdr")
        })
        names(results_list) <- names_comp
        
        ## Coefs
        coef_names <- paste0("type_gfcv", levels(as.factor(hierarchy_meta$type_gfcv)))

        results_gfcv <- lapply(coef_names, function(comp_id){
            results(hierarchy_deseq, name = comp_id)
        })
        names(results_gfcv) <- c("GFM_CVM", "GFF_CVF")
        ## Full gfcv
        hierarchy_deseq <- DESeqDataSetFromMatrix(countData = as.data.frame(assay(hierarchy)),
                                                  colData = hierarchy_meta, design = ~ type_gfcv + batch + 0)
        hierarchy_deseq <- DESeq(hierarchy_deseq, test = "Wald")
        

        results_gfcv_full <- list(results(hierarchy_deseq, contrast = c(1,1,0)))
        names(results_gfcv_full) <- c("GF_CV_Full")
        # hierarchy_ancombc2 <- SummarizedExperiment(assays = hierarchy, 
        #                                            colData = hierarchy_meta)
        # ancom_res <- ancombc2(data = hierarchy_ancombc2, fix_formula = "~ group + 0", p_adj_method = "fdr", group = "group")
        # 
        results_list <- c(results_list, results_gfcv, results_gfcv_full)
        
        results_list <- do.call(cbind, results_list)
        
        colnames(results_list) <- gsub("log2FoldChange", "log2FC", colnames(results_list))
        colnames(results_list) <- gsub("pvalue", "p.value", colnames(results_list))
        colnames(results_list) <- gsub("padj", "adj.p.value", colnames(results_list))
        
        rowData(hierarchy) <- cbind(rowData(hierarchy), results_list)
        hierarchy
    })
    names(organ_results) <- names(organ_data)
    organ_results
})
names(x16s_exp) <- names(organ_dt_list_fil)

saveRDS(x16s_exp, paste0(params$output_dir, "16S_Metagenomics_exp_gfcv.rds"))
```

