---
title: "Correlations_Network_Enrichment_Plots"
author: "Jordi Rofes Herrera"
date: "2024-04-24"
output: html_document
params:
    nw_graphs: !r nw_graphs
    enrich_results_list: !r enrich_results_partial
    output_dir: !r enrich_nw_dir
    omic_dt: !r omic_dt
    group_var: "group"
    universe_ids_list: !r universe_list_ids
    omic_names_dict: !r omic_names_dict
    group_color_dict: !r group_color_dict
    omic_color_dict: !r omic_color_dict
    feature_ids_dict: !r feature_ids_dict
    omic_shape_dict: !r shape_vect_ext
    var_order_col_list: !r var_order_col_list
    close_cyt_session: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DOSE)
library(igraph)
library(dplyr)
library(RCy3)
library(ggplot2)
library(reshape2)
library(stringr)
library(ggnewscale)
library(MultiAssayExperiment)
source("../Utility_Functions/utilities.R")
```

### Network creation

#### Adding enrich results

```{r}
if(!dir.exists(params$output_dir)){dir.create(params$output_dir)}
## What I need to create a network
# 1. Network list / nw_graphs_dt
# 2. Clustering (could be all in one cluster) / Variable name in nw_graphs_dt
# 3. Enrichment of clusters / params$enrich_results_list
# 
nw_graphs_dt <- params$nw_graphs

for(score_id in names(nw_graphs_dt)){
    for(weight_id in names(nw_graphs_dt[[score_id]])){
        term_list <- lapply(names(params$enrich_results_list[[score_id]][[weight_id]]), 
                            function(clu_id){
                                res_enrich <- as.data.frame(params$enrich_results_list[[score_id]][[weight_id]][[clu_id]])
                                if(nrow(res_enrich) == 0){return(NA)}
                                res_enrich$ID <- paste0("enrich_term.", clu_id, ".", res_enrich$ID)
                                res_enrich$cluster_ids <- clu_id
                                res_enrich
                            })
        names(term_list) <- names(params$enrich_results_list[[score_id]][[weight_id]])

        term_list <- term_list[!is.na(term_list)]
        if(length(term_list) == 0){next}
        ## Define nodes n1
        term_dt <- lapply(names(term_list), function(clu_id){
            geneID_list <- strsplit(term_list[[clu_id]]$geneID, "/")
            geneID_list <- lapply(geneID_list, function(x){x[!is.na(x) & x != "NA"]})
            
            names(geneID_list) <- term_list[[clu_id]]$ID
            
            geneID_list
            # Reduce(c, found_ids)
        })
        names(term_dt) <- names(term_list) 
        
        ## Define edges n1
        
        term_dt_n1 <- lapply(term_dt, function(clu_dt){
            
            found_ids <- lapply(names(clu_dt), function(pathway_ids){
                ids <- clu_dt[[pathway_ids]]
                ids <- unique(unlist(ids))
                unlist(strsplit(paste(pathway_ids,  unique(ids), sep = "\t"), "\t"))
            })
            names(found_ids) <- names(clu_dt)
            # found_ids
            Reduce(c, found_ids)
        })
        names(term_dt_n1) <- names(term_list) 
        
        term_dt_n1 <- Reduce(c, term_dt_n1)
        
        ## Define edges n2
        term_dt_n2 <- lapply(term_dt, function(clu_dt){
            
            found_ids <- lapply(names(clu_dt), function(pathway_ids){
                ids <- clu_dt[[pathway_ids]]
                
                found <- igraph::neighborhood(graph = nw_graphs_dt[[score_id]][[weight_id]], 
                                    order = 1, nodes = ids)
                found <- unique(unlist(sapply(found, names)))
                unlist(strsplit(paste(pathway_ids,  unique(found), sep = "\t"), "\t"))
            })
            names(found_ids) <- names(clu_dt)
            # found_ids
            Reduce(c, found_ids)
        })
        names(term_dt_n2) <- names(term_list) 
        
        term_dt_n2 <- Reduce(c, term_dt_n2)
        
        ## Define Nodes
        term_list <- do.call(rbind, term_list)
        
        term_nodes <- lapply(seq_len(nrow(term_list)), function(term_id){
            term_info <- term_list[term_id,]
            
            terms_found <- term_dt[[term_info$cluster_ids]][[term_info$ID]]
            data.frame("Genes" = paste0(grep("RNA_Sequencing", terms_found, value = TRUE), collapse = ";"), 
                        "DMRs" = paste0(grep("WGB", terms_found, value = TRUE), collapse = ";"), 
                        "Metabolites" = paste0(grep("Untargeted", terms_found, value = TRUE), collapse = ";"))
        })
        term_nodes <- do.call(rbind, term_nodes)
        term_list <- cbind(term_list, term_nodes)
        
        nw_graphs_dt[[score_id]][[weight_id]] <- add.vertices(
            graph = nw_graphs_dt[[score_id]][[weight_id]], 
            nv = nrow(term_list), 
            attr = list("name" = term_list$ID, 
                        "Readable_Name" = term_list$Description, 
                        "Node_Omic" = "enrich_term", 
                        "cluster_ids" = term_list$cluster_ids,
                        "Genes" = term_list$Genes,
                        "DMRs" = term_list$DMRs,
                        "Metabolites" = term_list$Metabolites))
        
        nw_graphs_dt[[score_id]][[weight_id]] <- add.edges(
            graph = nw_graphs_dt[[score_id]][[weight_id]], 
            edges = term_dt_n1, attr = list("weight" = 0, "Type" = "term_n1"))
        
        nw_graphs_dt[[score_id]][[weight_id]] <- add.edges(
            graph = nw_graphs_dt[[score_id]][[weight_id]], 
            edges = term_dt_n2, attr = list("weight" = 0, "Type" = "term_n2"))
    }
}
```

#### Cytoscape calls

```{r}
library(MultiAssayExperiment)
library(RCy3)

```

```{r}
# getwd()
# 
# file.exists("../../outputs/Multi_Omics_Analysis/MOFA_Results/any_sig_005_mofa_int_thr08/correlation_results/full_kegg_joint_pathway_enrichment/correlation_results_f1f2_network_full.cys")
# dir.exists("../../outputs/Multi_Omics_Analysis/MOFA_Results/any_sig_005_mofa_int_thr08/correlation_results/full_kegg_joint_pathway_enrichment/")
# file.exists("C:/Users/Jordi/Documents/GitHub/gnotobiomics_project_data_analysis/outputs/Multi_Omics_Analysis/MOFA_Results/any_sig_005_mofa_int_thr08/correlation_results/full_kegg_joint_pathway_enrichment/correlation_results_f1f2_network_full.cys")
```


```{r}
cyt_session_path <- paste0(params$output_dir, 
                        "correlation_results_f1f2_network_full.cys")
term_network_path <- paste0(params$output_dir, 
                            "term_network_list.rds")

safe_loop <- function() {
    tryCatch({
        failed <- TRUE
        cytoscapePing()
        failed <- FALSE
    },
    error = function(e) {
        cat("Error:", e$message, "\n")
    }, warning = function(w) {
        cat("Warning:", w$message, "\n")
    })
    if(failed){safe_loop()}
}

if(!file.exists(cyt_session_path) | !file.exists(term_network_path)){
    
    safe_loop()

    term_network_list <- list()
    
    for(score_id in names(nw_graphs_dt)){
        score_dt <- nw_graphs_dt[[score_id]]
        
        term_network_list[[score_id]] <- list()
        # term_node_list[[score_id]] <- list()
        
        export_list_ids <- c()
        
        for(weight_id in names(score_dt)){
        
            term_network_list[[score_id]][[weight_id]] <- list()
            # term_node_list[[score_id]][[weight_id]] <- list()
            # 
            weight_dt <- score_dt[[weight_id]]
            
            clu_dt <- vertex_attr(weight_dt, name = "cluster_ids")
            # vertex.color = vertex_attr(test_sub, name = "Node_Omic")
            # plot.igraph(omic_network, vertex.size = 0.5, edge.size = 0.1, 
            #             vertex.label.cex = 0.2, edge.arrow.size = 0.1, 
            #             layout = layout_as_tree(omic_network))
            sufix_id <- paste0(score_id, ".", weight_id)
            
            RCy3::createNetworkFromIgraph(weight_dt, title = sufix_id)
            # RCy3::renameNetwork(title = sufix_id)
            
            RCy3::copyVisualStyle(from.style = "default", 
                                  to.style = sufix_id)
            RCy3::setVisualStyle(sufix_id)
            
            set.seed(1234)
            clu_colors <- RCy3::paletteColorRandom(value.count = length(unique(clu_dt)))
            
            
            # RCy3::setNodeColorMapping(table.column = "cluster_ids",
            #                           table.column.values = unique(clu_dt),
            #                           colors = clu_colors,
            #                           mapping.type = "discrete", style.name = sufix_id)
            RCy3::setNodeColorMapping(table.column = "Node_Omic",
                                      table.column.values = names(params$omic_color_dict),
                                      colors = params$omic_color_dict,
                                      mapping.type = "discrete", style.name = sufix_id)
            
            RCy3::setNodeShapeMapping(table.column = "Node_Omic", 
                                      table.column.values = names(params$omic_shape_dict), 
                                      shapes = params$omic_shape_dict, style.name = sufix_id)
            
            RCy3::setNodeLabelMapping(table.column = "Readable_Name", style.name = sufix_id)
            
            RCy3::setNodeFontSizeDefault(new.size = 6, style.name = sufix_id)
            
            small_node <- names(V(weight_dt))[grepl("Shotgun_Metagenomics_Functional", 
                                                    vertex_attr(weight_dt, name = "Node_Omic"))]
            
            RCy3::setNodePropertyBypass(node.names = small_node, new.values = 60, 
                                        visual.property = "NODE_LABEL_WIDTH")
            RCy3::setNodePropertyBypass(node.names = small_node, new.values = 4, 
                                        visual.property = "NODE_LABEL_FONT_SIZE")
            
            # RCy3::setNodeColorMapping(table.column = make.names(params$fold_change_variable), 
            #                         colors = colorRampPalette(colors = c("blue", 
            #                                                             "white", 
            #                                                             "red")),
            #                         style.name = params$output_suffix)
            RCy3::setEdgeColorMapping(table.column = "weight", 
                                    colors = colorRampPalette(colors = c("#B3CDE3", 
                                                                        "#FBB4AE")), 
                                    style.name = sufix_id)
            
            
            for(clu_id in names(params$enrich_results_list[[score_id]][[weight_id]])){
                
                term_network_list[[score_id]][[weight_id]][[clu_id]] <- list()
                # term_node_list[[score_id]][[weight_id]][[clu_id]] <- list()
                
                clu_name <- paste0(sufix_id, ".", clu_id)
                
                
                RCy3::createSubnetwork(nodes = clu_id, nodes.by.col = "cluster_ids", 
                                       subnetwork.name = clu_name, network = sufix_id)
                
                clu_nw <- subgraph(graph = weight_dt, 
                                    vids = V(weight_dt)[vertex_attr(graph = weight_dt, 
                                                                    name = "cluster_ids") == clu_id])
                
                clu_nw_n2 <- subgraph.edges(clu_nw, 
                                            E(clu_nw)[grepl("term_n2", edge_attr(clu_nw, name = "Type"))])
                
                clu_vertex <- V(clu_nw_n2)[vertex_attr(clu_nw_n2, name = "Node_Omic") == "enrich_term"]
                
                term_nw_list <- lapply(names(clu_vertex), function(term_name){
                    neighbors_ids <- names(neighbors(clu_nw_n2, term_name))
                    neighbors_ids <- neighbors_ids[!grepl("RNA_Sequencing|Untargeted_Metabolomics|WGB_DNA|enrich_term",
                                                        neighbors_ids)]
                    c(neighbors_ids, term_name)
                })
                names(term_nw_list) <- names(clu_vertex)
    
                term_description <- vertex_attr(weight_dt, name = "Readable_Name", names(clu_vertex))
                
                for(term_id in seq_along(term_nw_list)){
                    
                    term_network_list[[score_id]][[weight_id]][[clu_id]][[term_description[term_id]]] <- subgraph(clu_nw_n2, 
                                                                                  vids = term_nw_list[[term_id]])
                    
                    term_name <- paste0(clu_name, ".", term_description[term_id])
                    
                    RCy3::createSubnetwork(nodes = term_nw_list[[term_id]], nodes.by.col = "name", 
                                       subnetwork.name = term_name, network = clu_name)
                    RCy3::layoutNetwork(layout.name = "hierarchical", network = term_name)
                    
                    
                    if(length(term_nw_list[[term_id]]) > 1){
                        export_list_ids <- c(export_list_ids, term_name)
                    }
                  
                }
            }
        }
        network_output_dir <- paste0(params$output_dir, score_id, "/")
                    
        if(!dir.exists(network_output_dir)){
            dir.create(network_output_dir)
        }
        
        export_list_ids_2 <- abbreviate(make.names(export_list_ids), minlength = 30)
        
        for(export_id in seq_along(export_list_ids_2)){
            RCy3::exportSVG(filename = paste0(network_output_dir, 
                                            make.names(export_list_ids[export_id]), ".svg"),
                            network = export_list_ids[export_id])  
        }
          
    }
    saveRDS(term_network_list, term_network_path)
    saveSession(cyt_session_path)
    
    if(params$close_cyt_session){closeSession(save.before.closing = FALSE)}
    
} else if(!params$close_cyt_session){
    term_network_list <- readRDS(term_network_path)
    openSession(cyt_session_path)    
} else {
    term_network_list <- readRDS(term_network_path)
}

```


#### Correlation Plots

```{r}
omic_names <- c("DMRs", "Genes", "Metabolites")

lapply(names(term_network_list), function(score_id){
    score_nw <- term_network_list[[score_id]]
    
    lapply(names(score_nw), function(factor_id){
        factor_nw <- score_nw[[factor_id]]
        
        pdf(paste0(params$output_dir, "Corr_Heatmap_", 
                        score_id, "_", factor_id, ".pdf"), width = 12, height = 8)
        lapply(names(factor_nw), function(clu_id){
            
            clu_nw <- factor_nw[[clu_id]]
            lapply(names(clu_nw), function(term_id){
                term_nw <- clu_nw[[term_id]]
                feature_ids <- names(V(term_nw))
                term_ids <- lapply(omic_names, function(x){
                    found <- vertex_attr(term_nw, name = x, index = feature_ids)
                    strsplit(found[!is.na(found) & found != ""], ";")
                })
                term_ids <- unlist(term_ids, use.names = FALSE)
                
                if(length(feature_ids) == 1){return(NULL)}
                print(plot_nw_term(omic_dt = params$omic_dt, feature_ids = feature_ids, 
                            term_ids = term_ids,
                            feature_ids_dict = params$feature_ids_dict, 
                            omic_names_dict = params$omic_names_dict,
                            var_order_col = params$var_order_col_list[[score_id]][[factor_id]],
                            omic_color_dict = params$omic_color_dict, 
                            group_color_dict = params$group_color_dict,
                            plot_title = paste(clu_id, term_id), 
                            plot_type = "Heatmap"))
            })
            
        })
        dev.off()
    })
})
```

```{r}
omic_names <- c("DMRs", "Genes", "Metabolites")

lapply(names(term_network_list), function(score_id){
    score_nw <- term_network_list[[score_id]]
    
    lapply(names(score_nw), function(factor_id){
        factor_nw <- score_nw[[factor_id]]
        
        pdf(paste0(params$output_dir, "Corr_Lineplot_", 
                        score_id, "_", factor_id, ".pdf"), width = 12, height = 8)
        lapply(names(factor_nw), function(clu_id){
            
            clu_nw <- factor_nw[[clu_id]]
            lapply(names(clu_nw), function(term_id){
                term_nw <- clu_nw[[term_id]]
                feature_ids <- names(V(term_nw))
                term_ids <- lapply(omic_names, function(x){
                    found <- vertex_attr(term_nw, name = x, index = feature_ids)
                    strsplit(found[!is.na(found) & found != ""], ";")
                })
                term_ids <- unlist(term_ids, use.names = FALSE)
                
                if(length(feature_ids) == 1){return(NULL)}
                print(plot_nw_term(omic_dt = params$omic_dt, feature_ids = feature_ids, 
                            term_ids = term_ids,
                            feature_ids_dict = params$feature_ids_dict, 
                            omic_names_dict = params$omic_names_dict,
                            var_order_col = params$var_order_col_list[[score_id]][[factor_id]],
                            omic_color_dict = params$omic_color_dict, 
                            group_color_dict = params$group_color_dict,
                            plot_title = paste(clu_id, term_id), 
                            plot_type = "Lineplot"))
            })
            
        })
        dev.off()
    })
})
```

