---
title: "Network Analysis"
output: html_document
date: "2023-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required packages

```{r}
library(OmicsNetR)
library(readr)
library(AnnotationDbi)
library(org.Mm.eg.db)
```

## Loading the data

```{r}
rna_seq_dt <- readRDS("../RNA_seq/RNASeq_gfcv_complete_model_ihw_results_list.rds")

## RNA Seq Data
sig_dt <- lapply(names(rna_seq_dt), function(ctrs_name){
    ctrs <- rna_seq_dt[[ctrs_name]]
    ctrs <- ctrs[!is.na(ctrs$padj),]
    ctrs$Entrez <- mapIds(x = org.Mm.eg.db, keys = rownames(ctrs), column = "ENTREZID", keytype = "ENSEMBL")
    ctrs <- ctrs[!is.na(ctrs$Entrez),]
    
    sig_genes <- ctrs[ctrs$padj <= 0.1,]
    write.table(sig_genes[,c("Entrez", "log2FoldChange")], 
                file = paste0("./Networks_Input/", "RNASeq_", ctrs_name, "_Network.txt"), sep = " ", 
                row.names = FALSE, quote = FALSE)
})


# Peak Data

unt_meta_list <- readRDS("../Untargeted_Metabolomics/merged_gfcv_results.rds")

unt_meta_data <- unt_meta_list[["Merged_Data"]]
unt_meta_metadata <- unt_meta_list[["Merged_Metadata"]]
unt_meta_results <- unt_meta_list[["Merged_Results"]]

unt_meta <- lapply(names(unt_meta_results)[3:8], function(comp_dt_name){
    comp_dt <- unt_meta_results[[comp_dt_name]]
    comp_dt <- cbind(comp_dt[,c("mzmed", "rtmed")], unt_meta_data[,1],
                    comp_dt[,"adj.p.value"])
    colnames(comp_dt) <- c("Mz", "Rt", "Int", "Pvalue")

    comp_dt_sig <- comp_dt
    lapply(c("Positive", "Negative"), function(ionization_type){
        comp_dt_res <- comp_dt_sig[grepl(pattern = ionization_type, 
                                         rownames(comp_dt_sig)),]
        write.table(comp_dt_res, file = paste0("./Networks_Input/", 
                                           "Untargeted_Metabolomics_", 
                                           comp_dt_name, "_", ionization_type, ".txt"), 
                sep = ",", row.names = FALSE)    
    })
    
    return(NULL)
})

# Metabolite data
targ_meta_results <- readRDS("../epi_metabolomics/targeted_metabolomics_results.rds")

targ_meta_list <- readRDS("../epi_metabolomics/targeted_metabolomics_data.rds")

targ_meta <- lapply(names(targ_meta_list), function(organ_name){
    organ <- targ_meta_list[[organ_name]]
    organ_results <- targ_meta_results[[organ_name]]
    
    organ_results_sig <- lapply(names(organ_results)[3:8], function(comp_dt_names){
        comp_dt_results <- organ_results[[comp_dt_names]]
        organ_meta <- colData(organ)
        organ_meta$group_sex <- as.factor(paste0(ifelse(organ_meta$group == "G", "GF", "CV"),
                                                organ_meta$sex))
        model_matrix <- model.matrix(~ group_sex + 0, organ_meta)
        colnames(model_matrix) <- levels(organ_meta$group_sex)
        if(!all(rownames(comp_dt_results) == rownames(organ))){stop("Rownames do not match")}
        
        comp_dt_results$log2FC <- ProteoNet:::fold_change_calc(data = assay(organ), 
                                     model_matrix = model_matrix, contrs = gsub("_", "-",
                                                                                comp_dt_names), 
                                     geometric_mean = TRUE, log2_dt = FALSE)[[1]]
        comp_dt_results[comp_dt_results$adj.p.value <= 0.1,]
    })
    names(organ_results_sig) <- names(organ_results)[3:8]
    organ_results_sig
})
names(targ_meta) <- names(targ_meta_list)

targ_meta$liver <- lapply(names(targ_meta$liver), function(comp_name){
    targ_meta$liver[[comp_name]] <- rbind(targ_meta$liver[[comp_name]], targ_meta$liver_scfa[[comp_name]])
})
names(targ_meta$liver) <- names(targ_meta$liver_scfa)
targ_meta$liver_scfa <- NULL

lapply(names(targ_meta), function(organ_name){
    organ <- targ_meta[[organ_name]]
    
    organ_res <- lapply(names(organ), function(comp_dt_name){
        comp_dt <- organ[[comp_dt_name]]
        comp_dt_f <- data.frame("Metabolite_Name" = rownames(comp_dt), "log2FC" = comp_dt$log2FC)
        if(nrow(comp_dt_f) == 0){return(NULL)}
        write.table(comp_dt_f, file = paste0("./Networks_Input/", "Targeted_Metabolomics_",
                                           organ_name, "_", comp_dt_name, ".txt"), 
                    row.names = FALSE, sep = " ")
    })
    return(NULL)
})

# Microbiome data
x16S_met_data_list <- readRDS("../16S_meta/16S_data_list.rds")
x16S_met_metadata_list <- readRDS("../16S_meta/16S_metadata_list.rds")

x16S_met_data_list_sig <- lapply(names(x16S_met_data_list), function(organ_name){
    organ <- x16S_met_data_list[[organ_name]]
    organ_metadata <- x16S_met_metadata_list[[organ_name]]
    
    lapply(organ, function(hierarchy){
        group_dt_list <- lapply(unique(organ_metadata$type_gfcv), function(group_name){
            group_dt <- hierarchy[,group_name == organ_metadata$type_gfcv]    
            group_dt <- group_dt[rowSums(group_dt) != 0, ]
            p_vals <- apply(group_dt, 1, function(var_dt){
                t.test(var_dt)$p.value
            })
            group_dt[p_vals <= 0.05,]
        })
        names(group_dt_list) <- ifelse(unique(organ_metadata$type_gfcv) == "CM", "GFM-CVM", "GFF-CVF")
        group_dt_list
    })
})
names(x16S_met_data_list_sig) <- names(x16S_met_data_list)

x16S_met_microorganmis_list <- lapply(x16S_met_data_list_sig, function(organ){
    lapply(organ, function(hierarchy){
        lapply(hierarchy, function(comp_dt){
            microorganism_names <- rownames(comp_dt)
            microorganism_names <- gsub("D_[0,1,2,3,4,5,6]", "", microorganism_names)
            microorganism_names <- gsub("__", "", microorganism_names)
            microorganism_names <- strsplit(microorganism_names, split = ";")
            sapply(microorganism_names, function(name_list){
                found_missing <- grepl("unidentified|uncultured", name_list) | name_list == ""
                if(any(found_missing)){
                    name_list_found <- name_list[!found_missing]
                    name_list_found <- name_list_found[length(name_list_found)]
                    name_list_found <- gsub(" ", "_", name_list_found)
                    return(paste0("unclassified_", name_list_found))
                } else{
                    name_list_found <- name_list[length(name_list)]
                    name_list_found <- gsub(" ", "_", name_list_found)
                    return(name_list_found)    
                }
            })
        })
    })
})

lapply(names(x16S_met_microorganmis_list), function(organ_name){
    organ <- x16S_met_microorganmis_list[[organ_name]]
    organ_res <- lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        lapply(names(hierarchy), function(comp_dt_name){
            comp_dt <- hierarchy[[comp_dt_name]]
            write.table(comp_dt, paste0("./Networks_Input/", "Meta_16S_", 
                                        organ_name, "_",
                                        hierarchy_name, "_", 
                                        comp_dt_name, ".txt"), quote = FALSE, row.names = FALSE, col.names = FALSE)    
        })
    })
    return(NULL)
})
#c(2, 4, 5, 3, 1, 6)

```


```{r}

library(OmicsNetR)
dataSet <- Init.Data()
#BiocParallel::register(BiocParallel::SerialParam())

file_path<-system.file("test/malaria_peaks.csv", package = "OmicsNetR");
ImportMSPeaks(PeakFile = file_path);
SetOrganism("hsa");
UpdateCmpdDB(dbNM = "kegg");

# Step 3. Perform Peak Data Pre-processing (prepare node, edge sets and putative annotation on chemical/abiotic artifacts)
PerformDataProcessing();

# Step 4. Perform annotation network propagation
PerformPropagation();

# Step 5. Perform global network optimization
PerformGlobalOptimization();

# Step 6. Perform LC-MS peak annotation
PerformAnnotation();

# Step 7. Annotation results organization for network visulization
dataSet<-PreparePeaksNetwork(dataSet);

# Step 8. Network construction
dataSet<-QueryNet(dataSet, "peak", "default", "peak");

# Step 9. Create network graph
dataSet<-CreateGraph(dataSet);

# Step 10. Prepare the network file to be used for visualization, the output will be in JSON format.
dataSet<-PrepareNetwork(dataSet, "subnetwork1", "omicsnet_0.json")
```

```{r}
dataSet<-Init.Data();

dataSet<-PrepareInputList(dataSet,"Faecalibacterium_prausnitzii
Bacteroides_uniformis
Eubacterium_rectale
Alistipes_putredinis
Subdoligranulum_unclassified
Escherichia_coli
Alistipes_shahii
Ruminococcus_obeum", "microbiome", "mic", "species");

dataSet<-PreparePeaksNetwork(dataSet);
# dataSet<-QueryNet(dataSet, "peak", "default", "peak");
SetOrganism("microbiome");
SetMetPotentialOpts("0.8", "TRUE", "TRUE", "TRUE");
dataSet<-QueryNet(dataSet, "mic", "agora", "mic");

dataSet<-CreateGraph(dataSet)

```

