---
title: "PTM GFCV"
author: "Jordi Rofes Herrera"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
library(car)
library(DescTools)
```


```{r}
ptm_data <- read.csv("./GFCV_liv_PTMs_4_stats.csv", row.names = 1)

ptm_metadata <- ptm_data[,1:4]
ptm_data <- ptm_data[,5:ncol(ptm_data)]
ptm_metadata$sex <- factor(ptm_metadata$sex, levels = c("M", "F"))
ptm_metadata$gfcv <- factor(ptm_metadata$gfcv, levels = c("C", "G"))
ptm_metadata$group <- factor(paste0(ptm_metadata$gfcv, 
                            ifelse(ptm_metadata$gfcv == "C", "V", "F"), 
                            ptm_metadata$sex), levels = c("CVM", "CVF", "GFM", "GFF"))
ptm_metadata$batch <- factor(ptm_metadata$batch)
saveRDS(list("PTM_Data" = ptm_data, 
                          "PTM_Metadata" = ptm_metadata),"./ptm_gfcv_data_list.rds")
```

```{r}
lapply(ptm_data, function(x){boxplot(x ~ ptm_metadata$group)})

lapply(ptm_data, LeveneTest, group = ptm_metadata$group)
lapply(ptm_data, function(x){
    tapply(x, INDEX = ptm_metadata$group, FUN = function(y){
        qqnorm(y)
        qqline(y)
    })
})

```

```{r}
names_comp <- apply(t(combn(levels(ptm_metadata$group), m = 2))[,2:1], 1, paste, collapse = "-")
comp_mat <- as.data.frame(matrix(NA, ncol = 4, nrow = length(names_comp)))
rownames(comp_mat) <- names_comp
colnames(comp_mat) <- c("difference", "lower", "upper", "p.value")

tukey_results <- lapply(ptm_data, function(dt_var){
    anova_results <- aov(dt_var ~ batch + sex + gfcv + sex:gfcv, data = ptm_metadata)
    anova_results_no_int <- aov(dt_var ~ batch + sex + gfcv, data = ptm_metadata)
    
    list("Interaction Term" = as.data.frame(summary(anova_results)[[1]][4,]),
         "GF_CV_Full" = as.data.frame(summary(anova_results_no_int)[[1]][3,]),
         "Pairwise-Tests" = TukeyHSD(anova_results, which = c("sex:gfcv")))
})

gf_cv_results <- do.call(rbind, lapply(tukey_results, function(x){x[[2]]}))
names(gf_cv_results)[names(gf_cv_results) == "Pr(>F)"] <- "p.value"
gf_cv_results$adj.p.value <- p.adjust(gf_cv_results$p.value, method = "fdr")


interaction_results <- do.call(rbind, lapply(tukey_results, function(x){x[[1]]}))
names(interaction_results)[names(interaction_results) == "Pr(>F)"] <- "p.value"
interaction_results$adj.p.value <- p.adjust(interaction_results$p.value, method = "fdr")

contrasts_results <- lapply(tukey_results, function(x){x[[3]]})
contrasts_results <- lapply(seq_len(nrow(contrasts_results[[1]][[1]])), function(ctrs_row){
    ctrs_result_list <- lapply(contrasts_results, function(ctrs){
        if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
        ctrs[[1]][ctrs_row,]   
    })
    do.call(rbind, ctrs_result_list)
})
names(contrasts_results) <- c("CVF_CVM", "GFM_CVM", "GFF_CVM", 
                              "GFM_CVF", "GFF_CVF", "GFF_GFM")

contrasts_results <- lapply(contrasts_results, function(ctrs){
    ctrs <- as.data.frame(ctrs)
    colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
    ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
    ctrs
})


saveRDS(contrasts_results, "./ptm_gfcv_results.rds")
```
