---
title: "Weight Gene Correlation Network Analysis"
author: "Jordi Rofes Herrera"
date: "2023-09-19"
output: html_document
params:
    input_dir: "../../outputs/Multi_Omics_Analysis/"
    output_dir: "../../outputs/Multi_Omics_Analysis/full_gene_analysis/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the packages

```{r}
library(WGCNA)
library(MultiAssayExperiment)
library(AnnotationDbi)
library(org.Mm.eg.db)
library(clusterProfiler)
```


## Loading the data

```{r}

if(!dir.exists(params$output_dir)){dir.create(params$output_dir)}

multi_omic_dt <- readRDS(paste0(params$input_dir, "Multi_Omics_Analysis_MA_exp_lima.rds"))

rna_seq_dt <- experiments(multi_omic_dt)[["RNA_Sequencing"]]


p_val_dt <- rowData(rna_seq_dt)[,grepl("adj.p.value", colnames(rowData(rna_seq_dt)))]
rna_seq_filt <- rna_seq_dt[apply(as.matrix(p_val_dt) <= 0.05, 1, any),]
    
gsg <- goodSamplesGenes(datExpr = t(assay(rna_seq_filt)))
gsg$allOK

dt_list <- assay(rna_seq_filt)
rowMetadata <- rowData(rna_seq_filt)
metadata <- colData(rna_seq_filt)
```

## WGCNA Network

```{r}
wgcna_soft_thr <- WGCNA::pickSoftThreshold(data = t(dt_list), 
                                           networkType = "signed", powerVector = 1:30)
```

```{r}
spt <- wgcna_soft_thr
# par(mar=c(1,1,1,1))
plot(spt$fitIndices[,1],spt$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"))
text(spt$fitIndices[,1],spt$fitIndices[,2],col="red")
abline(h=0.80,col="red")
```

```{r}
# par(mar=c(1,1,1,1))
plot(spt$fitIndices[,1], spt$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(spt$fitIndices[,1], spt$fitIndices[,5], labels= spt$fitIndices[,1],col="red")
```

```{r}
setwd(params$output_dir)
# Network construction
bwnet <- blockwiseModules(datExpr = t(dt_list), power = 26, 
                        TOMType = "signed", minModuleSize = 30,
                        reassignThreshold = 0, mergeCutHeight = 0.25,
                        numericLabels = TRUE, saveTOMs = TRUE, loadTOM = TRUE,
                        saveTOMFileBase = "lima_blockwise", 
                        verbose = 3, randomSeed = 1234)
```


```{r}
# Convert labels to colors for plotting
mergedColors <-  labels2colors(bwnet$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(bwnet$dendrograms[[1]], mergedColors[bwnet$blockGenes[[1]]],
"Module colors",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```

```{r}
moduleLabels <- bwnet$colors
moduleColors <- labels2colors(bwnet$colors)
MEs <- bwnet$MEs

library(AnnotationDbi)
library(org.Mm.eg.db)
entrez_ids <- mapIds(x = org.Mm.eg.db, keys = names(moduleLabels), column = "ENTREZID", keytype = "ENSEMBL")
```

```{r}
cluster_ids <- lapply(unique(moduleColors), function(x){
    as.numeric(entrez_ids[moduleColors == x])
})
cluster_ids
names(cluster_ids) <- unique(moduleColors)
    
enrich_test <- compareCluster(geneClusters = cluster_ids, fun = "enrichGO", 
                        OrgDb = org.Mm.eg.db, keyType = "ENTREZID", ont = "ALL", 
                        pAdjustMethod = "fdr", pvalueCutoff = 0.05, 
                        qvalueCutoff = 0.05, universe = unlist(cluster_ids))
sem_data <- GOSemSim::godata(org.Mm.eg.db, ont = "ALL")

simplified_enrich <- clusterProfiler::simplify(enrich_test, OrgDb = org.Mm.eg.db)

GOenr <- GOenrichmentAnalysis(moduleColors, entrez_ids, organism = "mouse", nBestP = 10);
```


```{r}
# Network construction
net <- blockwiseModules(datExpr = t(dt_list), power = 3, maxBlockSize = 30000,
                        TOMType = "unsigned", minModuleSize = 30, 
                        reassignThreshold = 0, mergeCutHeight = 0.25,
                        numericLabels = TRUE, saveTOMs = TRUE, 
                        saveTOMFileBase = "lima_blockwise", verbose = 3)
```

```{r}
# Convert labels to colors for plotting
mergedColors <-  labels2colors(bwnet$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(bwnet$dendrograms[[1]], mergedColors[bwnet$blockGenes[[1]]],
"Module colors",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```