---
title: "DNA_Methylation_Additivity"
author: "Jordi Rofes Herrera"
date: "2023-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```
```{r}
fold_change_calc <- function (data, model_matrix, contrs, geometric_mean = TRUE, 
    log2_dt = TRUE) 
{
    if (log2_dt & !geometric_mean) {
        data <- 2^data
    }
    else if (!log2_dt & geometric_mean) {
        data <- log2(data)
    }
    contrast_matrix <- limma::makeContrasts(levels = model_matrix, 
        contrasts = contrs)
    sample_contrast <- model_matrix %*% contrast_matrix
    fold_changes <- apply(sample_contrast, 2, function(contrast) {
        sample_pos <- as.vector(contrast > 0)
        sample_neg <- as.vector(contrast < 0)
        if (geometric_mean) {
            fold_change <- apply(data, 1, function(protein) {
                mean(as.numeric(protein[sample_pos]), na.rm = TRUE) - 
                    mean(as.numeric(protein[sample_neg]), na.rm = TRUE)
            })
        }
        else {
            fold_change <- apply(data, 1, function(protein) {
                log2(mean(as.numeric(protein[sample_pos]), na.rm = TRUE)/mean(as.numeric(protein[sample_neg]), 
                    na.rm = TRUE))
            })
        }
        return(fold_change)
    })
    fold_changes <- as.data.frame(fold_changes)
    fold_changes
}
```


## Loading the data

```{r}
DNAme <- readRDS("prom_meth.RDS.gz")

dmr_DNAme_full <- DNAme[["dmr_matrix"]]
dmr_DNAme <- dmr_DNAme_full[,6:45]
CpG_DNAme <- DNAme[["methylation_matrix"]]
```

## Additivity

```{r}
library(ProteoNet)
library(ggplot2)
gf_cv_metadata <- data.frame("Samplename" = colnames(dmr_DNAme), "group" = substr(x = colnames(dmr_DNAme), start = 1, 2))
mod_mat <- model.matrix(~ group + 0, gf_cv_metadata)
colnames(mod_mat) <- gsub("group", "", colnames(mod_mat))

fc_mat <- fold_change_calc(dmr_DNAme, mod_mat, contrs = c("GF-CM", "CF-CM", "GM-CM"), geometric_mean = FALSE, log2_dt = FALSE)


ggplot(fc_mat) + 
    geom_point(aes(x = `CF-CM` + `GM-CM`, y = `GF-CM`, color = `GF-CM`)) + 
    theme_minimal() + 
    ylab("log2(GF/CM)") + xlab("log2(CF/CM) + log2(GM-CM)") + 
    geom_smooth(method = "lm", aes(x = `CF-CM` + `GM-CM`, y = `GF-CM`))

additivity_fc <- lm(`GF-CM` ~ `CF-CM` + `GM-CM`, data = fc_mat)
summary(additivity_fc)

df <- data.frame(x = predict(additivity_fc), y = additivity_fc$model$`GF-CM`)
ggplot(df, aes(x=x, y=y)) +
    geom_point(aes(color=y)) +
    ylab("log2(GF/CM)") +
    xlab("0.0854 + 0.699*log2(CF/CM) + 0.551*log2(GM/CM)") +
    geom_text(aes(x = -1, y = 3, label = "R^2 = 0.816")) +
    theme_minimal() +
    geom_smooth(method = "lm", se = F)
```


```{r}
library(plotly)
d3plot <- plot_ly(x = fc_mat$`GM-CM`, y = fc_mat$`CF-CM`, 
                          z = fc_mat$`GF-CM`, color = fc_mat$`GF-CM`)
d3plot <- d3plot %>% add_markers()
d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = "GM-CM"),
                            yaxis = list(title = "CF-CM"),
                            zaxis = list(title = "GF-CM")))
        
print(d3plot)
```

