---
title: "DNA Methylation Analysis"
author: "Jordi Rofes Herrera"
date: "2023-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.duplicate.label = "allow")
```

## Required packages

```{r}
library(MultiAssayExperiment)
library(rGREAT)
library(dplyr)
library(msigdbr)
library(knitr)
library(DT)
library(TxDb.Mmusculus.UCSC.mm39.refGene)
source("D:/Jordi/Doctorat/GNOTOBIOMICS/Utility Functions/utilities.R")
library(ggplot2)
txdb <- "TxDb.Mmusculus.UCSC.mm39.refGene"
```

## Loading the data

```{r}
multi_omic_dt <- readRDS("../Multi_Omics_Analysis/Merged_Multi_Omics.rds")
dna_met_dt <- multi_omic_dt[["DNA_Methylation.liver"]]


id_cols <- rowData(dna_met_dt)[,grep("\\.id$", colnames(rowData(dna_met_dt)))]
id_cols

num_cpgs_any <- as.data.frame(rowData(dna_met_dt)) %>% 
    mutate(width_range = width(rowRanges(dna_met_dt))) %>%
    group_by(geneName) %>% 
    summarise(sum_cpgs = sum(n_overlap_CpGs),
            sum_width = sum(width_range)) 

num_cpgs_any <- num_cpgs_any %>%
    mutate(sum_cpgs_perc = sum_cpgs/sum(sum_cpgs)) %>% arrange(desc(sum_width))

hist(num_cpgs_any$sum_cpgs_perc, breaks = 100)
num_cpgs_any
```

## DMRSeq results {.tabset}

```{r}
ctrs_names <- gsub(".adj.p.value", "", 
                    colnames(rowData(dna_met_dt))[grep("adj.p.value$", 
                                                colnames(rowData(dna_met_dt)))]) 
sig_tables <- lapply(ctrs_names, function(x){
    dna_met_dt[rowData(dna_met_dt)[[paste0(x, ".adj.p.value")]] <= 0.05]
})
names(sig_tables) <- ctrs_names

```

```{r}
lapply(sig_tables, nrow)
```

```{r}
methylation_res <- lapply(names(sig_tables), function(ctrs_names){
    col_fc_name <- paste0(ctrs_names, ".log2FC")
    ctrs_fc <- rowData(sig_tables[[ctrs_names]])[[col_fc_name]]
    data.frame("Positive log2FC" = sum(ctrs_fc > 0), "Negative log2FC" = sum(ctrs_fc < 0))
})
names(methylation_res) <- names(sig_tables)
methylation_res <- do.call(rbind, methylation_res)
methylation_res
```



<!-- ## Correlations with Gene Expression -->

<!-- ```{r} -->
<!-- network_omics <- list("DNA_Methylation_RNASeq" = grep("DNA|RNASeq", x = names(experiments(multi_omic_dt)), value = TRUE)) -->
<!-- variables_dicts <- lapply(network_omics[[1]], function(omic_name){ -->
<!--     if(omic_name == "RNASeq.liver"){ -->
<!--         return("gene_lab") -->
<!--     } else if(omic_name == "Untargeted_Metabolomics.liver"){ -->
<!--         return("HFD-CNT.PutativeMetabolites") -->
<!--         #return("HFD-CNT.formula") -->
<!--     } else if(grepl("16S|^Shotgun", omic_name)){ -->
<!--         return("specie_name_short") -->
<!--     } else if(grepl("DNA_Methylation", omic_name)){ -->
<!--         return("geneName") -->
<!--     } else{ -->
<!--         return(NA) -->
<!--     } -->
<!-- }) -->

<!-- # rmarkdown::render(input = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/Multi_Omic_Correlations/Correlations_Script.Rmd", -->
<!-- #                   output_file = "./correlation_networks_085_ch.html", -->
<!-- #                   params = list( -->
<!-- #                         corr_threshold = 0.85, -->
<!-- #                         multi_omic_path = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/Multi_Omics_Analysis/Multivariate_Merged_Multi_Omics.rds", -->
<!-- #                         group_metadata_var = "group", -->
<!-- #                         sample_levels_2_correlate = c("CNT", "HFD"), -->
<!-- #                         filter_variable_2_correlate = list( -->
<!-- #                             "HFD Altered" = quote(`HFD-CNT.adj.p.value` <= 0.05) -->
<!-- #                         ), -->
<!-- #                         omic_list_2_correlate = network_omics, -->
<!-- #                         rowData_variable_name_list = variables_dicts, -->
<!-- #                         draw_networks = TRUE, -->
<!-- #                         add_autocorrelations = FALSE, -->
<!-- #                         keep_full_correlations = TRUE, -->
<!-- #                         output_dir = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/DNA_met/", -->
<!-- #                         output_suffix = "hfc_cnt_085_ch", -->
<!-- #                         draw_cytoscape = FALSE) -->
<!-- #                   ) -->
<!-- #  -->
<!-- #  -->
<!-- # rmarkdown::render(input = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/Multi_Omic_Correlations/Correlations_Script.Rmd", -->
<!-- #                   output_file = "./correlation_networks_085_chi.html", -->
<!-- #                   params = list( -->
<!-- #                         corr_threshold = 0.85, -->
<!-- #                         multi_omic_path = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/Multi_Omics_Analysis/Multivariate_Merged_Multi_Omics.rds", -->
<!-- #                         group_metadata_var = "group", -->
<!-- #                         sample_levels_2_correlate = c("CNT", "HFD", "INT"), -->
<!-- #                         filter_variable_2_correlate = list( -->
<!-- #                             "HFD Altered" = quote(`HFD-CNT.adj.p.value` <= 0.05) -->
<!-- #                         ), -->
<!-- #                         omic_list_2_correlate = network_omics, -->
<!-- #                         rowData_variable_name_list = variables_dicts, -->
<!-- #                         draw_networks = TRUE, -->
<!-- #                         add_autocorrelations = FALSE, -->
<!-- #                         keep_full_correlations = TRUE, -->
<!-- #                         output_dir = "D:/Jordi/Doctorat/GNOTOBIOMICS/Data_Analysis/DNA_met/", -->
<!-- #                         output_suffix = "hfc_cnt_085_chi") -->
<!-- #                   ) -->

<!-- ``` -->


### Individual contrasts {.tabset}

#### Annotation plot

```{r}
omic_dt_list <- c("All Results" = multi_omic_dt[["DNA_Methylation.liver"]], sig_tables)

dmr_annotation_plot(omic_dt = omic_dt_list)

# apply(factor_tables[2:nrow(factor_tables),], 1, function(x){
#     if(all(x == 0)){return(NULL)} 
#     test_dt <- rbind(factor_tables[1,] - x, x)
#     print(test_dt)
#     test_dt <- rbind(factor_tables[1,], x)
#     test_dt
#     #test_dt
#     # fisher.test(test_dt, simulate.p.value = TRUE)
# })
# fisher.test(f1, simulate.p.value = TRUE)
```

#### Chromosome Plots

```{r, fig.height=6, fig.width=8}
possible_chromosomes  <- unique(seqnames(rowRanges(multi_omic_dt[["DNA_Methylation.liver"]])))
dmr_annotation_plot(omic_dt_list, annotation_labels = possible_chromosomes, 
                    annotation_metadata_var = "seqnames", x_lab = "Chromosome Proportions")
```


#### rGreat {.tabset}

```{r}
library(msigdbr)
    
h_gene_sets = msigdbr(species = "Mus musculus", category = "H")

h_gene_sets = split(h_gene_sets$entrez_gene, h_gene_sets$gs_name)
h_gene_sets = lapply(h_gene_sets, as.character)  # just to make sure gene IDs are all in character.
```

```{r}
set.seed(1234)
great_results <- lapply(sig_tables, function(ctrs_res){
    if(nrow(ctrs_res) == 0){return(NA)}
    sub_granges <- rowRanges(ctrs_res)
    mcols(sub_granges) <- mcols(sub_granges)[!colnames(mcols(sub_granges)) %in% 
                                               c("seqnames", "ranges", "strand", 
                                                "seqlevels", "seqlengths",
                                                "isCircular", "start", "end", 
                                                "width", "element")]  
    return(great(gr = sub_granges, gene_sets = h_gene_sets, 
                tss_source = txdb))
})


contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    return(getEnrichmentTable(gr_res))
})
contrs_names <- names(contrs_result_sig_list)
template <- c(
    "##### `r contrs_names[{{i}}]` \n",
    "```{r, echo = FALSE}\n",
    "datatable(contrs_result_sig_list[[{{i}}]], options = list(scrollX = TRUE))",
    "```\n",
    "\n"
)
```

```{r}
tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list, 
                                          contrs_names = contrs_names, template = template)
```

`r knit(text=unlist(tables_chunk))`

### Contrast list {.tabset}

```{r}
expression_list <- list(
    "HFD Altered" = quote(
        `HFD-CNT.adj.p.value` <= 0.05
    ),
    "INT Restored Up" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 & 
        ((`INT-HFD.adj.p.value` <= 0.05 & 
        `INT-CNT.adj.p.value` > 0.05) | 
            ((`INT-HFD.adj.p.value` > 0.05 & 
            `INT-CNT.adj.p.value` > 0.05) & 
                ((`INT-HFD.adj.p.value` < `INT-CNT.adj.p.value`) | 
                     ((`INT-HFD.adj.p.value` == `INT-CNT.adj.p.value`) & (abs(`INT-HFD.log2FC`) - abs(`INT-CNT.log2FC`)) > 0))))
    ), 
    "INT Restored Down" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 & 
        ((`INT-HFD.adj.p.value` <= 0.05 & 
        `INT-CNT.adj.p.value` > 0.05) | 
            ((`INT-HFD.adj.p.value` > 0.05 & 
            `INT-CNT.adj.p.value` > 0.05) & 
                ((`INT-HFD.adj.p.value` < `INT-CNT.adj.p.value`) | 
                     ((`INT-HFD.adj.p.value` == `INT-CNT.adj.p.value`) & (abs(`INT-HFD.log2FC`) - abs(`INT-CNT.log2FC`)) > 0))))
    ),
    "INT Restored Over Down" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 &
        `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` > 0 &
        `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` > 0
    ),
    "INT Restored Over Up" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` >= 0 &
        `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` < 0 &
        `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` < 0
    ),
    "INT Resistant Over Up" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` >= 0 & 
        `INT-CNT.adj.p.value` <= 0.05 &
        `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` >= 0
    ),
    "INT Resistant Over Down" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 & 
        `INT-CNT.adj.p.value` <= 0.05 &
        `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` < 0
    ),
    "INT Resistant Up" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` >= 0 & 
        ((`INT-CNT.adj.p.value` <= 0.05 & 
        `INT-HFD.adj.p.value` > 0.05) | 
            ((`INT-HFD.adj.p.value` > 0.05 & 
            `INT-CNT.adj.p.value` > 0.05) & 
                ((`INT-HFD.adj.p.value` > `INT-CNT.adj.p.value`) | 
                     ((`INT-HFD.adj.p.value` == `INT-CNT.adj.p.value`) & (abs(`INT-HFD.log2FC`) - abs(`INT-CNT.log2FC`)) < 0))))
    ),
    "INT Resistant Down" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 & 
        ((`INT-CNT.adj.p.value` <= 0.05 & 
        `INT-HFD.adj.p.value` > 0.05) | 
            ((`INT-HFD.adj.p.value` > 0.05 & 
            `INT-CNT.adj.p.value` > 0.05) & 
                ((`INT-HFD.adj.p.value` > `INT-CNT.adj.p.value`) | 
                     ((`INT-HFD.adj.p.value` == `INT-CNT.adj.p.value`) & (abs(`INT-HFD.log2FC`) - abs(`INT-CNT.log2FC`)) < 0))))
    ),
    "INT Resistant Half Up" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` >= 0 & 
        `INT-HFD.adj.p.value` <= 0.05 & `INT-CNT.adj.p.value` <= 0.05 &
        `INT-HFD.log2FC` < 0 & 
        `INT-CNT.log2FC` >= 0
    ),
    "INT Resistant Half Down" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 &
        `INT-HFD.adj.p.value` <= 0.05 & `INT-CNT.adj.p.value` <= 0.05 & 
        `INT-HFD.log2FC` >= 0 &
        `INT-CNT.log2FC` < 0
    ),
    "HFE Unaffected" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` > 0.05 & `HFE-HFD.adj.p.value` <= 0.05
    ),
    "HFE Affected equal HFD" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` <= 0.05 & `HFE-HFD.adj.p.value` > 0.05
    ),
    "HFE Affected diff HFD" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` <= 0.05 & `HFE-HFD.adj.p.value` <= 0.05
    ),
    "HFE Other" = quote(
        `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` > 0.05 & `HFE-HFD.adj.p.value` > 0.05
    )
)

# expression_list <- list(
#     "HFD Altered" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05)
#     ),
#     "INT Restored Up" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 & 
#         `INT-CNT.adj.p.value` > 0.05 
#     ), 
#     "INT Restored Down" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 &  
#         `INT-CNT.adj.p.value` > 0.05 
#     ),
#     "INT Restored Over Up" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 &
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` > 0 &
#         `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` > 0
#     ),
#     "INT Restored Over Down" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 &
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` < 0 &
#         `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` < 0
#     ),
#     "INT Resistant Over Up" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 & 
#         `INT-CNT.adj.p.value` <= 0.05 &
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` > 0)
#     ),
#     "INT Resistant Over Down" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 & 
#         `INT-CNT.adj.p.value` <= 0.05 &
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` < 0)
#     ),
#     "INT Resistant Up" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 & 
#         `INT-CNT.adj.p.value` <= 0.05 & 
#         `INT-HFD.adj.p.value` > 0.05) 
#     ),
#     "INT Resistant Down" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 & 
#         `INT-CNT.adj.p.value` <= 0.05 &
#         `INT-HFD.adj.p.value` > 0.05)
#     ),
#     "INT Resistant Half Up" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` > 0 & 
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` < 0 & 
#         `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` > 0)
#     ),
#     "INT Resistant Half Down" = quote(
#         (`HFD-CNT.adj.p.value` <= 0.05 & `HFD-CNT.log2FC` < 0 &
#         `INT-HFD.adj.p.value` <= 0.05 & `INT-HFD.log2FC` > 0 &
#         `INT-CNT.adj.p.value` <= 0.05 & `INT-CNT.log2FC` < 0)
#     ),
#     "HFE Unnaffected" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` > 0.05 & `HFE-HFD.adj.p.value` <= 0.05 
#     ),
#     "HFE Affected" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & `HFE-CNT.adj.p.value` <= 0.05 & `HFE-HFD.adj.p.value` > 0.05
#     ),
#     "HFE Other" = quote(
#         `HFD-CNT.adj.p.value` <= 0.05 & ((`HFE-CNT.adj.p.value` <= 0.05 & `HFE-HFD.adj.p.value` <= 0.05) |
#             (`HFE-CNT.adj.p.value` > 0.05 & `HFE-HFD.adj.p.value` > 0.05))
#     )
# )
```

```{r}
expression_list_sub <- list("Restored DMRs" = grep("Restored", names(expression_list), value = TRUE), 
                            "Resistant DMRs" = grep("Resistant", names(expression_list), value = TRUE))
# hfd_affected_cols <- grep("Affected", names(expression_list))


condition_OR <- function(eval_exprs){
    Reduce(f = function(x, y){expr(!!x | !!y)},
           x = eval_exprs)    
}

expression_list_sub <- lapply(expression_list_sub, function(eval_exprs){
    eval_exprs <- expression_list[eval_exprs]
    condition_OR(eval_exprs)
})

expression_list_sub$`HFE Unnaffected Genes` <- expression_list[[grep("HFE Unaffected", names(expression_list), value = TRUE)]]
expression_list_sub$`HFE Affected Genes` <- expression_list[[grep("HFE Affected", names(expression_list), value = TRUE)]]


sig_tables <- lapply(expression_list_sub, function(ctrs){
    row_dt <- rowData(dna_met_dt)
    subset(dna_met_dt, eval(ctrs, envir = row_dt))
})


lapply(sig_tables, nrow)
fc_dt_res <- lapply(sig_tables, function(ctrs_dt){
    fc_dt <- rowData(ctrs_dt)[["HFD-CNT.log2FC"]]
    data.frame("Positive HFD-CNT.log2FC" = sum(fc_dt > 0), "Negative HFD-CNT.log2FC" = sum(fc_dt < 0))
})
fc_dt_res <- do.call(rbind, fc_dt_res)
fc_dt_res


fc_dt_res2 <- lapply(sig_tables, function(ctrs_dt){
    fc_dt <- rowData(ctrs_dt)[["INT-HFD.log2FC"]]
    data.frame("Positive INT-HFD.log2FC" = sum(fc_dt > 0), "Negative INT-HFD.log2FC" = sum(fc_dt < 0))
})
fc_dt_res2 <- do.call(rbind, fc_dt_res2)
fc_dt_res2
# sig_tables2 <- lapply(expression_list_sub, function(ctrs){
#     row_dt <- rowData(dna_met_dt)
#     subset(dna_met_dt, eval(ctrs, envir = row_dt))
# })
```

#### Annotation Plot

```{r}
omic_dt_list <- c("All Results" = multi_omic_dt[["DNA_Methylation.liver"]], sig_tables)
dmr_annotation_plot(omic_dt = omic_dt_list)
# test_dt <- factor_tables[1:2,]
# fisher.test(factor_tables[1,])
```

#### Chromosome Plots

```{r, fig.height=6, fig.width=8}
possible_chromosomes  <- unique(seqnames(rowRanges(multi_omic_dt[["DNA_Methylation.liver"]])))
dmr_annotation_plot(omic_dt_list, annotation_labels = possible_chromosomes, 
                    annotation_metadata_var = "seqnames", x_lab = "Chromosome Proportions")
```


#### rGREAT {.tabset}

```{r}
set.seed(1234)

great_results <- lapply(sig_tables, function(ctrs_res){
    if(nrow(ctrs_res) == 0){return(NA)}
    sub_granges <- rowRanges(ctrs_res)
    mcols(sub_granges) <- mcols(sub_granges)[!colnames(mcols(sub_granges)) %in% 
                                               c("seqnames", "ranges", "strand", 
                                                "seqlevels", "seqlengths",
                                                "isCircular", "start", "end", 
                                                "width", "element")]    
    return(great(gr = sub_granges, gene_sets = h_gene_sets, 
                tss_source = txdb))
})


contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){return(data.frame())}
    return(getEnrichmentTable(gr_res))
})

contrs_names <- names(contrs_result_sig_list)

tables_chunk_2 <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list, 
                          contrs_names = contrs_names, 
                          template = template)
```

`r knit(text=unlist(tables_chunk_2))`


## Appendix

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}

```



