---
title: "DNAmet"
author: "jmb"
date: "7/28/2022"
output: html_document
---
## Set up environment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load needed packages
```{r include=FALSE}
library("BiocManager")
library("ggplot2")
library("stringi")
library("stringr")
library("tidyr")
library("ggpubr")
library("plyr")
library("dplyr")
library("knitr")
library("readxl")
library("writexl")
library("sva")
library("data.table")
library("biomaRt")
library("NOISeq")
library("tidyverse")
library("mgsub")
library("gtools")
library("purrr")
library("DESeq2")
library("mixOmics")
library("BiocParallel")
library("genefilter")
library("pheatmap")
library("RColorBrewer")
library("vsn")
library("IHW")
library("hexbin")
library("glmpca")
# library("EnhancedVolcano")
# library("airway")
library("magrittr")
library("topGO")
library("fgsea")
library("KEGGREST")
library("msigdbr")
# library("pathview")
library("clusterProfiler")
library("DOSE")
library("enrichplot")
register(MulticoreParam(4))
options(MulticoreParam=quote(MulticoreParam(workers=4)))
options(MulticoreParam=MulticoreParam(workers=4))
options(connectionObserver = NULL)
options(ggrepel.max.overlaps = Inf)
options("menu.graphics" = FALSE)
library("org.Mm.eg.db")
library("Rgraphviz")
library("ggupset")
library("gplots")
library("gt")
library("ggridges")
library("edgeR")
library("WGCNA") # https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/
library("proxyC")
library("EDASeq")
library("naniar")
library("ggnewscale")
library("cowplot")
library("Rtsne")
library("M3C")
library("devtools")
library("ggbiplot")
library("VennDiagram")
library("eulerr")
library("umap")
# library("xlsx")
# library("canceR")
# library("qpcR")
library("ggvenn")
library("MOFA2")
library("MOFAdata")
library("ReactomePA")
library("factoextra")
library("circlize")
library("ComplexHeatmap")
```

#DNA methylation dfs
```{r}
setwd ("~/Documents/PhD/ChroMe_PhD/data_omics_GFCV_lima/R_feb2022/DNAmet/")

DNAme <- readRDS("prom_meth.RDS.gz")

dmr_DNAme <- DNAme[["dmr_matrix"]]
CpG_DNAme <- DNAme[["methylation_matrix"]]

#dmr_DNAme
class(dmr_DNAme)

dmr_DNAme <- dplyr::select(dmr_DNAme, -chr,
                           -start, -end, -rid,
                           -n_overlap_CpGs)

cond_DNAme <- data.frame(samplename=colnames(dmr_DNAme))

cond_DNAme$type_gfcv <- stri_sub(cond_DNAme$samplename, 1,2)
cond_DNAme$gfcv <- stri_sub(cond_DNAme$samplename, 1,1)
cond_DNAme$sex <- stri_sub(cond_DNAme$samplename, 2,2)
cond_DNAme$batch <- stri_sub(cond_DNAme$samplename, 4,4)

dmr_DNAme_t <- as.data.frame(t(dmr_DNAme))


rownames(dmr_DNAme_t) <- cond_DNAme$samplename


#CpG_DNAme
class(CpG_DNAme)

CpG_DNAme <- dplyr::select(CpG_DNAme, -chr,
                           -start, -end, -rid,
                           -n_overlap_CpGs)


CpG_DNAme_t <- as.data.frame(t(CpG_DNAme))


rownames(CpG_DNAme_t) <- cond_DNAme$samplename

rownames(cond_DNAme) <- cond_DNAme$samplename


```


###PCA CpG_DNAme_t
```{r}


CpG_DNAme_t[is.na(CpG_DNAme_t)] <- 0


p_CpG <-mixOmics::pca(CpG_DNAme_t, ncomp = 3, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)


plotIndiv(p_CpG, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "methylation by condition .95",ellipse = T, ellipse.level = 0.95)

dim(CpG_DNAme_t)

###########################
# transform B to M-values #
###########################

transformToMvalues <- function(Beta) {
  Beta[Beta == 1] <- 0.99
  Beta[Beta == 0] <- 0.01
  M <- log2(Beta / (1 - Beta))
  return(M)
}


M_CpG_DNAme_t <- transformToMvalues(CpG_DNAme_t)

pM_CpG <-mixOmics::pca(M_CpG_DNAme_t, ncomp = 3, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)


plotIndiv(pM_CpG, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "M-values methylation by condition .95",ellipse = T, ellipse.level = 0.95)

dim(M_CpG_DNAme_t)

#eliminate outliers
CpG_DNAme_t_o <- CpG_DNAme_t %>%  t() %>% as.data.frame() %>% dplyr::select(., -CM51, -CM31) %>% t() %>% as.data.frame()

cond_DNAme_o <- cond_DNAme %>%  t() %>% as.data.frame() %>% dplyr::select(., -CM51, -CM31) %>% t() %>% as.data.frame()

CpG_DNAme_t_o <- CpG_DNAme_t_o[,-86724]

p_CpG_o <-mixOmics::pca(CpG_DNAme_t_o, ncomp = 3, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)



plotIndiv(p_CpG_o, ind.names = T, group = cond_DNAme_o$type_gfcv, legend = T, title= "methylation by condition .95",ellipse = T, ellipse.level = 0.95)

#eliminate outliers
CpG_DNAme_t_o <- CpG_DNAme_t %>%  t() %>% as.data.frame() %>% dplyr::select(., -CM51, -CM31, -GF22, -GM51, -CF41, -CF42) %>% t() %>% as.data.frame()

cond_DNAme_o <- cond_DNAme %>%  t() %>% as.data.frame() %>% dplyr::select(., -CM51, -CM31, -GF22, -GM51, -CF41, -CF42) %>% t() %>% as.data.frame()

dim(CpG_DNAme_t_o)

CpG_DNAme_t_o <- CpG_DNAme_t_o[,-86724]

p_CpG_o <-mixOmics::pca(CpG_DNAme_t_o, ncomp = 3, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)



plotIndiv(p_CpG_o, ind.names = T, group = cond_DNAme_o$type_gfcv, legend = T, title= "methylation by condition .95",ellipse = T, ellipse.level = 0.95)



```

###PCA dmr_DNAme_t
```{r}

dmr_DNAme[is.na(dmr_DNAme)] <- 0


dmr_DNAme_t <- as.data.frame(t(dmr_DNAme))

dim(dmr_DNAme_t)

p_dmr <-mixOmics::pca(dmr_DNAme_t, ncomp = 6, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)

pdf("GFCV_DMRs_11k_PCA_25oct2022.pdf")

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by condition .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$sex, legend = T, title= "dmr methylation by sex .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$batch, legend = T, title= "dmr methylation by batch .99",ellipse = T, ellipse.level = 0.99)


plotIndiv(p_dmr,comp = c(1,3), ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by condition .99",ellipse = T, ellipse.level = 0.99)


plotIndiv(p_dmr,comp = c(2,3), ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by condition .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr,comp = c(1,4), ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by condition .99",ellipse = T, ellipse.level = 0.99)

# plotIndiv(p_dmr,comp = c(1,2,3), ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by condition .99",ellipse = T, ellipse.level = 0.99, style = "3d")
dev.off()

dim(CpG_DNAme_t)

```

###Heatmap DMR
```{r}
library("ComplexHeatmap")
dim(dmr_DNAme_t)

pdf("GFCV_DMRs_11k_heatmap_25oct2022.pdf")

col_fun = colorRamp2(c(0,0.3, 0.6, 1), c("#FDE725FF", "#91D742FF","#297A8EFF", "#440154FF"))

Heatmap(dmr_DNAme_t, row_km = 4,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(dmr_DNAme_t, row_km = 3,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(dmr_DNAme_t, row_km = 2,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)
dev.off()
```

Union DMR and promoter CpGs
```{r}
# 
# 
# dmr_matrix <- DNAme[["dmr_matrix"]]
# methylation_matrix <- DNAme[["methylation_matrix"]]
# 
# methylation_matrix$chr <- as.character(methylation_matrix$chr)
# 
# lengh_dmr <- dmr_matrix$end-dmr_matrix$start
# max(lengh_dmr)
# 
# union_dmr_CpG <- data.frame()
# 
# ### seems to work, but very slow NOT
# for(i in 1:nrow(dmr_matrix)){
#   dmr <- dmr_matrix[i,]
#   dmr$chr <- as.character(dmr$chr)
#   methylation_matrix_temp <-  methylation_matrix %>% 
#     dplyr::filter(.,chr==dmr$chr)
#   methylation_matrix_temp2 <- methylation_matrix_temp[methylation_matrix_temp$start %[]%
#     c(dmr$start & dmr$end)]|
#     methylation_matrix_temp[methylation_matrix_temp$start %[[%
#       c(dmr$start:dmr$end)]|
#     methylation_matrix_temp[methylation_matrix_temp$start %]]%
#       c(dmr$start:dmr$end)]|
#     methylation_matrix_temp[methylation_matrix_temp$start %[]%
#       c(dmr$start -1109 & dmr$end + 1109)]
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{rm(methylation_matrix_temp2)}
# }
# 
# 
# ### seems to work, but very slow NOT
# for(i in 1:nrow(dmr_matrix)){
#   dmr <- dmr_matrix[i,]
#   dmr$chr <- as.character(dmr$chr)
#   methylation_matrix_temp <-  methylation_matrix %>% 
#     dplyr::filter(.,chr==dmr$chr)
#   for(j in 1:nrow(methylation_matrix_temp)){
#     promoter <- methylation_matrix_temp[j,]
#   methylation_matrix_temp2 <- promoter[promoter$start %[]%
#     c(start <= dmr$start & end >= dmr$end)|
#       c(dmr$start %in% (start:end))|
#       c(dmr$end %in% (start:end))|
#       c(start >= dmr$start -1109 & end <= dmr$end + 1109)]
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{rm(methylation_matrix_temp2)}}
# }
# 
# 
# d.diamonds[d.diamonds$price %[]% c(2400,2510),]
# 
# 
# #NOT CORRECT
# for(i in 1:nrow(dmr_matrix)){
#   dmr <- dmr_matrix[i,]
#   dmr$chr <- as.character(dmr$chr)
#   methylation_matrix_temp <-  methylation_matrix %>% 
#     dplyr::filter(.,chr==dmr$chr)
#   methylation_matrix_temp2 <- apply(methylation_matrix_temp, 1, function(x)
#    dplyr::filter(x,
#     (start <= dmr$start & end >= dmr$end)|
#       (dmr$start %in% (start:end) & end <= dmr$end +2108)|
#       (start >= dmr$start -2108 & (dmr$end %in% (start:end)))|
#       (start >= dmr$start -1109 & end <= dmr$end + 1109)))
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{rm(methylation_matrix_temp2)}
# }
# 
# 
# 
# ### seems to work, but very slow
# for(i in 1:nrow(dmr_matrix)){
#   dmr <- dmr_matrix[i,]
#   dmr$chr <- as.character(dmr$chr)
#   methylation_matrix_temp <-  methylation_matrix %>% 
#     dplyr::filter(.,chr==dmr$chr)
#   for(j in 1:nrow(methylation_matrix_temp)){
#     promoter <- methylation_matrix_temp[j,]
#   methylation_matrix_temp2 <- dplyr::filter(
#     promoter,
#     (start <= dmr$start & end >= dmr$end)|
#       (dmr$start %in% (start:end) & end <= dmr$end +2108)|
#       (start >= dmr$start -2108 & (dmr$end %in% (start:end))|
#       (start >= dmr$start -1109 & end <= dmr$end + 1109)))
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{rm(methylation_matrix_temp2)}}
# }
# 
# 
# 
# for(i in 1:nrow(dmr_matrix)){
#   dmr <- dmr_matrix[i,]
#   dmr$chr <- as.character(dmr$chr)
#   methylation_matrix_temp <-  methylation_matrix %>% dplyr::filter(
#   .,chr==dmr$chr)
#   methylation_matrix_temp2 <- dplyr::filter(methylation_matrix_temp,
#                                             start <= dmr$start & end >= dmr$end)
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{
#     methylation_matrix_temp2 <- dplyr::filter(methylation_matrix_temp, 
#                    start <= dmr$start & end <= dmr$end +2108)}
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#  else{
#    methylation_matrix_temp2 <- dplyr::filter(methylation_matrix_temp, 
#                    start >= dmr$start -2108 & end >= dmr$end)}
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#  else{
#   methylation_matrix_temp2 <- dplyr::filter(methylation_matrix_temp, 
#                    start >= dmr$start -1109 & end <= dmr$end + 1109)}
#   if(nrow(methylation_matrix_temp2) != 0 ){
#     union_dmr_CpG <- dplyr::bind_rows(union_dmr_CpG,
#                                     methylation_matrix_temp2)}
#   else{rm(methylation_matrix_temp2)}
#             
# }
# 

```

PCA union CpGs and DMR
```{r}
# union_dmr_CpG[is.na(union_dmr_CpG)] <- 0
# 
# colnames(union_dmr_CpG[,1:5])
# 
# union_dmr_CpG_t <- dplyr::select(union_dmr_CpG, -chr,-start,
#                                  -end, -n_overlap_CpGs, -rid)
# 
# View(union_dmr_CpG_t)
# 
# rwn <- rownames(union_dmr_CpG_t)
# 
# rwn <- stri_sub(rwn, 1,20)
# 
# union_dmr_CpG_t$gene_id <- rwn
# 
# union_dmr_CpG_t <- dplyr::distinct(union_dmr_CpG_t)
# dim(union_dmr_CpG_t)
# 
# 
# union_dmr_CpG_t <- as.data.frame(t(union_dmr_CpG_t))
# 
# p_union <-mixOmics::pca(union_dmr_CpG_t, ncomp = 6, center = TRUE, scale = T,
#          max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
#          V = NULL, multilevel = NULL)
# 
# 
# 
# plotIndiv(p_union, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "union dmr & promoter methylation by condition .99",ellipse = T, ellipse.level = 0.99)

```

Heatmap union CpGs and DMR
```{r}
library("ComplexHeatmap")
# dim(union_dmr_CpG_t)
# 
# Heatmap(union_dmr_CpG_t,km = 4)
# 
# col_fun = colorRamp2(c(0,0.3, 0.6, 1), c("#FDE725FF", "#91D742FF","#297A8EFF", "#440154FF"))
# 
# Heatmap(union_dmr_CpG_t, row_km = 4,name = "promo&dmr",
#         show_column_names = F,
#         cluster_rows = T, border = T, col =col_fun)
# 
# Heatmap(union_dmr_CpG_t, row_km = 3,name = "promo&dmr",
#         show_column_names = F,
#         cluster_rows = T, border = T, col =col_fun)
# 
# Heatmap(union_dmr_CpG_t, row_km = 2,name = "promo&dmr",
#         show_column_names = F,
#         cluster_rows = T, border = T, col =col_fun)
```

#DMR 20k and 10k annotated
```{r}

DMR_object <- readRDS("dmr_annotation.RDS.gz")

all_dmrs <- as.data.frame(row.names = 1:21514,DMR_object[["all_dmrs"]])
dim(all_dmrs)

merged_dmrs <- as.data.frame(DMR_object[["dmrs_merged"]])
dim(merged_dmrs)
```

###PCA merged_dmrs
```{r}
DNAme <- readRDS("prom_meth.RDS.gz")

dmr_matrix <- DNAme[["dmr_matrix"]]

#put ID to regions create metadata df
dmr_matrix$feature_id <- rownames(dmr_matrix)

merged_dmrs <- dplyr::rename(merged_dmrs, chr=seqnames)

merged_dmrs$feature_id <- paste0(merged_dmrs$chr,":",
                                 merged_dmrs$start,
                                "_",merged_dmrs$end)

dmr_matrix_id <- dplyr::inner_join(merged_dmrs,
                                   dmr_matrix,
                                   by=c("feature_id","chr","start","end"))

dim(dmr_matrix_id)
View(dmr_matrix_id)
table(isUnique(dmr_matrix_id$feature_id))

rownames(dmr_matrix_id) <- dmr_matrix_id$feature_id

colnames(dmr_matrix_id[1:21])


meta_dmr_id <- dmr_matrix_id[,1:21]

dmr_matrix_id2 <- dmr_matrix_id[,22:61]

# PCA dmr_matrix_id2

dmr_matrix_id2_t <- as.data.frame(t(dmr_matrix_id2))

dim(dmr_matrix_id2_t)

p_dmr <-mixOmics::pca(dmr_matrix_id2_t, ncomp = 6, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)



plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation by type_gfcv .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$gfcv, legend = T, title= "dmr methylation by gfcv .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$sex, legend = T, title= "dmr methylation by sex .99",ellipse = T, ellipse.level = 0.99)

plotIndiv(p_dmr, ind.names = T, group = cond_DNAme$batch, legend = T, title= "dmr methylation by batch .99",ellipse = T, ellipse.level = 0.99)




```


###Heatmap merged_dmrs
```{r}
library("ComplexHeatmap")
dim(dmr_matrix_id2_t)

# Heatmap(dmr_matrix_id2_t,km = 4, )

col_fun = colorRamp2(c(0,0.3, 0.6, 1), c("#FDE725FF", "#91D742FF","#297A8EFF", "#440154FF"))

Heatmap(dmr_matrix_id2_t, row_km = 4,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(dmr_matrix_id2_t, row_km = 3,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(dmr_matrix_id2_t, row_km = 2,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

```
###DMR and RNAseq union
```{r}

rna_ID_sig <- read.csv(file ="~/Documents/PhD/ChroMe_PhD/data_omics_GFCV_lima/R_feb2022/RNAseq/GFCV_DEg_LRT_general_Sig_20k_jun2022.csv",
                       header = T, sep = ",",stringsAsFactors = F)
dim(rna_ID_sig)

dmr_matrix_id <- dplyr::rename(dmr_matrix_id, ensembl_gene_id=ENSEMBL)


union_rna_dmr <- dplyr::inner_join(rna_ID_sig,dmr_matrix_id,
                                   by="ensembl_gene_id")
dim(union_rna_dmr)

unique_genes <- data.frame(ensembl_gene_id=union_rna_dmr$ensembl_gene_id)

unique_genes <- dplyr::distinct(unique_genes)


# test PCA with DMR data present in sig DE genes in RNA

union_rna_dmr_test <- union_rna_dmr
dim(union_rna_dmr_test)

union_rna_dmr_test <- dplyr::select(union_rna_dmr_test,-X)
# union_rna_dmr_test <- dplyr::select(union_rna_dmr_test,-entrezgene_accession)
union_rna_dmr_test <- dplyr::select(union_rna_dmr_test,-entrezgene_id)


union_rna_dmr_test <- dplyr::distinct(union_rna_dmr_test)
dim(union_rna_dmr_test)


rownames(union_rna_dmr_test) <- paste0(union_rna_dmr_test$entrezgene_accession,"_",
                                       union_rna_dmr_test$feature_id)

union_rna_dmr_test <- dplyr::select(union_rna_dmr_test, CF11:GM52)


union_rna_dmr_test_t <- as.data.frame(t(union_rna_dmr_test))

p_dmr_rna <-mixOmics::pca(union_rna_dmr_test_t, ncomp = 6, center = TRUE, scale = T,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)


pdf("GFCV_DMRs_union_RNAid_PCA&heatmap_27oct2022.pdf")
plotIndiv(p_dmr_rna, ind.names = T, group = cond_DNAme$type_gfcv, legend = T, title= "dmr methylation match RNA by type_gfcv .99",ellipse = T, ellipse.level = 0.99)


#Heatmap with DMR data present in sig DE genes in RNA

col_fun = colorRamp2(c(0,0.3, 0.6, 1), c("#FDE725FF", "#91D742FF","#297A8EFF", "#440154FF"))

Heatmap(union_rna_dmr_test_t, row_km = 4,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(union_rna_dmr_test_t, row_km = 3,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

Heatmap(union_rna_dmr_test_t, row_km = 2,name = "DMR mean",
        show_column_names = F,
        cluster_rows = T, border = T, col =col_fun)

dev.off()

```

#Mean methylation
```{r}
dim(union_rna_dmr_test_t)

mean_DMR <- apply(union_rna_dmr_test_t[,1:nrow(
  union_rna_dmr_test_t)], 1, mean)


mean_DMR_df <- data.frame(mean_Bvalue_dmr=mean_DMR)

rwn <- names(mean_DMR)

rownames(mean_DMR_df) <- rwn

dim(mean_DMR_df)


plot <- ggplot(mean_DMR_df, aes(x=cond_DNAme$type_gfcv, y=mean_Bvalue_dmr, fill=cond_DNAme$type_gfcv)) + 
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(width = 0.2, height = 0, size= 2.5, aes(shape=cond_DNAme$sex)) +
    #geom_point() +
    #scale_shape_manual(values = c(21,22)[genderGFCV]) +  ###ASK TERESA
    #geom_dotplot(binaxis = "y", stackdir = "center", method = "histodot") +
    ggtitle("Mean DMRs B-values per individueal liv") +
    xlab("Condition") + ylab("Counts") +
    theme_classic() +
    theme(plot.title = element_text(size = 22, face = "bold")) +
    scale_fill_manual(values=c("#EB6429FF", "#30B57CFF","#FCAC11FF","#84D44BFF"), 
                      name="Experimental\nCondition",
                      breaks=c("CF", "CM","GF","GM"),
                      labels=c("conv F (CF)","conv M (CM)","germfree F (GF)", "germfree M (GM)")) +
    geom_signif(comparisons = list(c("CF", "CM"),c("GF", "GM"),c("GF", "CF"),c("GM", "CM")), 
                map_signif_level=TRUE, step_increase = 0.07) 
  print(plot)

  

## Boxplots all groups toguether no-vsd data
pdf("GFCVdmr_liv_Bvalues_wilcox_allgroups_27oct2022.pdf")
for (i in colnames(union_rna_dmr_test_t)) {
  ptm <- union_rna_dmr_test_t[,i,drop=T]      # creats a temp list of values for each ptm in col i
  plot <- ggplot(union_rna_dmr_test_t, aes(x=cond_DNAme$type_gfcv, y=ptm, fill=cond_DNAme$type_gfcv), main= i) + 
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(width = 0.2, height = 0, size= 2.5, aes(shape=cond_DNAme$sex)) +
    #geom_point() +
    #scale_shape_manual(values = c(21,22)[genderGFCV]) +  ###ASK TERESA
    #geom_dotplot(binaxis = "y", stackdir = "center", method = "histodot") +
    ggtitle(paste0(i, " liv")) +
    xlab("Condition") + ylab("Counts") +
    theme_classic() +
    theme(plot.title = element_text(size = 22, face = "bold")) +
    scale_fill_manual(values=c("#EB6429FF", "#30B57CFF","#FCAC11FF","#84D44BFF"), 
                      name="Experimental\nCondition",
                      breaks=c("CF", "CM","GF","GM"),
                      labels=c("conv F (CF)","conv M (CM)","germfree F (GF)", "germfree M (GM)")) +
    geom_signif(comparisons = list(c("CF", "CM"),c("GF", "GM"),c("GF", "CF"),c("GM", "CM")), 
                map_signif_level=TRUE, step_increase = 0.07) 
  print(plot)                # plots for each compound
}
dev.off()


#M-values

M_union_rna_dmr_test_t <- transformToMvalues(union_rna_dmr_test_t)

dim(M_union_rna_dmr_test_t)



mean_DMR_M <- apply(M_union_rna_dmr_test_t[,1:nrow(
  M_union_rna_dmr_test_t)], 1, mean)


mean_DMR_M_df <- data.frame(mean_Mvalue_dmr=mean_DMR_M)

rwn <- names(mean_DMR_M)

rownames(mean_DMR_M_df) <- rwn

dim(mean_DMR_M_df)


plot <- ggplot(mean_DMR_M_df, aes(x=cond_DNAme$type_gfcv, y=mean_Mvalue_dmr, fill=cond_DNAme$type_gfcv)) + 
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(width = 0.2, height = 0, size= 2.5, aes(shape=cond_DNAme$sex)) +
    #geom_point() +
    #scale_shape_manual(values = c(21,22)[genderGFCV]) +  ###ASK TERESA
    #geom_dotplot(binaxis = "y", stackdir = "center", method = "histodot") +
    ggtitle("Mean DMRs M-values per individueal liv") +
    xlab("Condition") + ylab("Counts") +
    theme_classic() +
    theme(plot.title = element_text(size = 22, face = "bold")) +
    scale_fill_manual(values=c("#EB6429FF", "#30B57CFF","#FCAC11FF","#84D44BFF"), 
                      name="Experimental\nCondition",
                      breaks=c("CF", "CM","GF","GM"),
                      labels=c("conv F (CF)","conv M (CM)","germfree F (GF)", "germfree M (GM)")) +
    geom_signif(comparisons = list(c("CF", "CM"),c("GF", "GM"),c("GF", "CF"),c("GM", "CM")), 
                map_signif_level=TRUE, step_increase = 0.07) 
  print(plot)


```


#XXXXXXXXXXXXXXXXXXXXXXXXXXX
###MOFA 
####Preparing df for MOFA
```{r}

dim(union_dmr_CpG_t)
View(union_dmr_CpG_t)
class(union_dmr_CpG_t)
dim(cond_DNAme)


cln <- colnames(union_dmr_CpG_t)

cln <- stri_sub(cln, 1, 18)

colnames(union_dmr_CpG_t) <- cln

union_dmr_CpG_t$samplename <- rownames(union_dmr_CpG_t)

union_dmr_CpG_t <- dplyr::inner_join(cond_DNAme,union_dmr_CpG_t, 
                                     by="samplename")


union_dmr_CpG_t_m <- reshape2::melt(union_dmr_CpG_t, 
                                    id.vars = c("samplename",
                                                "type_gfcv",
                                                "gfcv","sex",
                                                "batch"),
                                    variable.name = "feature",
                                    value.name = "value")

dim(union_dmr_CpG_t_m)

union_dmr_CpG_t_m <- dplyr::select(union_dmr_CpG_t_m, -gfcv,
                                   -sex, -batch)


colnames(union_dmr_CpG_t_m) <- c("sample", "group", 
                                 "feature" , "value")

union_dmr_CpG_t_m$feature <- stri_sub(union_dmr_CpG_t_m$feature, 1,18)


union_dmr_CpG_t_m$view <- "DNAme"

union_dmr_CpG_t_m <- dplyr::relocate(union_dmr_CpG_t_m, feature, .before = "group" )
union_dmr_CpG_t_m <- dplyr::relocate(union_dmr_CpG_t_m, view, .before = "group" )
# union_dmr_CpG_t_m <- dplyr::filter(union_dmr_CpG_t_m, !is.na(value))
union_dmr_CpG_t_m_mg <- union_dmr_CpG_t_m   #multi-group framework option
union_dmr_CpG_t_m <- dplyr::select(union_dmr_CpG_t_m, -group)

head(union_dmr_CpG_t_m)
dim(union_dmr_CpG_t_m)
```
####Prepare MOFArna object
```{r}

# preparing MOFA parameters

MOFAobject_DNAme_u <- union_dmr_CpG_t_m



dim(MOFAobject_DNAme_u)



MOFAobject_DNAme_u_mofa <- create_mofa_from_df(MOFAobject_DNAme_u)


print(MOFAobject_DNAme_u_mofa)



#data options
data_opts_rna <- get_default_data_options(MOFAobject_DNAme_u_mofa)
head(data_opts_rna)

data_opts_rna$scale_views <- T
data_opts_rna$scale_groups <- F

head(data_opts_rna)


#model options
model_opts_rna <- get_default_model_options(MOFAobject_DNAme_u_mofa)
head(model_opts_rna)

model_opts_rna$num_factors <- 3
head(model_opts_rna)


#training options
train_opts_rna <- get_default_training_options(MOFAobject_DNAme_u_mofa)
head(train_opts_rna)

train_opts_rna$convergence_mode <- "slow"
train_opts_rna$drop_factor_threshold <- -1
train_opts_rna$maxiter <- 10000


#prepare MOFAobject_DNAme_u_mofa
MOFAobject_DNAme_u_mofa <- prepare_mofa(
  object = MOFAobject_DNAme_u_mofa,
  data_options = data_opts_rna,
  model_options = model_opts_rna,
  training_options = train_opts_rna
)



# Train MOFAobject_DNAme_u_mofa 
outfile = file.path(getwd(),"model_dna_u.hdf5")
MOFAobject_DNAme_u_mofa_trained <- run_mofa(MOFAobject_DNAme_u_mofa, outfile, use_basilisk = TRUE)

plot_factor_cor(MOFAobject_DNAme_u_mofa_trained)
```
```


```{r}
```


```{r}
```

```{r}
```

