---
title: "Master Script"
author: "Jordi Rofes Herrera"
date: "28/1/2022"
output: html_document
params: 
    input_dir: "../../inputs/Untargeted_Metabolomics/"
    output_dir: "../../outputs/Untargeted_Metabolomics/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Experiment Processing

```{r}
db_path <- paste0(params$input_dir, "FullHMDB_Chebi_Tripeptides_db.csv")

hermes_results_path <- paste0(params$output_dir, "Hermes_Results/")
if(!dir.exists(hermes_results_path)){dir.create(hermes_results_path)}

hp_output_path <- paste0(hermes_results_path, "Hilic_Positive/")
if(!dir.exists(hp_output_path)){dir.create(hp_output_path)}

rmarkdown::render(input = "./Hermes_Analysis.Rmd",
                  output_file = paste0(hp_output_path, "Hermes_Report.html"), 
                  clean = TRUE, params = list(
    ms1_dir = paste0(params$input_dir, "Hilic_Positive/Hermes_Files/"), 
    qc_names =  "QC", blank_names = "Blank",
    met_db = db_path, met_db_sep = ",",
    ppm_error = 10, instrument = "QTOF", resolution = 30000, 
    noise_int = 1000, ionization = "+", labelled = FALSE,
    ad_list = c("M+H", "M+NH4", "M+Na", "M+K", "M+"), 
    min_max_mz = c(50, 1500), 
    add_charge = 1, add_mult = 1,
    soi_detection_type = "double",
    output_dir = hp_output_path,
    consensus = TRUE, soi_consensus = 1:3))


hn_output_path <- paste0(hermes_results_path, "Hilic_Negative/")
if(!dir.exists(hn_output_path)){dir.create(hn_output_path)}

rmarkdown::render(input = "./Hermes_Analysis.Rmd",
                  output_file = paste0(hn_output_path, "Hermes_Report.html"), 
                  clean = TRUE, params = list(
    ms1_dir = paste0(params$input_dir, "Hilic_Negative/Hermes_Files/"), 
    qc_names =  "QC", blank_names = "Blank", 
    met_db = db_path, met_db_sep = ",",
    ppm_error = 10, instrument = "QTOF", resolution = 30000, 
    noise_int = 1000, ionization = "-", labelled = FALSE,
    ad_list = c("M-H", "M+Cl"), 
    min_max_mz = c(50, 1500), 
    add_charge = 1, add_mult = 1,
    soi_detection_type = "double", soi_filter_ids = 1:3,
    output_dir = hn_output_path,
    consensus = TRUE, soi_consensus = 1:3))

rp_output_path <- paste0(hermes_results_path, "RP_Positive/")
if(!dir.exists(rp_output_path)){dir.create(rp_output_path)}

rmarkdown::render(input = "./Hermes_Analysis.Rmd",
                  output_file = paste0(rp_output_path, "Hermes_Report.html"), 
                  clean = TRUE, params = list(
    ms1_dir = paste0(params$input_dir, "RP_Positive/Hermes_Files/"), 
    qc_names =  "QC", blank_names = "Blank",
    met_db = db_path, met_db_sep = ",",
    ppm_error = 10, instrument = "QTOF", resolution = 30000, 
    noise_int = 1000, ionization = "+", labelled = FALSE,
    ad_list = c("M+H", "M+NH4", "M+Na", "M+K", "M+"), 
    min_max_mz = c(50, 1500), 
    add_charge = 1, add_mult = 1,
    soi_detection_type = "double", soi_filter_ids = 1:3,
    output_dir = rp_output_path,
    consensus = TRUE, soi_consensus = 1:3))

```

```{r}
rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
                  output_file = "./Hermes_Results/Hilic_Positive/xcms_hermes_results.html", clean = TRUE, 
                  params = list(metadata_file = "./Hilic_Positive/LC_M S_metadata.csv",
    xcms_hermes_file = "./Hermes_Results/Hilic_Positive/summarized_hermes_xcms.rds",
    hermes_file = "./Hermes_Results/Hilic_Positive/filteredSoiLists.rds",
    qc_name = "HP_QC",
    blank_name = "HP_Blank",
    output_results = "./Hermes_Results/Hilic_Positive/",
    data_type = "Hilic Positive"))

rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
                  output_file = "./Hermes_Results/Hilic_Negative/xcms_hermes_results.html", clean = TRUE, 
                  params = list(metadata_file = "./Hilic_Negative/LC_MS_metadata.csv",
    xcms_hermes_file = "./Hermes_Results/Hilic_Negative/summarized_hermes_xcms.rds",
    hermes_file = "./Hermes_Results/Hilic_Negative/filteredSoiLists.rds", 
    qc_name = "HN_QC",
    blank_name = "HN_Blank",
    output_results = "./Hermes_Results/Hilic_Negative/",
    data_type = "Hilic Negative"))

rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
                  output_file = "./Hermes_Results/RP_Positive/xcms_hermes_results.html", 
                  clean = TRUE, 
                  params = list(metadata_file = "./RP_Positive/LC_MS_metadata.csv",
    hermes_file = "./Hermes_Results/RP_Positive/filteredSoiLists.rds",
    xcms_hermes_file = "./Hermes_Results/RP_Positive/summarized_hermes_xcms.rds",
    qc_name = "RP_QC",
    blank_name = "RP_Blank",
    output_results = "./Hermes_Results/RP_Positive/",
    data_type = "RP Positive"))
```

