---
title: "Master Script"
author: "Jordi Rofes Herrera"
date: "28/1/2022"
output: html_document
params: 
    input_dir: "../../inputs/Untargeted_Metabolomics/"
    output_dir: "../../outputs/Untargeted_Metabolomics/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
```

## Experiment Processing

```{r}
library(SummarizedExperiment)
db_path <- paste0(params$input_dir, "FullHMDB_Chebi_Tripeptides_db.csv")

hermes_results_path <- paste0(params$output_dir, "Hermes_Results/")
if(!dir.exists(hermes_results_path)){dir.create(hermes_results_path)}

column_ids <- c("Hilic_Positive", "Hilic_Negative", "RP_Positive")
positive_adducts <- c("M+H", "M+NH4", "M+Na", "M+K", "M+")
negative_adducts <- c("M-H", "M+Cl")

gfcv_exp <- list()
lima_exp <- list()

for(id in column_ids){
    output_path <- paste0(hermes_results_path, id, "/")    
    if(!dir.exists(output_path)){dir.create(output_path)}
    
    file_dir <- paste0(params$input_dir, id, "/")
    hermes_files <- paste0(file_dir, "Hermes_Files/")
    
    hermes_output_path <- paste0(output_path, "filteredSoiLists.rds") 
    ## HERMES Analysis
    
    if(!file.exists(hermes_output_path)){
        param_list <- list(ms1_dir = hermes_files, 
                            qc_names =  "QC", blank_names = "Blank",
                            met_db = db_path, met_db_sep = ",",
                            ppm_error = 10, instrument = "QTOF", resolution = 30000, 
                            noise_int = 1000, labelled = FALSE,
                            min_max_mz = c(50, 1500), 
                            add_charge = 1, add_mult = 1,
                            soi_detection_type = "double",
                            output_dir = output_path,
                            consensus = TRUE, 
                            soi_consensus = 1:3)
        param_list$ionization <- ifelse(grepl("Positive", x = id, 
                                                ignore.case = TRUE), 
                                        "+", "-")
        param_list$ad_list <- ifelse(grepl("Positive", x = id, 
                                                ignore.case = TRUE), 
                                        positive_adducts, negative_adducts)
        rmarkdown::render(input = "./Hermes_Analysis.Rmd",
                      output_file = paste0(output_path, "Hermes_Report.html"), 
                      clean = TRUE, params = param_list)
    }
    
    ## XCMS Analysis
    metadata_path <- paste0(file_dir, "LC_MS_metadata.csv")
    xcms_hermes_output_path <- paste0(output_path, "summarized_hermes_xcms.rds")
    
    if(!file.exists(xcms_hermes_output_path)){
        param_list <- list(
            file_dir = file_dir,
            metadata_file = metadata_path,
            output_dir = output_path
        )
            
        rmarkdown::render(input = "./XCMS_Analysis.Rmd",
                  output_file = paste0(output_path, "XCMS_Analysis.html"), 
                  clean = TRUE, params = param_list)    
    }
    
    ## XMCS-HERMES Analysis
    untargeted_lima_output <- paste0(output_path, "xcms_hermes_exp_lima.rds")
    untargeted_gfcv_output <- paste0(output_path, "xcms_hermes_exp_gfcv.rds")
    
    if(!file.exists(untargeted_lima_output)){
        param_list <- list(
            metadata_file = metadata_path,
            xcms_hermes_file = xcms_hermes_output_path,
            hermes_file = hermes_output_path,
            output_results = output_path
        )
        switch(id, "Hilic_Positive" = {
            param_list$qc_name <- "HP_QC"
            param_list$blank_name  <- "HP_Blank"
            param_list$data_type <- "Hilic_Positive"
            param_list$mummichog_ionization <- "positive"
        }, "Hilic_Negative" = {
            param_list$qc_name <- "HN_QC"
            param_list$blank_name <- "HN_Blank"
            param_list$data_type <- "Hilic_Negative"
            param_list$mummichog_ionization <- "negative"
        }, "RP_Positive" = {
            param_list$qc_name <- "RP_QC"
            param_list$blank_name <- "RP_Blank"
            param_list$data_type <- "RP_Positive"
            param_list$mummichog_ionization <- "positive"
        })
        
        rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
                      output_file = paste0(output_path, "xcms_hermes_results.html"), 
                      clean = TRUE, params = param_list, envir = new.env())
    }

    gfcv_exp[[id]] <- readRDS(untargeted_gfcv_output)
    lima_exp[[id]] <- readRDS(untargeted_lima_output)
}
####
gfcv_exp <- Reduce(combineRows, gfcv_exp)
assay(gfcv_exp) <- as.data.frame(assay(gfcv_exp))


library(MetaboAnalystR)

results_output <- paste0(params$output_dir, "Mummichog_results/")

if(!dir.exists(results_output)){dir.create(results_output)}

mummichog_input <- as.data.frame(rowData(gfcv_exp))[,c("mzmed", "rtmed", 
                                                    "GF_CV.p.value", 
                                                    "GF_CV.p.value")]
mummichog_input$mode <- tolower(gsub("^.*_", "", gsub("\\..*$", "", 
                                                rownames(mummichog_input))))

colnames(mummichog_input) <- c("mz", "rt", "t.score", "p.value", "mode")

mummichog_input$p.value <- p.adjust(mummichog_input$p.value, "fdr")

if(!dir.exists(results_output)){dir.create(results_output)}
old_dir <- getwd()
setwd(results_output)
write.table(mummichog_input, row.names = FALSE, 
            file = "./mummichog_dt.txt", sep = ",")

mSet <- InitDataObjects("mass_all", "mummichog", FALSE)
mSet <- UpdateInstrumentParameters(mSet, 10.0, "mixed", "yes", 0.05)
mSet <- Read.PeakListData(mSet, "mummichog_dt.txt")
mSet <- SetRTincluded(mSet, "seconds")
mSet <- SanityCheckMummichogData(mSet)
mSet <- SetPeakEnrichMethod(mSet, "mum", "v2")
mSet <- SetMummichogPval(mSet, cutoff = 0.05)
mSet <- PerformPSEA(mSet, "mmu_kegg", "current", 3 , 100)

mSet<-PlotPeaks2Paths(mSet, "peaks_to_paths_0_", "png", 72, width=NA)
saveRDS(mSet, file = "./metaboanalyst_obj.rds")
rm(mSet)

test <- readLines("https://rest.kegg.jp/list/compound")
test <- strsplit(test, "\t")
test <- as.data.frame(do.call(rbind, test))
    
kegg_compound <- test$V2
names(kegg_compound) <- test$V1

metaboanalyst_obj <- readRDS("./metaboanalyst_obj.rds")
setwd(old_dir)

# cp_list <- sapply(rowData(lima_exp)$mzmed, function(mz){
#     found <- sapply(metaboanalyst_obj$ec_exp_dict, function(cp_mzs){
#         any(sapply(cp_mzs, function(mz_c){
#             isTRUE(all.equal(mz_c, mz))
#             
#         }))
#     })
#     names(metaboanalyst_obj$ec_exp_dict)[found]
# })

cp_list <- metaboanalyst_obj$mz2cpd_dict[as.character(rowData(gfcv_exp)$mzmed)]
    
name_list <- sapply(cp_list, function(x){
    found <- kegg_compound[x]
    found <- found[!is.na(found)]
    if(length(found)){
        return(paste0(found, collapse = ";"))    
    } else{
        return(NA)
    }
    
})

rowData(gfcv_exp)$metabo_analyst_cp <- sapply(cp_list, function(x){
    if(length(x)){
        return(paste0(x, collapse = ";"))
    } else{
        return(NA)
    }
})
rowData(gfcv_exp)$metaboanalyst_compound_names <- name_list

library(stringr)
rowData(gfcv_exp)$compounds_merged <- rowData(gfcv_exp)$compound_names

rowData(gfcv_exp)$compounds_merged[is.na(rowData(gfcv_exp)$compounds_merged)] <- rowData(gfcv_exp)$PutativeMetabolitesKEGG[is.na(rowData(gfcv_exp)$compounds_merged)]


rowData(gfcv_exp)$compounds_merged_readable <- str_trunc(rowData(gfcv_exp)$compounds_merged, 75)
rowData(gfcv_exp)$compounds_merged_readable[!is.na(rowData(gfcv_exp)$compounds_merged_readable) & rowData(gfcv_exp)$compounds_merged_readable != ""] <- base::make.unique(rowData(gfcv_exp)$compounds_merged_readable[!is.na(rowData(gfcv_exp)$compounds_merged_readable) & rowData(gfcv_exp)$compounds_merged_readable != ""])    


rowData(gfcv_exp)$compounds_kegg_merged <- rowData(gfcv_exp)$compounds
rowData(gfcv_exp)$compounds_kegg_merged[is.na(rowData(gfcv_exp)$compounds_kegg_merged)] <- rowData(gfcv_exp)$kegg_id[is.na(rowData(gfcv_exp)$compounds_kegg_merged)]

saveRDS(gfcv_exp, paste0(params$output_dir, "Untargeted_Metabolomics_exp_gfcv.rds"))
```


```{r}
####
lima_exp <- Reduce(combineRows, lima_exp)
assay(lima_exp) <- as.data.frame(assay(lima_exp))

library(MetaboAnalystR)

results_output <- paste0(params$output_dir, "Mummichog_results/")

if(!dir.exists(results_output)){dir.create(results_output)}

mummichog_input <- as.data.frame(rowData(lima_exp))[,c("mzmed", "rtmed", 
                                                    "Group_Test.statistic", 
                                                    "Group_Test.p.value")]
mummichog_input$mode <- tolower(gsub("^.*_", "", gsub("\\..*$", "", 
                                                rownames(mummichog_input))))

colnames(mummichog_input) <- c("mz", "rt", "t.score", "p.value", "mode")

mummichog_input$p.value <- p.adjust(mummichog_input$p.value, "fdr")

if(!dir.exists(results_output)){dir.create(results_output)}
old_dir <- getwd()
setwd(results_output)
write.table(mummichog_input, row.names = FALSE, 
            file = "./mummichog_dt.txt", sep = ",")

mSet <- InitDataObjects("mass_all", "mummichog", FALSE)
mSet <- UpdateInstrumentParameters(mSet, 10.0, "mixed", "yes", 0.05)
mSet <- Read.PeakListData(mSet, "mummichog_dt.txt")
mSet <- SetRTincluded(mSet, "seconds")
mSet <- SanityCheckMummichogData(mSet)
mSet <- SetPeakEnrichMethod(mSet, "mum", "v2")
mSet <- SetMummichogPval(mSet, cutoff = 0.05)
mSet <- PerformPSEA(mSet, "mmu_kegg", "current", 3 , 100)

mSet<-PlotPeaks2Paths(mSet, "peaks_to_paths_0_", "png", 72, width=NA)
saveRDS(mSet, file = "./metaboanalyst_obj.rds")
rm(mSet)

test <- readLines("https://rest.kegg.jp/list/compound")
test <- strsplit(test, "\t")
test <- as.data.frame(do.call(rbind, test))
    
kegg_compound <- test$V2
names(kegg_compound) <- test$V1

metaboanalyst_obj <- readRDS("./metaboanalyst_obj.rds")
setwd(old_dir)

# cp_list <- sapply(rowData(lima_exp)$mzmed, function(mz){
#     found <- sapply(metaboanalyst_obj$ec_exp_dict, function(cp_mzs){
#         any(sapply(cp_mzs, function(mz_c){
#             isTRUE(all.equal(mz_c, mz))
#             
#         }))
#     })
#     names(metaboanalyst_obj$ec_exp_dict)[found]
# })

cp_list <- metaboanalyst_obj$mz2cpd_dict[as.character(rowData(lima_exp)$mzmed)]
    
name_list <- sapply(cp_list, function(x){
    found <- kegg_compound[x]
    found <- found[!is.na(found)]
    if(length(found)){
        return(paste0(found, collapse = ";"))    
    } else{
        return(NA)
    }
    
})

rowData(lima_exp)$metabo_analyst_cp <- sapply(cp_list, function(x){
    if(length(x)){
        return(paste0(x, collapse = ";"))
    } else{
        return(NA)
    }
})
rowData(lima_exp)$metaboanalyst_compound_names <- name_list

# lima_rd <- as.data.frame(rowData(lima_exp))

# compound_ids <- unique(lima_rd$compounds[!is.na(lima_rd$compounds)])
# keep_ids <- sapply(compound_ids, function(x){
#     compound_list <- lima_rd[lima_rd$compounds == x,]
#     if(nrow(compound_list) == 1){
#         return(rownames(compound_list))
#     } else{
#         rownames(compound_list)[which.max(compound_list$Group_Test.statistic)]
#     }
# })
# 
# compound_ids2 <- unique(lima_rd$PutativeMetabolites[!is.na(lima_rd$PutativeMetabolites)])
# keep_ids2 <- sapply(compound_ids2, function(x){
#     compound_list <- lima_rd[lima_rd$PutativeMetabolites == x,]
#     if(nrow(compound_list) == 1){
#         return(rownames(compound_list))
#     } else{
#         rownames(compound_list)[which.max(compound_list$Group_Test.statistic)]
#     }
# })
# 
# lima_exp <- lima_exp[union(keep_ids, keep_ids2)]
library(stringr)
rowData(lima_exp)$compounds_merged <- rowData(lima_exp)$compound_names

rowData(lima_exp)$compounds_merged[is.na(rowData(lima_exp)$compounds_merged)] <- rowData(lima_exp)$PutativeMetabolitesKEGG[is.na(rowData(lima_exp)$compounds_merged)]


rowData(lima_exp)$compounds_merged_readable <- str_trunc(rowData(lima_exp)$compounds_merged, 75)
rowData(lima_exp)$compounds_merged_readable[!is.na(rowData(lima_exp)$compounds_merged_readable) & rowData(lima_exp)$compounds_merged_readable != ""] <- base::make.unique(rowData(lima_exp)$compounds_merged_readable[!is.na(rowData(lima_exp)$compounds_merged_readable) & rowData(lima_exp)$compounds_merged_readable != ""])    


rowData(lima_exp)$compounds_kegg_merged <- rowData(lima_exp)$compounds
rowData(lima_exp)$compounds_kegg_merged[is.na(rowData(lima_exp)$compounds_kegg_merged)] <- rowData(lima_exp)$kegg_id[is.na(rowData(lima_exp)$compounds_kegg_merged)]


#####

saveRDS(lima_exp, paste0(params$output_dir, "Untargeted_Metabolomics_exp_lima.rds"))

# rmarkdown::render(input = "./Hermes_Analysis.Rmd",
#                   output_file = paste0(hp_output_path, "Hermes_Report.html"), 
#                   clean = TRUE, params = list(
#     ms1_dir = paste0(params$input_dir, "Hilic_Positive/Hermes_Files/"), 
#     qc_names =  "QC", blank_names = "Blank",
#     met_db = db_path, met_db_sep = ",",
#     ppm_error = 10, instrument = "QTOF", resolution = 30000, 
#     noise_int = 1000, ionization = "+", labelled = FALSE,
#     ad_list = c("M+H", "M+NH4", "M+Na", "M+K", "M+"), 
#     min_max_mz = c(50, 1500), 
#     add_charge = 1, add_mult = 1,
#     soi_detection_type = "double",
#     output_dir = hp_output_path,
#     consensus = TRUE, soi_consensus = 1:3))
# 
# 
# hn_output_path <- paste0(hermes_results_path, "Hilic_Negative/")
# if(!dir.exists(hn_output_path)){dir.create(hn_output_path)}
# 
# rmarkdown::render(input = "./Hermes_Analysis.Rmd",
#                   output_file = paste0(hn_output_path, "Hermes_Report.html"), 
#                   clean = TRUE, params = list(
#     ms1_dir = paste0(params$input_dir, "Hilic_Negative/Hermes_Files/"), 
#     qc_names =  "QC", blank_names = "Blank", 
#     met_db = db_path, met_db_sep = ",",
#     ppm_error = 10, instrument = "QTOF", resolution = 30000, 
#     noise_int = 1000, ionization = "-", labelled = FALSE,
#     ad_list = c("M-H", "M+Cl"), 
#     min_max_mz = c(50, 1500), 
#     add_charge = 1, add_mult = 1,
#     soi_detection_type = "double", soi_filter_ids = 1:3,
#     output_dir = hn_output_path,
#     consensus = TRUE, soi_consensus = 1:3))
# 
# rp_output_path <- paste0(hermes_results_path, "RP_Positive/")
# if(!dir.exists(rp_output_path)){dir.create(rp_output_path)}
# 
# rmarkdown::render(input = "./Hermes_Analysis.Rmd",
#                   output_file = paste0(rp_output_path, "Hermes_Report.html"), 
#                   clean = TRUE, params = list(
#     ms1_dir = paste0(params$input_dir, "RP_Positive/Hermes_Files/"), 
#     qc_names =  "QC", blank_names = "Blank",
#     met_db = db_path, met_db_sep = ",",
#     ppm_error = 10, instrument = "QTOF", resolution = 30000, 
#     noise_int = 1000, ionization = "+", labelled = FALSE,
#     ad_list = c("M+H", "M+NH4", "M+Na", "M+K", "M+"), 
#     min_max_mz = c(50, 1500), 
#     add_charge = 1, add_mult = 1,
#     soi_detection_type = "double", soi_filter_ids = 1:3,
#     output_dir = rp_output_path,
#     consensus = TRUE, soi_consensus = 1:3))

```

```{r}
# rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
#                   output_file = "./Hermes_Results/Hilic_Positive/xcms_hermes_results.html", clean = TRUE, 
#                   params = list(metadata_file = "./Hilic_Positive/LC_M S_metadata.csv",
#     xcms_hermes_file = "./Hermes_Results/Hilic_Positive/summarized_hermes_xcms.rds",
#     hermes_file = "./Hermes_Results/Hilic_Positive/filteredSoiLists.rds",
#     qc_name = "HP_QC",
#     blank_name = "HP_Blank",
#     output_results = "./Hermes_Results/Hilic_Positive/",
#     data_type = "Hilic Positive"))
# 
# rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
#                   output_file = "./Hermes_Results/Hilic_Negative/xcms_hermes_results.html", clean = TRUE, 
#                   params = list(metadata_file = "./Hilic_Negative/LC_MS_metadata.csv",
#     xcms_hermes_file = "./Hermes_Results/Hilic_Negative/summarized_hermes_xcms.rds",
#     hermes_file = "./Hermes_Results/Hilic_Negative/filteredSoiLists.rds", 
#     qc_name = "HN_QC",
#     blank_name = "HN_Blank",
#     output_results = "./Hermes_Results/Hilic_Negative/",
#     data_type = "Hilic Negative"))
# 
# rmarkdown::render(input = "./XCMS_HERMES_Post_Processing.Rmd", 
#                   output_file = "./Hermes_Results/RP_Positive/xcms_hermes_results.html", 
#                   clean = TRUE, 
#                   params = list(metadata_file = "./RP_Positive/LC_MS_metadata.csv",
#     hermes_file = "./Hermes_Results/RP_Positive/filteredSoiLists.rds",
#     xcms_hermes_file = "./Hermes_Results/RP_Positive/summarized_hermes_xcms.rds",
#     qc_name = "RP_QC",
#     blank_name = "RP_Blank",
#     output_results = "./Hermes_Results/RP_Positive/",
#     data_type = "RP Positive"))
```


## Tests Hermes

```{r}
library(SummarizedExperiment)
db_path <- paste0(params$input_dir, "FullHMDB_Chebi_Tripeptides_db.csv")

column_ids <- c("Hilic_Positive", "Hilic_Negative", "RP_Positive")
positive_adducts <- c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", "[M+]+")
negative_adducts <- c("[M-H]-", "[M+Cl]-")

gfcv_exp <- list()
lima_exp <- list()

for(id in column_ids){
       
    file_dir <- paste0(params$input_dir, id, "/")
    hermes_files <- paste0(file_dir, "Hermes_Test/")
    output_path <- hermes_files
    if(!dir.exists(output_path)){dir.create(output_path)}
    hermes_output_path <- paste0(output_path, "filteredSoiLists.rds") 
    ## HERMES Analysis
    
    if(!file.exists(hermes_output_path)){
        param_list <- list(ms1_dir = hermes_files, 
                            qc_names =  "QC", blank_names = "Blank",
                            met_db = db_path, met_db_sep = ",",
                            ppm_error = 10, instrument = "QTOF", resolution = 30000, 
                            noise_int = 1000, labelled = FALSE,
                            min_max_mz = c(50, 1500), 
                            add_charge = 1, add_mult = 1,
                            soi_detection_type = "double",
                            output_dir = output_path,
                            consensus = TRUE, 
                            soi_consensus = 1:3)
        param_list$ionization <- ifelse(grepl("Positive", x = id, 
                                                ignore.case = TRUE), 
                                        "+", "-")
        if(grepl("Positive", id)){
            param_list$ad_list <- positive_adducts    
        } else{
            param_list$ad_list <- negative_adducts
        }
        
        rmarkdown::render(input = "./Hermes_Analysis.Rmd",
                      output_file = paste0(output_path, "Hermes_Report_Test.html"), 
                      clean = TRUE, params = param_list)

        }
}
```

