---
title: "Untargeted Metabolomics Analysis"
author: "Jordi Rofes Herrera"
date: "27/1/2022"
output: html_document
params:
    file_dir: "../../inputs/Untargeted_Metabolomics/Hilic_Negative/"
    metadata_file: "../../inputs/Untargeted_Metabolomics/Hilic_Negative/LC_MS_metadata.csv"
    output_dir: "../../outputs/Untargeted_Metabolomics/Hermes_Results/Hilic_Negative/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required Packages

```{r}
library(xcms)
library(MSnbase)
library(BiocParallel)
library(ggplot2)
library(plotly)
```

```{r}
library(readxl)
gf_lima_meta <- read.csv(params$metadata_file)
```


## Data loading

```{r}
quant_files <- list.files(path = params$file_dir, full.names = TRUE)
file_names <- quant_files[sub(pattern = "\\.[mM][zZ][xX]?[mM][lL]$", replacement = "", 
                              x = basename(quant_files)) %in% gf_lima_meta$injection_order]
findOrder <- function(files, phenodata, pheno_var){
    samp <- sub(pattern = "\\.[mM][zZ][xX]?[mM][lL]$", replacement = "",
                x =  basename(files))
    if(length(pheno_var) == 1){
        if(pheno_var == "rownames"){
            ordering <- rownames(phenodata)
        } else{
            ordering <- phenodata[[pheno_var]]
        }
    } else{
        ordering <- pheno_var
    }
    if(!all(ordering %in% samp)){
        stop("Filenames do not agree with the phenodata variable. Change the names accordingly")
    }
    return(order(sapply(samp, function(x){which(ordering == x)})))
}
file_order <- findOrder(file_names, phenodata = gf_lima_meta, pheno_var = "injection_order")
quant_files <- file_names[file_order]
```


```{r}
ms_data <- readMSData(files = quant_files, pdata = AnnotatedDataFrame(data = gf_lima_meta), centroided. = TRUE, mode = "onDisk")
ms_data <- filterEmptySpectra(ms_data)
```

```{r}
register(SnowParam())
ms_data <- findChromPeaks(ms_data, param = CentWaveParam(ppm = 10, peakwidth = c(5, 50)))

# group_colors <- brewer.pal(length(table(pData(ms_data)$group)), "Set3")
# names(group_colors) <- names(table(pData(ms_data)$group))
# tc <- spectra(ms_data)
# tic_dt <- sapply(tc, tic)
# 
# tic_dt <- split(x = tic_dt, f = fromFile(ms_data))
# 
# boxplot(tic_dt, col = group_colors[pData(ms_data)$group],
#         ylab = "intensity", main = "Total ion current")

saveRDS(ms_data, paste0(params$output_dir,"xcmsnexp_chrom_peaks.rds"))
```

```{r}
## Bin the BPC
# bpis <- chromatogram(ms_data , aggregationFun = "max")
# 
# bpis_bin <- bin(bpis, binSize = 2)
# 
# ## Calculate correlation on the log2 transformed base peak intensities
# cormat <- cor(log2(do.call(cbind, lapply(bpis_bin, intensity))))
# colnames(cormat) <- rownames(cormat) <- bpis_bin$sample_name
# 
# ## Define which phenodata columns should be highlighted in the plot
# ann <- data.frame(group = bpis_bin$group)
# rownames(ann) <- bpis_bin$sample_name
# 
# ## Perform the cluster analysis
# pheatmap(cormat, annotation = ann,
#          annotation_color = list(group = group_colors))
```


```{r}
ms_data <- readRDS(paste0(params$output_dir,"xcmsnexp_chrom_peaks.rds"))

ms_data <- refineChromPeaks(ms_data, param = MergeNeighboringPeaksParam())
# saveRDS(ms_data, paste0(params$output_dir,"xcmsnexp_chrom_peaks_merged.rds"))
```

```{r}
#ms_data <- readRDS(paste0(params$output_dir,"xcmsnexp_chrom_peaks_merged.rds"))
ms_data <- adjustRtime(ms_data, param = ObiwarpParam())
plotAdjustedRtime(filterFile(ms_data, 3:10), peakGroupsPch = 1,
                  peakGroupsCol = "#00ce0040")


# saveRDS(ms_data, paste0(params$output_dir,"xcmsnexp_chrom_rt_corrected.rds"))
```

```{r}
# ms_data <- readRDS(paste0(params$output_dir,"xcmsnexp_chrom_rt_corrected.rds"))

pdp <- PeakDensityParam(sampleGroups = gf_lima_meta$groups_m,
                        minFraction = 0.4, bw = 5, binSize = 0.01)
ms_data <- groupChromPeaks(ms_data, param = pdp)
ms_data <- fillChromPeaks(ms_data, param = FillChromPeaksParam())
saveRDS(ms_data, file = paste0(params$output_dir, "xcmsnexp_filled.rds"))
saveRDS(quantify(ms_data, value = "into"), file =  paste0(params$output_dir, "summarized.rds"))
# write.csv(assay(xcms_dt), paste0(params$output_dir,"xcms_quant_matrix.csv"))
# xcms_dt <- readRDS("./Hermes_Results/Hilic_Positive/xcmsnexp_filled.rds")
```

```{r}
library(qHermes)
library(xcms)
ms_data <- readRDS(paste0(params$output_dir, "xcmsnexp_filled.rds"))
hermes_dt <- readRDS(paste0(params$output_dir,"filteredSoiLists.rds"))
ms_data <- qHermes::annotateFeaturesFromList(XCMSnExp = ms_data, RHermesExp = hermes_dt, 
                                             SOI_id = 4, filter = FALSE)
xcms_dt <- quantify(ms_data, value = "into")
saveRDS(xcms_dt, file =  paste0(params$output_dir, "summarized_hermes_xcms.rds"))
```
