---
title: "Limma post XCMS/HERMES processing"
author: "Jordi Rofes Herrera"
date: "27/3/2022"
output: html_document
params:
    metadata_file: "../../inputs/Untargeted_Metabolomics/Hilic_Positive/LC_MS_metadata.csv"
    xcms_hermes_file: "../../outputs/Untargeted_Metabolomics/Hermes_Results/Hilic_Positive/summarized_hermes_xcms.rds"
    hermes_file: "../../outputs/Untargeted_Metabolomics/Hermes_Results/Hilic_Positive/filteredSoiLists.rds"
    hermes_filter: TRUE
    qc_name: "HP_QC"
    blank_name: "HP_Blank"
    output_results: "../../outputs/Untargeted_Metabolomics/Hermes_Results/Hilic_Positive/"
    data_type: "Hilic_Positive"
    mummichog_ionization: "positive"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## XCMS Post-procesing analysis

```{r}
# readRDS("./Hermes_Results/Hilic_Positive/summarized.rds")
xcms_dt <- readRDS(params$xcms_hermes_file)
```


```{r}
library(SummarizedExperiment)
library(ggplot2)
library(plotly)
library(mixOmics)
library(vsn)
library(dplyr)
library(stringr)
library(igraph)
library(DESeq2)
pca_plot <- function(pca_data, pc_x, pc_y, group_var, ellipse_var, allElipse =TRUE, interactive = TRUE, level = 0.95){
    pc_var <- pca_data$sdev^2
    pc_var_abs <- pc_var/sum(pc_var)*100
    pc_plot <- ggplot() + geom_point(aes(x = pca_data$x[,pc_x], y = pca_data$x[,pc_y], colour = group_var)) + 
        theme_classic() + xlab(paste0("PC", pc_x, " (", round(pc_var_abs[pc_x]), "%)")) +
        ylab(paste0("PC", pc_y, " (",round(pc_var_abs[pc_y]), "%)")) +
        theme(axis.line = element_line(colour = "black", size = 0.5,
                                        linetype = "solid"),
                                        legend.title = element_blank(),
                                        plot.margin = unit(c(0.5,0.5,0.5,0.5),"cm"),
            plot.title = element_text(hjust = 0.5),
            axis.text.x = element_text(vjust = 0.5, hjust = 1)) + geom_hline(yintercept = 0) + 
        geom_vline(xintercept = 0)
    if(allElipse){
        pc_plot <- pc_plot + stat_ellipse(aes(x = pca_data$x[,pc_x], y = pca_data$x[,pc_y]),
                            colour = "grey7", type = "t", linetype = 1,
                            level = level)
    }
        
    
    if(!missing(ellipse_var)){
        pc_plot <- pc_plot + stat_ellipse(aes(x = pca_data$x[,pc_x], y = pca_data$x[,pc_y], color = ellipse_var),
                            type = "t", linetype = 1,
                            level = level)
    }
        
    
    if(interactive){
        pc_plot <- ggplotly(pc_plot)
    }
    return(pc_plot)
}
var_plot <- function(pca_data){
    pc_var <- pca_data$sdev^2
    var_vec_1 <- cumsum(pc_var)/sum(pc_var)*100
    variance_plot <- qplot(y = var_vec_1) + theme_minimal() + 
        xlab("Number of components") + ylab("Cummulative variance (%)") + 
        ggtitle("Scree Plot") + theme(plot.title = element_text(hjust = 0.5))
    return(variance_plot)
}
```

### Data loading

```{r}
#xcms_dt <- readRDS(paste0(params$output_dir, "/xcms_quant_matrix.rds"))
gf_lima_meta <- read.csv(params$metadata_file)
```

#### PMP filter

```{r}
xcms_p <- pmp::filter_peaks_by_fraction(xcms_dt, min_frac = 0.8, classes = gf_lima_meta$groups_m, 
                                        qc_label = params$qc_name, method = "across")
xcms_p <- pmp::filter_peaks_by_fraction(xcms_p, min_frac = 0.3, classes = gf_lima_meta$groups_m, 
                                        qc_label = params$qc_name, method = "QC")
xcms_p <- pmp::filter_peaks_by_blank(xcms_p, fold_change = 1, classes = gf_lima_meta$groups_m, 
                                     blank_label = params$blank_name, qc_label = params$qc_name,
                                     fraction_in_blank = 0, remove_samples = TRUE, remove_peaks = TRUE)

xcms_p <- pmp::filter_peaks_by_rsd(xcms_p, max_rsd = 35, 
                                    classes = gf_lima_meta$groups_m[gf_lima_meta$groups_m != params$blank_name], 
                                    qc_label = params$qc_name, remove_peaks = TRUE)
dt_pca <- pmp::mv_imputation(xcms_p, method = "knn", k = 10)

pca_dt <- prcomp(t(assay(dt_pca)), center = TRUE, scale. = TRUE)
pca_plot(pca_dt, 1, 2, group_var = gf_lima_meta$groups_m[gf_lima_meta$groups_m != params$blank_name],
         level = 0.95, allElipse = FALSE)
```

#### QCRSC batch correction

```{r}
xcms_p_dc <- pmp::QCRSC(df = xcms_p, order = c(1:92), batch = rep(1, 92), spar = 0, 
                        qc_label = params$qc_name, classes = gf_lima_meta$groups_m[gf_lima_meta$groups_m != params$blank_name], )


dt_pca <- pmp::mv_imputation(xcms_p_dc, method = "knn", k = 10)

gf_lima_meta_nb <- gf_lima_meta[gf_lima_meta$groups_m != params$blank_name,]

pca_dt <- prcomp(t(assay(dt_pca)), center = TRUE, scale. = TRUE)
pca_plot(pca_dt, 1, 2, group_var = gf_lima_meta_nb$groups_m,
         level = 0.95, allElipse = FALSE)
```

### GFCV model analysis

#### Batch effect exploration

```{r}
library(sva)
library(DESeq2)
xcms_p_dc_filt <- xcms_p_dc[,(gf_lima_meta_nb$gfcv != "") & (gf_lima_meta_nb$groups_m != params$qc_name)]
pca_gr_dt <- gf_lima_meta[(gf_lima_meta$groups_m != params$blank_name) & (gf_lima_meta$gfcv != "") & 
                                                             (gf_lima_meta$groups_m != params$qc_name),]

# write.csv(pca_gr_dt, file = paste0(params$output_results, "filtered_metadata.csv"), row.names = FALSE)

dt_pca <- assay(pmp::mv_imputation(xcms_p_dc_filt, method = "knn", k = 10))
mode(dt_pca) <- "integer"
dt_pca <- pmp::mv_imputation(dt_pca, method = "knn", k = 10)

dt_pca <- DESeq2::DESeqDataSetFromMatrix(round(dt_pca), colData = pca_gr_dt, design = ~ batch + sex_m + gfcv)

dt_pca <- estimateSizeFactors(dt_pca)
dt_pca <- estimateDispersions(dt_pca)
plotDispEsts(dt_pca)
dt_pca <- varianceStabilizingTransformation(dt_pca, blind=FALSE)

pca_dt <- prcomp(t(assay(dt_pca)), center = TRUE, scale. = TRUE)
pca_plot(pca_dt, 1, 2, group_var = as.factor(pca_gr_dt$batch), level = 0.95, allElipse = FALSE)
```

#### Batch correction

```{r}
dt_pca <- assay(pmp::mv_imputation(xcms_p_dc_filt, method = "knn"))

mode(dt_pca) <- "integer"
dt_pca <- pmp::mv_imputation(dt_pca, method = "knn", k = 10)
dt_pca <- DESeq2::DESeqDataSetFromMatrix(round(dt_pca), colData = pca_gr_dt, design = ~ batch + sex_m + gfcv)

dt_pca <- estimateSizeFactors(dt_pca)
dt_pca <- estimateDispersions(dt_pca)
plotDispEsts(dt_pca)
dt_pca <- varianceStabilizingTransformation(dt_pca, blind=FALSE)

dt_pca <- ComBat(dat = assay(dt_pca), batch = pca_gr_dt$batch)

pca_dt <- prcomp(t(dt_pca), center = TRUE, scale. = TRUE)

pca_plot(pca_dt, 1, 2, group_var = pca_gr_dt$batch, level = 0.95, allElipse = FALSE, ellipse_var = pca_gr_dt$groups_m)
pca_plot(pca_dt, 1, 2, group_var = pca_gr_dt$groups_m, ellipse_var = pca_gr_dt$groups_m, allElipse = FALSE)
```

```{r}
pcvar <- round(pca_dt$sdev^2/sum(pca_dt$sdev^2)*100, 2)

d3plot <- plot_ly(x = pca_dt$x[,1], y = pca_dt$x[,2], z = pca_dt$x[,3], color = pca_gr_dt$groups_m)
d3plot <- d3plot %>% add_markers()
d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
                     yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
                     zaxis = list(title = paste0('PC3', "(", pcvar[3], "%)"))))
d3plot
```

```{r}
pcvar <- round(pca_dt$sdev^2/sum(pca_dt$sdev^2)*100, 2)

d3plot <- plot_ly(x = pca_dt$x[,1], y = pca_dt$x[,2], z = pca_dt$x[,4], color = pca_gr_dt$groups_m)
d3plot <- d3plot %>% add_markers()
d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
                     yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
                     zaxis = list(title = paste0('PC4', "(", pcvar[4], "%)"))))
d3plot
```

#### Anova analisis

```{r}
library(limma)
xcms_p_dc_filt$group <- factor(xcms_p_dc_filt$groups_m, 
                                levels = c("CVM", "CVF", "GFM", "GFF"))
xcms_p_dc_filt$sex <- factor(xcms_p_dc_filt$sex_m, levels = c("M", "F"))
xcms_p_dc_filt$gfcv <- factor(xcms_p_dc_filt$gfcv, levels = c("C", "G"))

tukey_results <- apply(assay(xcms_p_dc_filt), 1, function(dt_var){
    anova_results <- aov(log(dt_var) ~ batch + sex + gfcv + sex:gfcv, 
                        data = colData(xcms_p_dc_filt))
    anova_results_no_int <- aov(log(dt_var) ~ batch + sex + gfcv, 
                                data = colData(xcms_p_dc_filt))
    print(anova_results)
    list("Interaction Term" = as.data.frame(summary(anova_results)[[1]][4,]),
         "GF_CV_Full" = as.data.frame(summary(anova_results_no_int)[[1]][3,]),
         "Pairwise-Tests" = TukeyHSD(anova_results, which = c("sex:gfcv")))
})

gf_cv_results <- do.call(rbind, lapply(tukey_results, function(x){x[[2]]}))
names(gf_cv_results)[names(gf_cv_results) == "Pr(>F)"] <- "pvalue"
gf_cv_results$adj.p.value <- p.adjust(gf_cv_results$pvalue, method = "fdr")


interaction_results <- do.call(rbind, lapply(tukey_results, function(x){x[[1]]}))
names(interaction_results)[names(interaction_results) == "Pr(>F)"] <- "pvalue"
interaction_results$adj.p.value <- p.adjust(interaction_results$pvalue, method = "fdr")

contrasts_results <- lapply(tukey_results, function(x){x[[3]]})
contrasts_results <- lapply(seq_len(nrow(contrasts_results[[1]][[1]])), function(ctrs_row){
    ctrs_result_list <- lapply(contrasts_results, function(ctrs){
        if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
        ctrs[[1]][ctrs_row,]   
    })
    do.call(rbind, ctrs_result_list)
})
names(contrasts_results) <- c("CVF_CVM", "GFM_CVM", "GFF_CVM", 
                              "GFM_CVF", "GFF_CVF", "GFF_GFM")

contrasts_results <- lapply(contrasts_results, function(ctrs){
    ctrs <- as.data.frame(ctrs)
    colnames(ctrs) <- c("difference", "lower", "upper", "pvalue")
    ctrs$adj.p.value <- p.adjust(ctrs[,"pvalue"], method = "fdr")
    ctrs
})

feature_data <- as.data.frame(rowData(xcms_p_dc_filt))
```

```{r, eval=params$hermes_filter}
hermes_dt <- readRDS(params$hermes_file)
hermes_ions <- hermes_dt@metadata@ExpParam@ionF[[2]]

hermes_dt@metadata@ExpParam@DB$Name <- gsub(";", "-", 
                                            hermes_dt@metadata@ExpParam@DB$Name)

feature_data$soi <- sapply(feature_data$soi, function(x){
    if(all(is.na(x))){return(NA)}
    paste(x, collapse = ",")})
feature_data$formula <- sapply(feature_data$formula, function(x){
    if(all(is.na(x))){return(NA)}
    paste(x, collapse = " / ")})

feature_data$neutral_formula <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
    
    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    if(length(found_formulas) == 0){return(NA)}
    paste0(found_formulas, collapse = " / ")
})

feature_data$adduct_annotation <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
    
    found_an <- hermes_ions$an[match(form, hermes_ions$ion)]
    if(length(found_an) == 0){return(NA)}
    paste0(found_an, collapse = " / ")
})
    
feature_data$PutativeMetabolites <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        paste(found_mets, collapse = ";")
    })
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$PutativeMetabolitesKEGG <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
        
    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id & !is.na(hermes_dt@metadata@ExpParam@DB$Kegg) & hermes_dt@metadata@ExpParam@DB$Kegg != ""]
        if(length(found_mets)){
            paste(found_mets, collapse = ";")    
        } else{
            return(NA)
        }
    })
    
    # found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula %in% found_formulas & !is.na(hermes_dt@metadata@ExpParam@DB$Kegg) & hermes_dt@metadata@ExpParam@DB$Kegg != ""]
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$kegg_id <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Kegg[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        found_mets[is.na(found_mets) | found_mets == ""] <- NA
        if(length(found_mets)){
            paste(found_mets, collapse = ";")
        } else{
            return(NA)
        }
    })
    
    # found_mets <- hermes_dt@metadata@ExpParam@DB$Kegg[hermes_dt@metadata@ExpParam@DB$MolecularFormula %in% found_formulas]
    # found_mets <- found_mets[!is.na(found_mets) & found_mets != ""]
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$hmdb_id <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$HMDB_ID[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        found_mets[is.na(found_mets) | found_mets == ""] <- NA
        if(length(found_mets)){
            paste(found_mets, collapse = ";")
        } else{
            return(NA)
        }
    })
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)


feature_data$iso_num <- sapply(seq_len(nrow(feature_data)), function(row_id){
    if(!is.na(feature_data[row_id,]$SOIData)){
        return(paste(feature_data[row_id,]$SOIData[[1]]$isofound, collapse = " / "))
    } else{
        return(NA)
    }
    
}, USE.NAMES = FALSE)

feature_data$iso_fidelity <- sapply(seq_len(nrow(feature_data)), function(row_id){
    if(!is.na(feature_data[row_id,]$SOIData)){
        return(paste(round(feature_data[row_id,]$SOIData[[1]]$isofidelity, 3), collapse = " / "))
    } else{
        return(NA)
    }
    
}, USE.NAMES = FALSE)
```


```{r}
contrasts_results <-  c(list("GFCV_sex_Interaction" = interaction_results, 
                            "GF_CV" = gf_cv_results), contrasts_results)

contrasts_results <- do.call(cbind, contrasts_results)

colnames(contrasts_results) <- gsub("pvalue", "p.value", colnames(contrasts_results))

feature_data <- cbind(feature_data, contrasts_results)

rownames(xcms_p_dc_filt) <- paste0(params$data_type, ".", 
                                   rownames(xcms_p_dc_filt))

assay(xcms_p_dc_filt) <- as.data.frame(assay(xcms_p_dc_filt))

xcms_p_dc_filt$samplename <- make.names(xcms_p_dc_filt$samplename)
colnames(xcms_p_dc_filt) <- xcms_p_dc_filt$samplename

rowData(xcms_p_dc_filt) <- feature_data
```


```{r}
mummichog_test <- as.data.frame(rowData(xcms_p_dc_filt)[c("mzmed", "rtmed",
                                            "GF_CV.p.value",
                                            "GF_CV.adj.p.value")])
colnames(mummichog_test) <- c("mz", "rtime", "p-value", "t-score")

mummichog_test$custom_id <- rownames(mummichog_test)

mummichog_path <- "../../outputs/Untargeted_Metabolomics/Mummichog_results/"
if(!dir.exists(mummichog_path)){dir.create(mummichog_path)}

write.table(x = mummichog_test,
            file = paste0(mummichog_path, "mummichog_file.txt"),
            sep = "\t", row.names = FALSE, quote = FALSE)

reticulate::py_config()
system(command = paste0("mummichog -f ..\\..\\outputs\\Untargeted_Metabolomics\\Mummichog_results\\mummichog_file.txt -o myResults_Test_Full -m ", params$mummichog_ionization), wait = T)

mummichog_folder <- grep("myResults",
                         list.dirs(path = ".", full.names = T,
                                    recursive = F), value = T)
new_folder <- paste0(params$output_results, mummichog_folder)

if(!dir.exists(new_folder)) dir.create(new_folder)
file.copy(from = mummichog_folder, to = params$output_results, recursive = T)
unlink(mummichog_folder, recursive = T)
```

#### mummichog

```{r}
emp_compounds <- readLines(paste0(new_folder, "/tables/ListOfEmpiricalCompounds.tsv"))
emp_compounds <- strsplit(emp_compounds, split = "\t")
emp_compounds <- lapply(emp_compounds, function(x){
    data.table::data.table(t(x))
})
emp_compounds <- as.data.frame(data.table::rbindlist(emp_compounds, fill = TRUE))
colnames(emp_compounds) <- emp_compounds[1,]
emp_compounds <- as.data.frame(emp_compounds[-1,])

emp_compounds2 <- readLines(paste0(new_folder, "/tables/userInput_to_EmpiricalCompounds.tsv"))
emp_compounds2 <- strsplit(emp_compounds2, split = "\t")
emp_compounds2 <- do.call(rbind, emp_compounds2)
colnames(emp_compounds2) <- emp_compounds2[1,]
emp_compounds2 <- as.data.frame(emp_compounds2[-1,])

adduct_h <- ifelse(params$mummichog_ionization == "positive", "M+H[1+]", "M-H[-]")

keep_rows_test <- c()
for(id in seq_len(nrow(emp_compounds))){
    ec_dt <- emp_compounds[id, ]
    ion_list <- strsplit(ec_dt$str_row_ion, ";")[[1]]
    row_list <- strsplit(ec_dt$massfeature_rows, ";")[[1]]
    if(length(ion_list) > 1){
        
        if(any(grepl(adduct_h, ion_list))){
            keep_rows_test <- c(keep_rows_test, row_list[m_h])
        }
        
        emp_cp_info <- emp_compounds2[(emp_compounds2$input_row %in% row_list) & 
                                    !(emp_compounds2$input_row %in% keep_rows_test),]
        keep_rows_test <- c(keep_rows_test, emp_cp_info$input_row[which.max(emp_cp_info$statistic)])
            
    } else{
        keep_rows_test <- c(keep_rows_test, row_list)
    }
}

pathway_enrich <- readLines(paste0(new_folder, "/tables/mcg_pathwayanalysis_myResults_Test_Full.tsv"))
pathway_enrich <- strsplit(pathway_enrich, split = "\t")
pathway_enrich <- do.call(rbind, pathway_enrich)
colnames(pathway_enrich) <- pathway_enrich[1,]
pathway_enrich <- as.data.frame(pathway_enrich[-1,])

pathway_list <- strsplit(pathway_enrich$`overlap_EmpiricalCompounds (id)`, split = ";")
names(pathway_list) <- pathway_enrich$pathway

emp_compounds2$pathways_tested <- sapply(emp_compounds2$EID, function(x){
    found <- names(pathway_list)[sapply(pathway_list, function(y){any(y %in% x)})]
    if(length(found)){
        return(paste(found, collapse = " / "))
    } else{
        return(NA)
    }
})

merged_res <- lapply(rownames(rowData(xcms_p_dc_filt)), function(x){
    found <- emp_compounds2[emp_compounds2$CompoundID_from_user == x, 
                        c("input_row", "EID" , "str_row_ion", "compounds", 
                        "compound_names", "CompoundID_from_user", "pathways_tested")]
    if(nrow(found) == 0){
        return(rep(NA, 7))
    } else if(nrow(found) == 1){
        return(found)
    } else if(nrow(found) > 1){
        return(sapply(found, paste, collapse = " / "))
    }
})
merged_res <- do.call(rbind, merged_res)

rowData(xcms_p_dc_filt) <- cbind(rowData(xcms_p_dc_filt), merged_res)

rowData(xcms_p_dc_filt)$input_row <- sapply(rowData(xcms_p_dc_filt)$input_row, function(row_id){
    unique(strsplit(row_id, " / ")[[1]])
})

mz_rd <- as.data.frame(rowData(xcms_p_dc_filt))

hermes_f <- unique(unlist(strsplit(mz_rd$neutral_formula, " / ")))
hermes_f <- hermes_f[!is.na(hermes_f)]
# hermes_f <- unique(mz_rd$neutral_formula[!is.na(mz_rd$neutral_formula)])
hermes_p_ad <- ifelse(params$mummichog_ionization == "positive", 
                        "M+H", "M-H")

keep_adducts <- sapply(hermes_f, function(f_id){
    f_dt <- mz_rd[grep(f_id, mz_rd$neutral_formula),]
    
    test <- IRanges::findOverlaps(query = IRanges(start = f_dt$rtmin, 
                                          end = f_dt$rtmax), 
                                  type = "any", 
                                  drop.redundant = TRUE, 
                                  drop.self = TRUE)
    
    if(length(test) == 0){return(rownames(f_dt))} else{
        test_gr <- graph_from_data_frame(as.data.frame(test), 
                                         directed = FALSE)
        group_m <- components(test_gr)$membership
        keep_group <- sapply(unique(group_m), function(group_id){
            feature_ids <- names(group_m)[group_m == group_id]
            group_dt <- f_dt[as.numeric(feature_ids),]
            
            found_h <- grepl(hermes_p_ad, 
                            group_dt$adduct_annotation)
            if(sum(found_h) == 1){
                return(rownames(group_dt[found_h,]))
            }
            return(rownames(group_dt)[which.max(group_dt$GFCV_sex_Interaction.F.value)[1]])
        })
        return(keep_group)
    }
})

xcms_p_dc_filt <- xcms_p_dc_filt[(mz_rd$isotope == "M0" & (rownames(mz_rd) %in% unlist(keep_adducts))) | (mz_rd$input_row %in% keep_rows_test),]
```


```{r}
# saveRDS(xcms_p_dc_filt,
#         paste0(params$output_results, "xcms_hermes_exp_gfcv.rds"))
```

### LIMA model analysis

```{r}
xcms_p_dc_filt <- xcms_p_dc[,(gf_lima_meta_nb$gfcv == "") & (gf_lima_meta_nb$groups_m != params$qc_name)]
pca_gr_dt <- gf_lima_meta[(gf_lima_meta$groups_m != params$blank_name) & (gf_lima_meta$gfcv == "") & 
                                                             (gf_lima_meta$groups_m != params$qc_name),]

meanSdPlot(x = assay(xcms_p_dc_filt), ranks = FALSE)
dt_pca <- assay(pmp::mv_imputation(xcms_p_dc_filt, method = "knn", k = 10))
mode(dt_pca) <- "integer"
dt_pca <- pmp::mv_imputation(dt_pca, method = "knn", k = 10)

dt_pca <- DESeq2::DESeqDataSetFromMatrix(round(dt_pca), colData = pca_gr_dt, 
                                        design = ~ groups_m)

dt_pca <- estimateSizeFactors(dt_pca)
dt_pca <- estimateDispersions(dt_pca)
plotDispEsts(dt_pca)
dt_pca <- varianceStabilizingTransformation(dt_pca, blind=FALSE)

meanSdPlot(x = assay(dt_pca), ranks = FALSE)

pca_dt <- prcomp(t(assay(dt_pca)), center = TRUE, scale. = TRUE)
pca_plot(pca_dt, 1, 2, group_var = as.factor(pca_gr_dt$groups_m), 
        level = 0.95, allElipse = FALSE)
```

#### Anova analisis

```{r}
library(limma)
lima_metadata <- gf_lima_meta_nb[!gf_lima_meta_nb$gfcv %in% c("G","C") & (gf_lima_meta_nb$groups_m != params$qc_name),]

lima_metadata$group <- factor(lima_metadata$groups_m, 
                            levels = c("CNT", "HFD", "INT", "HFE"))
lima_metadata

comp_names <- apply(t(combn(levels(lima_metadata$group), m = 2))[,2:1], 1, 
                    paste, collapse = "-")
comp_matrix <- matrix(NA, nrow = length(comp_names), ncol = 2)
rownames(comp_matrix) <- comp_names

tukey_results <- apply(assay(xcms_p_dc_filt), 1, function(dt_var){
    anova_results <- kruskal.test(dt_var, g = lima_metadata$group)
    anova_results <- data.frame("statistic" = anova_results$statistic,
                                "parameter" = anova_results$parameter,
                                "p.value" = anova_results$p.value)

    # anova_results2 <- aov(dt_var ~ 0 + group, data = lima_metadata)
    # comp_results <- list("Group_Test" = summary(anova_results)[[1]]["group",])
    comp_results <- list("Group_Test" = anova_results)
    #plot(anova_results)
    if(comp_results$Group_Test$p.value <= 0.05){
        comp_results$Pairwise_Tests <- DescTools::ConoverTest(dt_var,
                                                            lima_metadata$group)[[1]]
        # comp_results$Pairwise_Tests <- TukeyHSD(anova_results, which = c("group"))$group
        return(comp_results)
    } else{
        comp_results$Pairwise_Tests <- comp_matrix
        return(comp_results)
    }

})
# tukey_results <- apply(assay(xcms_p_dc_filt), 1, function(dt_var){
#     anova_results <- aov(log(dt_var) ~ 0 + group, data = lima_metadata)
#     comp_results <- list("Group_Test" = summary(anova_results)[[1]]["group",])
#     if(summary(anova_results)[[1]]["group", "Pr(>F)"] <= 0.1){
#         comp_results$Pairwise_Tests <- TukeyHSD(anova_results, which = c("group"))$group
#         return(comp_results)
#         
#     } else{
#         comp_results$Pairwise_Tests <- comp_matrix
# #         return(comp_results)
#     }
# })


anova_test_results <- lapply(tukey_results, function(ctrs){
    ctrs$Group_Test
})
anova_test_results <- do.call(rbind, anova_test_results)
# colnames(anova_test_results)[5] <- c("pvalue")
anova_test_results$adj.p.value <- p.adjust(anova_test_results$p.value)

contrasts_results <- lapply(comp_names, function(ctrs_row){
    ctrs_result_list <- lapply(tukey_results, function(ctrs){
        ctrs <- ctrs$Pairwise_Tests
        if(!(ctrs_row %in% rownames(ctrs))){return(rep(NA, 2))}
        ctrs[ctrs_row,]   
    })
    do.call(rbind, ctrs_result_list)
})
names(contrasts_results) <- comp_names

contrasts_results <- lapply(contrasts_results, function(ctrs){
    ctrs <- as.data.frame(ctrs)
    colnames(ctrs) <- c("difference", "pvalue")
    ctrs$adj.p.value <- p.adjust(ctrs[,"pvalue"], method = "fdr")
    ctrs
})

contrasts_results$Group_Test <-  anova_test_results

contrasts_results <- do.call(cbind, contrasts_results)

feature_data <- as.data.frame(rowData(xcms_p_dc_filt))
```


```{r, eval=params$hermes_filter}
hermes_dt <- readRDS(params$hermes_file)
hermes_ions <- hermes_dt@metadata@ExpParam@ionF[[2]]

hermes_dt@metadata@ExpParam@DB$Name <- gsub(";", "-", 
                                            hermes_dt@metadata@ExpParam@DB$Name)

feature_data$soi <- sapply(feature_data$soi, function(x){
    if(all(is.na(x))){return(NA)}
    paste(x, collapse = ";")})
feature_data$formula <- sapply(feature_data$formula, function(x){
    if(all(is.na(x))){return(NA)}
    paste(x, collapse = " / ")})

feature_data$neutral_formula <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
    
    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    if(length(found_formulas) == 0){return(NA)}
    paste0(found_formulas, collapse = " / ")
})

feature_data$adduct_annotation <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
    
    found_an <- hermes_ions$an[match(form, hermes_ions$ion)]
    if(length(found_an) == 0){return(NA)}
    paste0(found_an, collapse = " / ")
})
    
feature_data$PutativeMetabolites <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        paste(found_mets, collapse = ";")
    })
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$PutativeMetabolitesKEGG <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]
        
    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id & !is.na(hermes_dt@metadata@ExpParam@DB$Kegg) & hermes_dt@metadata@ExpParam@DB$Kegg != ""]
        if(length(found_mets)){
            paste(found_mets, collapse = ";")    
        } else{
            return(NA)
        }
    })
    
    # found_mets <- hermes_dt@metadata@ExpParam@DB$Name[hermes_dt@metadata@ExpParam@DB$MolecularFormula %in% found_formulas & !is.na(hermes_dt@metadata@ExpParam@DB$Kegg) & hermes_dt@metadata@ExpParam@DB$Kegg != ""]
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$kegg_id <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$Kegg[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        found_mets[is.na(found_mets) | found_mets == ""] <- NA
        if(length(found_mets)){
            paste(found_mets, collapse = ";")
        } else{
            return(NA)
        }
    })
    
    # found_mets <- hermes_dt@metadata@ExpParam@DB$Kegg[hermes_dt@metadata@ExpParam@DB$MolecularFormula %in% found_formulas]
    # found_mets <- found_mets[!is.na(found_mets) & found_mets != ""]
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)

feature_data$hmdb_id <- sapply(feature_data$formula, function(form){
    if(is.na(form)){return(NA)}
    form <- strsplit(form, " / ")[[1]]

    found_formulas <- hermes_ions$f[match(form, hermes_ions$ion)]
    
    found_mets <- sapply(found_formulas, function(formula_id){
        found_mets <- hermes_dt@metadata@ExpParam@DB$HMDB_ID[hermes_dt@metadata@ExpParam@DB$MolecularFormula == formula_id]
        found_mets[is.na(found_mets) | found_mets == ""] <- NA
        if(length(found_mets)){
            paste(found_mets, collapse = ";")
        } else{
            return(NA)
        }
    })
    
    if(length(found_mets) == 0){return(NA)}
    # if(length(found_mets) > 5){
    #     found_mets <- found_mets[1:5]
    # }
    return(paste(found_mets, collapse = " / "))
}, USE.NAMES = FALSE)


feature_data$iso_num <- sapply(seq_len(nrow(feature_data)), function(row_id){
    if(!is.na(feature_data[row_id,]$SOIData)){
        return(paste(feature_data[row_id,]$SOIData[[1]]$isofound, collapse = " / "))
    } else{
        return(NA)
    }
    
}, USE.NAMES = FALSE)

feature_data$iso_fidelity <- sapply(seq_len(nrow(feature_data)), function(row_id){
    if(!is.na(feature_data[row_id,]$SOIData)){
        return(paste(round(feature_data[row_id,]$SOIData[[1]]$isofidelity, 3), collapse = " / "))
    } else{
        return(NA)
    }
    
}, USE.NAMES = FALSE)
```


```{r}
feature_data <- cbind(feature_data, contrasts_results)

assay(xcms_p_dc_filt) <- as.data.frame(assay(xcms_p_dc_filt))

rownames(xcms_p_dc_filt) <- paste0(params$data_type, ".", rownames(xcms_p_dc_filt))

xcms_p_dc_filt$group <- factor(xcms_p_dc_filt$groups_m, 
                               levels = c("CNT", "HFD", "INT", "HFE"))
xcms_p_dc_filt$samplename <- make.names(xcms_p_dc_filt$samplename)
colnames(xcms_p_dc_filt) <- xcms_p_dc_filt$samplename

# rownames(data_table) <- paste0(params$data_type, ".", 
#                                 rownames(data_table))

rowData(xcms_p_dc_filt) <- feature_data
```

```{r}
mummichog_test <- as.data.frame(rowData(xcms_p_dc_filt)[c("mzmed", "rtmed",
                                            "Group_Test.p.value",
                                            "Group_Test.statistic")])
colnames(mummichog_test) <- c("mz", "rtime", "p-value", "t-score")

mummichog_test$custom_id <- rownames(mummichog_test)

mummichog_path <- "../../outputs/Untargeted_Metabolomics/Mummichog_results/"
if(!dir.exists(mummichog_path)){dir.create(mummichog_path)}

write.table(x = mummichog_test,
            file = paste0(mummichog_path, "mummichog_file.txt"),
            sep = "\t", row.names = FALSE, quote = FALSE)

reticulate::py_config()
system(command = paste0("mummichog -f ..\\..\\outputs\\Untargeted_Metabolomics\\Mummichog_results\\mummichog_file.txt -o myResults_Test_Full -m ", params$mummichog_ionization), wait = T)

mummichog_folder <- grep("myResults",
                         list.dirs(path = ".", full.names = T,
                                    recursive = F), value = T)
new_folder <- paste0(params$output_results, mummichog_folder)

if(!dir.exists(new_folder)) dir.create(new_folder)
file.copy(from = mummichog_folder, to = params$output_results, recursive = T)
unlink(mummichog_folder, recursive = T)
```

#### mummichog
```{r}
emp_compounds <- readLines(paste0(new_folder, "/tables/ListOfEmpiricalCompounds.tsv"))
emp_compounds <- strsplit(emp_compounds, split = "\t")
emp_compounds <- lapply(emp_compounds, function(x){
    data.table::data.table(t(x))
})
emp_compounds <- as.data.frame(data.table::rbindlist(emp_compounds, fill = TRUE))
colnames(emp_compounds) <- emp_compounds[1,]
emp_compounds <- as.data.frame(emp_compounds[-1,])

emp_compounds2 <- readLines(paste0(new_folder, "/tables/userInput_to_EmpiricalCompounds.tsv"))
emp_compounds2 <- strsplit(emp_compounds2, split = "\t")
emp_compounds2 <- do.call(rbind, emp_compounds2)
colnames(emp_compounds2) <- emp_compounds2[1,]
emp_compounds2 <- as.data.frame(emp_compounds2[-1,])

adduct_h <- ifelse(params$mummichog_ionization == "positive", "M+H[1+]", "M-H[-]")

keep_rows_test <- c()
for(id in seq_len(nrow(emp_compounds))){
    ec_dt <- emp_compounds[id, ]
    ion_list <- strsplit(ec_dt$str_row_ion, ";")[[1]]
    row_list <- strsplit(ec_dt$massfeature_rows, ";")[[1]]
    if(length(ion_list) > 1){
        
        if(any(grepl(adduct_h, ion_list))){
            keep_rows_test <- c(keep_rows_test, row_list[m_h])
        }
        
        emp_cp_info <- emp_compounds2[(emp_compounds2$input_row %in% row_list) & 
                                    !(emp_compounds2$input_row %in% keep_rows_test),]
        keep_rows_test <- c(keep_rows_test, emp_cp_info$input_row[which.max(emp_cp_info$statistic)])
            
    } else{
        keep_rows_test <- c(keep_rows_test, row_list)
    }
}

pathway_enrich <- readLines(paste0(new_folder, "/tables/mcg_pathwayanalysis_myResults_Test_Full.tsv"))
pathway_enrich <- strsplit(pathway_enrich, split = "\t")
pathway_enrich <- do.call(rbind, pathway_enrich)
colnames(pathway_enrich) <- pathway_enrich[1,]
pathway_enrich <- as.data.frame(pathway_enrich[-1,])

pathway_list <- strsplit(pathway_enrich$`overlap_EmpiricalCompounds (id)`, split = ";")
names(pathway_list) <- pathway_enrich$pathway

emp_compounds2$pathways_tested <- sapply(emp_compounds2$EID, function(x){
    found <- names(pathway_list)[sapply(pathway_list, function(y){any(y %in% x)})]
    if(length(found)){
        return(paste(found, collapse = " / "))
    } else{
        return(NA)
    }
})

merged_res <- lapply(rownames(rowData(xcms_p_dc_filt)), function(x){
    found <- emp_compounds2[emp_compounds2$CompoundID_from_user == x, 
                    c("input_row", "EID" , "str_row_ion", "compounds", 
                        "compound_names", "CompoundID_from_user", "pathways_tested")]
    if(nrow(found) == 0){
        return(rep(NA, 7))
    } else if(nrow(found) == 1){
        return(found)
    } else if(nrow(found) > 1){
        return(sapply(found, paste, collapse = " / "))
    }
})
merged_res <- do.call(rbind, merged_res)

rowData(xcms_p_dc_filt) <- cbind(rowData(xcms_p_dc_filt), merged_res)

rowData(xcms_p_dc_filt)$input_row <- sapply(rowData(xcms_p_dc_filt)$input_row, function(row_id){
    unique(strsplit(row_id, " / ")[[1]])
})


mz_rd <- as.data.frame(rowData(xcms_p_dc_filt))

hermes_f <- unique(mz_rd$neutral_formula[!is.na(mz_rd$neutral_formula)])
hermes_p_ad <- ifelse(params$mummichog_ionization == "positive", 
                        "M+H", "M-H")

keep_adducts <- sapply(hermes_f, function(f_id){
    f_dt <- mz_rd[mz_rd$neutral_formula %in% f_id,]
    
    test <- IRanges::findOverlaps(query = IRanges(start = f_dt$rtmin, 
                                          end = f_dt$rtmax), 
                                  type = "any", 
                                  drop.redundant = TRUE, 
                                  drop.self = TRUE)
    
    if(length(test) == 0){return(rownames(f_dt))} else{
        test_gr <- graph_from_data_frame(as.data.frame(test), 
                                         directed = FALSE)
        group_m <- components(test_gr)$membership
        keep_group <- sapply(unique(group_m), function(group_id){
            feature_ids <- names(group_m)[group_m == group_id]
            group_dt <- f_dt[as.numeric(feature_ids),]
            
            found_h <- grepl(hermes_p_ad, 
                            group_dt$adduct_annotation)
            if(sum(found_h) == 1){
                return(rownames(group_dt[found_h,]))
            }
            return(rownames(group_dt)[which.max(group_dt$Group_Test.statistic)[1]])
        })
        return(keep_group)
    }
})

xcms_p_dc_filt <- xcms_p_dc_filt[(mz_rd$isotope == "M0" & (rownames(mz_rd) %in% unlist(keep_adducts))) | (mz_rd$input_row %in% keep_rows_test),]
```


```{r}
# saveRDS(xcms_p_dc_filt,
#         paste0(params$output_results, "xcms_hermes_exp_lima.rds"))
```

