---
title: "Test_Correlations_Meta_Functional"
output: html_document
date: "2024-06-28"
params:
    input_dir: "../../inputs/"
    output_dir: "../../outputs/Multi_Omics_Analysis/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
library(MultiAssayExperiment)
```

```{r}
num_factors <- 2
score_filter <- 0.7
mofa_dir_name <- "sig_int_thr07_liv2"
output_dir <- paste0(params$output_dir, "MOFA_Results/", mofa_dir_name, "/")
corr_output_dir <- paste0(output_dir, "correlation_results/")

enrich_name <- "merged_kegg_results"
enrich_nw_dir <- paste0(corr_output_dir, enrich_name, "/")
# corr_output_dir <- paste0(output_dir, "correlation_results/")
# omic_dt <- readRDS(paste0(output_dir, "multi_omics_filtered.rds"))

omic_dt <- readRDS(paste0(output_dir, "multi_omics_filtered_mod.rds"))

exp_names <- names(omic_dt)[grepl("Shotgun.*Species", 
                                names(omic_dt))]

omic_dt_filt <- omic_dt[,,exp_names]


multi_omics <- readRDS(paste0(params$output_dir, 
                            "Multi_Omics_Analysis_MA_exp_lima.rds"))
exp_names_f <- names(multi_omics)[grepl("Functional", 
                                names(multi_omics))]
multi_omic_filt <- multi_omics[,,exp_names_f]


corr_feature_path <- paste0(enrich_nw_dir, "feature_count_correlated.xlsx")
corr_feature_names <- openxlsx::getSheetNames(corr_feature_path)

corr_results <- lapply(corr_feature_names, function(sheet_name){
    openxlsx::read.xlsx(corr_feature_path, sheet = sheet_name)
})

names(corr_results) <- corr_feature_names

omic_var_names <- lapply(corr_results, function(corr_res){
    corr_res$Feature_ID[grep("Shotgun", corr_res$Feature_ID)]
})

omic_var_names <- lapply(c("pearson", "spearman"), function(score_id){
    factor_res <- lapply(seq_len(num_factors), function(factor_id){
        corr_ids <- corr_results[[grep(paste0(score_id, ".", "Factor_", factor_id), names(corr_results))]]$Feature_ID
        corr_ids[grep("Shotgun", corr_ids)]
        
        exp_res <- lapply(exp_names, function(exp_names){
            gsub(paste0(exp_names, "."), "", corr_ids[grepl(exp_names, corr_ids)])
        })
        names(exp_res) <- exp_names
        exp_res
    })
    names(factor_res) <- paste0("Factor_", seq_len(num_factors))
    factor_res
})
names(omic_var_names) <- c("pearson", "spearman")

# omic_var_names <- lapply(seq_len(num_factors), function(factor_id){
#     factor_col <- paste0("Factor_", factor_id,  "_weights_sig")
# 
#     sapply(names(omic_dt_filt), function(omic_id){
#         omic_exp <- experiments(omic_dt_filt)[[omic_id]]
#         rownames(omic_exp)[rowData(omic_exp)[,factor_col]]
#     })
# })
# names(omic_var_names) <- paste0("Factor_", seq_len(num_factors))
```

## Loading the network

```{r}
nw_paths <- list.files(corr_output_dir, 
                        pattern = "network_results_0_005_chi_f1f2_.*\\.rds$", 
                        full.names = T)
nw_graphs <- lapply(nw_paths, readRDS)

nw_graphs <- lapply(nw_graphs, function(score_dt){
    lapply(score_dt, function(weight_dt){
        weight_dt[["Pairwise full liver"]]
    })
})

score_names <- gsub("\\.rds", "", sapply(strsplit(grep("network_results", 
                                                        basename(nw_paths), 
                                                        value = TRUE), "_"),
                                            function(x){x[length(x)]}))
score_filters <- c(0.8, 0.8)
names(score_filters) <- score_names
names(nw_graphs) <- score_names

rand_seed <- 1234
universe_list <- lapply(nw_graphs, function(score_dt){
    lapply(score_dt, function(graph_dt){
        names(V(graph_dt))
    })
})

nw_graphs <- lapply(names(nw_graphs), function(score_id){
    score_dt <- nw_graphs[[score_id]]
    score_res <- lapply(names(score_dt), function(graph_id){
        graph_dt <- score_dt[[graph_id]]

        graph_weights <- abs(edge_attr(graph_dt,
                        name = "weight"))
        graph_adj.p.val <- edge_attr(graph_dt, name = "adj.p.value")
        subgraph.edges(graph_dt,
                    E(graph_dt)[graph_weights >= score_filters[score_id] & graph_adj.p.val <= 0.05],
                    delete.vertices = FALSE)
    })
    names(score_res) <- names(score_dt)
    score_res
})

names(nw_graphs) <- score_names

```

## Mergin the microbiota functionalities data

```{r}
new_exps <- experiments(multi_omic_filt)

new_exps$Shotgun_Metagenomics_Functional.cecum.merge <- Reduce(
    f = function(x,y){
            combineRows(x, y, delayed = FALSE)

        },
    as.list(multi_omic_filt@ExperimentList[grepl("Functional.cecum", names(multi_omic_filt@ExperimentList))]))

new_exps$Shotgun_Metagenomics_Functional.colon.merge <- Reduce(
    f = function(x,y){
            combineRows(x, y, delayed = FALSE)

        },
    as.list(multi_omic_filt@ExperimentList[grepl("Functional.colon", names(multi_omic_filt@ExperimentList))]))

multi_omic_filt <- MultiAssayExperiment(experiments = new_exps, 
                                        colData = colData(multi_omic_filt))
multi_omic_filt <- multi_omic_filt[,,grepl("merge", names(multi_omic_filt))]
```


```{r}
filtered_exps <- lapply(names(multi_omic_filt), function(multi_omics_names){
    multi_omics_exp <- experiments(multi_omic_filt)[[multi_omics_names]]
    p_val_dt <- rowData(multi_omics_exp)[,grepl("adj.p.value", colnames(rowData(multi_omics_exp)))]
    p_val_dt <- p_val_dt[,grepl("HFD-CNT|INT-HFD|INT-CNT", colnames(p_val_dt))]
    multi_omics_exp <- multi_omics_exp[apply(as.matrix(p_val_dt) <= 0.05, 1, any),]
    
    if(nrow(multi_omics_exp) == 0){return(NA)}
    
    multi_omics_exp
})
names(filtered_exps) <- names(multi_omic_filt)
filtered_exps[is.na(filtered_exps)] <- NULL

experiments(multi_omic_filt) <- ExperimentList(filtered_exps)
```


```{r}
# test_res <- lapply(seq_len(num_factors), function(weight_id){
#     weight_vars <- omic_var_names[[weight_id]]
# 
#     organ_res <- lapply(c("cecum", "colon"), function(organ_id){
#         organ_vars <- weight_vars[[grep(organ_id, names(weight_vars), value = TRUE)]]
#         organ_vars <- make.names(organ_vars)
#         
#         if(!length(organ_vars)){return(NA)}
# 
#         functional_exp <- experiments(multi_omic_filt)[[grep(organ_id, names(multi_omic_filt), value = TRUE)]]
#         rownames(functional_exp) <- make.names(rownames(functional_exp))
#         functional_feat <- as.data.frame(t(assay(functional_exp)))
#         
#         sp_exp <- experiments(omic_dt_filt)[[grep(organ_id, names(omic_dt_filt), 
#                                                    value = TRUE)]]
#         rownames(sp_exp) <- make.names(rownames(sp_exp))
#         
#         sp_exp <- sp_exp[organ_vars,]
#         
#         if(length(organ_vars) >= ncol(sp_exp)){
#             sp_exp <- sp_exp[order(abs(rowData(sp_exp)[[paste0("Factor_", weight_id, "_weights")]]), 
#                                     decreasing = TRUE),]
# 
#             keep_names <- organ_vars[seq_len(ncol(sp_exp) - 2)]
#             extra_names <- organ_vars[!seq_along(organ_vars) %in% keep_names]
#             
#             # sp_extra <- sp_exp[extra_names,]
#             # sp_exp <- sp_exp[keep_names,]
#         } else{
#             extra_names <- NA
#             keep_names <- rownames(sp_exp)
#         }
#         sp_feat <- as.data.frame(t(assay(sp_exp)))
#         
#         merged_dt <- cbind(sp_feat, functional_feat)
#         
#         feat_res <- lapply(colnames(functional_feat), function(feat_id){
#             formula_dt <- expression(paste0(feat_id, " ~ ", 
#                                             paste0(keep_names, 
#                                                     collapse = "+")))
#             feat_lm <- lm(as.formula(eval(formula_dt)), data = merged_dt)
#             feat_lm <- step(feat_lm)
#             
#             feat_sum <- summary(feat_lm)
#             if(nrow(feat_sum$coefficients) == 1){return(NA)}
#             as.data.frame(feat_sum$coefficients[-1, "Pr(>|t|)", drop = FALSE])
#             # if(any(coef_pvals <= 0.05)){
#             #     return(feat_id)
#             # }
#         })
#         names(feat_res) <- colnames(functional_feat)
#         
#         sp_res <- lapply(colnames(sp_feat), function(sp_dt){
#             
#             # na_dt <- data.frame(NA)
#             # rownames(na_dt) <- sp_dt
#             
#             feat_pvals <- sapply(feat_res, function(f_res){
#                 if(all(is.na(f_res))){return(NA)}
#                 f_res[sp_dt,]
#             })
#             # names(feat_pvals) <- names(feat_res)
#             # feat_pvals <- do.call(rbind, feat_pvals)
#             feat_adj.pvals <- p.adjust(feat_pvals, method = "fdr")
#             feat_names <- names(feat_adj.pvals)[!is.na(feat_adj.pvals) & feat_adj.pvals <= 0.05]
#             rowData(functional_exp[feat_names,])
# 
#         })
#         names(sp_res) <- colnames(sp_feat)
#         sp_res
#     })
#     names(organ_res) <- c("cecum", "colon")
#     organ_res
# })
```

## Correlation calculation

```{r}
correlation_scores <- c("pearson", "spearman")
test_res_score <- lapply(correlation_scores, function(score_id){
    test_res <- lapply(seq_len(num_factors), function(weight_id){
        weight_vars <- omic_var_names[[score_id]][[weight_id]]
    
        organ_res <- lapply(c("cecum", "colon"), function(organ_id){
            organ_vars <- weight_vars[[grep(organ_id, names(weight_vars), value = TRUE)]]
            
            organ_vars <- make.names(organ_vars)
            if(!length(organ_vars)){return(NA)}
    
            functional_exp <- experiments(multi_omic_filt)[[grep(organ_id, names(multi_omic_filt), value = TRUE)]]
            rownames(functional_exp) <- make.names(rownames(functional_exp))
            # functional_feat <- as.data.frame(t(assay(functional_exp)))
            
            sp_exp <- experiments(omic_dt_filt)[[grep(organ_id, names(omic_dt_filt), 
                                                       value = TRUE)]]
            rownames(sp_exp) <- make.names(rownames(sp_exp))
            
            sp_exp <- sp_exp[organ_vars,]
        
            corr_dt <- mia::getExperimentCrossAssociation(
                        functional_exp, sp_exp, assay.type1 = "clr", 
                        assay.type2 = "clr", method = score_id, 
                        cor_threshold = 0.8, p_adj_method = "fdr", 
                        p_adj_threshold = 0.05, test_significance = TRUE)
            sp_res <- lapply(unique(corr_dt$Var2), function(sp_dt){
                correlated_names <- as.character(corr_dt$Var1)[as.character(corr_dt$Var2) == sp_dt]
                sp_rd <- rowData(functional_exp[correlated_names,])
                cbind(data.frame("Specie" = sp_dt, "Functionality" = correlated_names), sp_rd)
            })
            names(sp_res) <- paste0("Species.", as.character(unique(corr_dt$Var2)))
            sp_res
        })
        names(organ_res) <- c("cecum", "colon")
        organ_res
    })
    names(test_res) <- paste0("Factor_", seq_len(num_factors))
    test_res
})
names(test_res_score) <- correlation_scores


results_wb <- openxlsx::createWorkbook()
lapply(names(test_res_score), function(score_id){
    
    score_dt <- test_res_score[[score_id]]
    
    lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        lapply(names(factor_dt), function(organ_id){
            organ_dt <- factor_dt[[organ_id]]
            if(!length(organ_dt) | all(is.na(organ_dt))){return(NULL)}
            organ_dt <- do.call(rbind, organ_dt)
            
            sheet_name <- paste(score_id, factor_id, organ_id, sep = ".")
            output_name <- paste0(output_dir, "functional_associations.xlsx")
                
            openxlsx::addWorksheet(wb = results_wb,
                                    sheetName = sheet_name)
            openxlsx::writeData(wb = results_wb, sheet = sheet_name,
                                x = as.data.frame(organ_dt)[,c(1,2, 39:48)])
            openxlsx::saveWorkbook(results_wb, 
                                    file = output_name, 
                                    overwrite = TRUE)  
                
        })
    })
})
```

```{r}
results_wb <- openxlsx::createWorkbook()
lapply(names(test_res_score), function(score_id){
    
    score_dt <- test_res_score[[score_id]]
    
    lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        lapply(names(factor_dt), function(organ_id){
            organ_dt <- factor_dt[[organ_id]]
            if(!length(organ_dt) | all(is.na(organ_dt))){return(NULL)}
            organ_dt <- do.call(rbind, organ_dt)

            fun_dt <- as.data.frame(table(organ_dt$Functionality))
            
            fun_dt <- cbind(fun_dt, organ_dt[sapply(fun_dt$Var1, function(x){
                which(organ_dt$Functionality == x)[1]
            }),3:ncol(organ_dt)])
            fun_dt <- fun_dt[order(fun_dt$Freq, decreasing = TRUE),]
            
            sheet_name <- paste(score_id, factor_id, organ_id, sep = ".")
            output_name <- paste0(output_dir, "functional_associations_counts.xlsx")
                
            openxlsx::addWorksheet(wb = results_wb,
                                    sheetName = sheet_name)
            openxlsx::writeData(wb = results_wb, sheet = sheet_name,
                                x = fun_dt[,c(1,2, 39:48)])
            openxlsx::saveWorkbook(results_wb, 
                                    file = output_name, 
                                    overwrite = TRUE)  
                
        })
    })
})
```

## Correlation filter nw factor

```{r}
score_id <- "spearman"
factor_id <- "Factor_1"
organ_ids <- c("cecum", "colon")

plot_dt <- lapply(names(nw_graphs), function(score_id){
    score_dt <- nw_graphs[[score_id]]
    score_res <- lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        
        keep_nodes <- names(V(factor_dt))[igraph::degree(factor_dt) != 0 & 
                                        grepl(pattern = "Shotgun",vertex_attr(factor_dt, "Node_Omic"))]
        
        found_info <- lapply(organ_ids, function(organ_id){
            found_nodes <- grep(organ_id, keep_nodes, value = T)
            found_nodes <- strsplit(found_nodes, "\\.")
            
            nodes_info <- test_res_score[[score_id]][[factor_id]][[organ_id]]
            found_nodes <- sapply(found_nodes, function(x){make.names(paste0(x[3:length(x)], collapse = "."))})
            
            found_nodes_info <- sapply(found_nodes, function(x){
                if(x %in% names(nodes_info)){
                    return(nodes_info[[x]])
                } else{
                    return(data.frame())    
                }
            })
        })
        names(found_info) <- organ_ids
        found_info
    })
    names(score_res) <- names(score_dt)
    score_res
})
names(plot_dt) <- names(nw_graphs)
```

## Correlation filter correlated with variables

```{r}
score_id <- "spearman"
factor_id <- "Factor_1"
organ_ids <- c("cecum", "colon")

res_path <- paste0(enrich_nw_dir,
                "feature_count_correlated.xlsx")
results_names <- openxlsx::getSheetNames(res_path)


plot_dt_2 <- lapply(results_names, function(sheet_id){
    results_excel <- openxlsx::read.xlsx(xlsxFile = res_path, 
                                         sheet = sheet_id)
    results_ids <- results_excel[grepl(pattern = "Shotgun", 
                                        results_excel$Feature_ID),]
    results_ids <- results_ids$Feature_ID
    found_info <- lapply(organ_ids, function(organ_id){
        
        found_nodes <- grep(organ_id, results_ids, value = T)
        found_nodes <- strsplit(found_nodes, "\\.")
        
        nodes_info <- test_res_score[[score_id]][[factor_id]][[organ_id]]
        found_nodes <- sapply(found_nodes, function(x){make.names(paste0(x[3:length(x)], collapse = "."))})
        
        found_nodes_info <- lapply(found_nodes, function(x){
            if(x %in% names(nodes_info)){
                return(nodes_info[[x]])
            } else{
                return(data.frame())    
            }
        })
        names(found_nodes_info) <- found_nodes
        found_nodes_info
    })
    names(found_info) <- organ_ids
    found_info
 
})
names(plot_dt_2) <- results_names



```


```{r}
plot_data <- lapply(names(plot_dt_2), function(score_id){
    score_dt <- plot_dt_2[[score_id]]
    organ_res <- lapply(names(score_dt), function(organ_id){
        organ_dt <- score_dt[[organ_id]]
        factor_id <- sapply(strsplit(score_id, "\\."), function(x){x[[2]]})
        score_id <- sapply(strsplit(score_id, "\\."), function(x){x[[1]]})
        
        data.frame("num_correlations" = sapply(organ_dt, nrow),
                   "factor" = factor_id,
                   "score" = score_id,
                   "organ" = organ_id)
    })
    do.call(rbind, organ_res)
})
plot_data <- do.call(rbind, plot_data)

ggplot(plot_data, aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() +
    facet_grid(rows = vars(score)) 

ggplot(plot_data[plot_data$num_correlations != 0,], 
        aes(x = factor, y = num_correlations, color = organ)) + 
    geom_boxplot() +
    facet_grid(rows = vars(score)) 

plot_data$group <- paste(plot_data$factor, plot_data$organ)

lapply(unique(plot_data$score), function(score_id){
    aov_dt <- plot_data[plot_data$score == score_id,]
    
    kruskal_res <- kruskal.test(formula = num_correlations ~ group + 0, data = aov_dt)
    
    if(kruskal_res$p.value <= 0.05){
        DescTools::ConoverTest(x = aov_dt$num_correlations, aov_dt$group)
    }
    # aov_mod <- aov(formula = num_correlations ~ group + 0, data = aov_dt)
    # TukeyHSD(aov_mod)    
})

```

## Correlation filter correlated nw features & degree filter

```{r}
score_id <- "spearman"
factor_id <- "Factor_1"
organ_ids <- c("cecum", "colon")

res_dt <- readRDS(paste0(corr_output_dir,
                    "de_overlapped_features.rds"))


plot_dt_3 <- lapply(names(nw_graphs), function(score_id){
    score_dt <- nw_graphs[[score_id]]
    score_res <- lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        
        node_dt <- res_dt[[score_id]][[factor_id]]
        node_dt <- node_dt[node_dt$degree.x >= 5 | node_dt$degree.y >= 5,]
        
        keep_nodes <- names(V(factor_dt))[names(V(factor_dt)) %in% 
                                                grep(pattern = "Shotgun",
                                                    node_dt$nodes, value = TRUE)]
        
        found_info <- lapply(organ_ids, function(organ_id){
            found_nodes <- grep(organ_id, keep_nodes, value = T)
            found_nodes <- strsplit(found_nodes, "\\.")
            
            nodes_info <- test_res_score[[score_id]][[factor_id]][[organ_id]]
            found_nodes <- sapply(found_nodes, function(x){make.names(paste0(x[3:length(x)], collapse = "."))})
            
            found_nodes_info <- sapply(found_nodes, function(x){
                if(x %in% names(nodes_info)){
                    return(nodes_info[[x]])
                } else{
                    return(data.frame())    
                }
            })
        })
        names(found_info) <- organ_ids
        found_info
    })
    names(score_res) <- names(score_dt)
    score_res
})
names(plot_dt_3) <- names(nw_graphs)
```

```{r}
plot_data <- lapply(names(plot_dt_3), function(score_id){
    score_dt <- plot_dt_3[[score_id]]
    score_res <- lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        organ_res <- lapply(names(factor_dt), function(organ_id){
            organ_dt <- factor_dt[[organ_id]]

            data.frame("num_correlations" = sapply(organ_dt, nrow),
                       "factor" = factor_id,
                       "score" = score_id,
                       "organ" = organ_id)
        })
        do.call(rbind, organ_res)
    })
    do.call(rbind, score_res)
})
plot_data <- do.call(rbind, plot_data)

ggplot(plot_data, aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() +
    facet_grid(rows = vars(score)) + ylab("Number of correlated functions for each specie") + xlab(NULL)

ggplot(plot_data[plot_data$num_correlations != 0,], aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() +
    facet_grid(rows = vars(score)) 

plot_data$group <- paste(plot_data$factor, plot_data$organ)

lapply(unique(plot_data$score), function(score_id){
    aov_dt <- plot_data[plot_data$score == score_id & plot_data$num_correlations != 0,]
    aov_mod <- aov(formula = num_correlations ~ group + 0, data = aov_dt)
    TukeyHSD(aov_mod)    
})

```

## Correlation filter correlated nw features & degree filter

```{r}
score_id <- "spearman"
factor_id <- "Factor_1"
organ_ids <- c("cecum", "colon")

res_dt <- readRDS(paste0(corr_output_dir,
                    "de_overlapped_features.rds"))


plot_dt_3 <- lapply(names(nw_graphs), function(score_id){
    score_dt <- nw_graphs[[score_id]]
    score_res <- lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        
        node_dt <- res_dt[[score_id]][[factor_id]]

        keep_nodes <- names(V(factor_dt))[names(V(factor_dt)) %in% 
                                                grep(pattern = "Shotgun",
                                                    node_dt$nodes, value = TRUE)]
        
        found_info <- lapply(organ_ids, function(organ_id){
            found_nodes <- grep(organ_id, keep_nodes, value = T)
            found_nodes <- strsplit(found_nodes, "\\.")
            
            nodes_info <- test_res_score[[score_id]][[factor_id]][[organ_id]]
            found_nodes <- sapply(found_nodes, function(x){make.names(paste0(x[3:length(x)], collapse = "."))})
            
            found_nodes_info <- sapply(found_nodes, function(x){
                if(x %in% names(nodes_info)){
                    return(nodes_info[[x]])
                } else{
                    return(data.frame())    
                }
            })
        })
        names(found_info) <- organ_ids
        found_info
    })
    names(score_res) <- names(score_dt)
    score_res
})
names(plot_dt_3) <- names(nw_graphs)
```

```{r}
plot_data <- lapply(names(plot_dt_3), function(score_id){
    score_dt <- plot_dt_3[[score_id]]
    score_res <- lapply(names(score_dt), function(factor_id){
        factor_dt <- score_dt[[factor_id]]
        organ_res <- lapply(names(factor_dt), function(organ_id){
            organ_dt <- factor_dt[[organ_id]]

            data.frame("num_correlations" = sapply(organ_dt, nrow),
                       "factor" = factor_id,
                       "score" = score_id,
                       "organ" = organ_id)
        })
        do.call(rbind, organ_res)
    })
    do.call(rbind, score_res)
})
plot_data <- do.call(rbind, plot_data)

ggplot(plot_data, aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() +
    facet_grid(rows = vars(score)) + ylab("Number of correlated functions for each specie") + xlab(NULL)

ggplot(plot_data[plot_data$num_correlations != 0,], aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() +
    facet_grid(rows = vars(score)) 

plot_data$group <- paste(plot_data$factor, plot_data$organ)

lapply(unique(plot_data$score), function(score_id){
    aov_dt <- plot_data[plot_data$score == score_id & plot_data$num_correlations != 0,]
    aov_mod <- aov(formula = num_correlations ~ group + 0, data = aov_dt)
    TukeyHSD(aov_mod)    
})


ggplot(plot_data, aes(x = factor, y = num_correlations, color = organ)) + geom_boxplot() + ylab("Number of correlated functions for each specie") + xlab(NULL)

aov_dt <- plot_data
aov_mod <- aov(formula = num_correlations ~ group + 0, data = aov_dt)
TukeyHSD(aov_mod)    

```
## Altres

```{r}

score_res_found <- lapply(results_names, function(sheet_name){
    
    found_res <- lapply(test_res_score, function(score_dt){
        

        score_dt <- unlist(score_dt$Factor_1, recursive = FALSE)
        
        names(score_dt) <- make.names(paste0("Shotgun_Metagenomics.", names(score_dt)))
        results_excel <- results_excel[grepl("Shotgun_Metagenomics",
                                            results_excel$Feature_ID),]    
        score_dt[make.names(results_excel$Feature_ID)]
        
    })
    found_res
})
names(score_res_found) <- results_names
```


```{r}


names_vect <- lapply(test_res, function(weight_dt){
    lapply(weight_dt, function(organ_dt){
        if(all(is.na(organ_dt))){return(NA)}
        
        organ_dt <- do.call(rbind, organ_dt)
        
        
        # lapply(organ_dt, function(specie_dt){
        #     
        #     
        # })
    })
})

intersect(names_vect$Factor_1$colon, names_vect$Factor_2$colon)

setdiff(names_vect$Factor_1$colon, names_vect$Factor_2$colon)
setdiff(names_vect$Factor_2$colon, names_vect$Factor_1$colon)
```


```{r}
library(tm)
library(wordcloud)

# test_corpus <- test_res$Factor_1$colon$Family.Pyrinomonadaceae[["readable_name"]]
# test_corpus

lapply(test_res, function(weight_dt){
    lapply(weight_dt, function(organ_dt){
        if(all(is.na(organ_dt))){return(NA)}
        lapply(organ_dt, function(specie_dt){
            if(all(is.na(specie_dt)) && !nrow(specie_dt)){return(NA)}
            specie_dt <- specie_dt$readable_name
            corpus_dt <- Corpus(x = VectorSource(specie_dt))
    
            corpus_clean <- tm_map(corpus_dt, tolower)
            corpus_clean <- tm_map(corpus_clean, function(x){gsub(";|-", " ", x)})
            
            corpus_clean <- tm_map(corpus_clean, removeWords, c(stopwords(), "colon", "pwy"))
            corpus_clean <- tm_map(corpus_clean, removePunctuation)
            corpus_clean <- tm_map(corpus_clean, stripWhitespace)
            sms_dtm <- DocumentTermMatrix(corpus_clean)
            
            freq_dt <- colSums(as.matrix(sms_dtm))
            
            wordcloud(names(freq_dt), as.numeric(freq_dt), min.freq = 5, random.order = FALSE)    
        })
    })
})

```


```{r}
lapply(test_res, function(weight_dt){
    lapply(weight_dt, function(organ_dt){
        if(all(is.na(organ_dt))){return(NA)}
        
        organ_dt <- do.call(rbind, organ_dt)
        
        if(all(is.na(organ_dt)) && !nrow(organ_dt)){return(NA)}
        organ_dt <- organ_dt$readable_name
        corpus_dt <- Corpus(x = VectorSource(organ_dt))

        corpus_clean <- tm_map(corpus_dt, tolower)
        corpus_clean <- tm_map(corpus_clean, function(x){gsub(";|-", " ", x)})
        
        corpus_clean <- tm_map(corpus_clean, removeWords, c(stopwords(), "colon", "pwy"))
        corpus_clean <- tm_map(corpus_clean, removePunctuation)
        corpus_clean <- tm_map(corpus_clean, stripWhitespace)
        sms_dtm <- DocumentTermMatrix(corpus_clean)
        
        freq_dt <- colSums(as.matrix(sms_dtm))
        
        wordcloud(names(freq_dt), as.numeric(freq_dt), min.freq = 30, random.order = FALSE)    
    })
})

```

