---
title: "MOFA models"
output: html_document
date: "2024-01-18"
params:
    input_dir: "../../outputs/Multi_Omics_Analysis/"
    output_dir: "../../outputs/Multi_Omics_Analysis/MOFA_Results/"
    multi_omics_exp: !r multi_omics[,colData(multi_omics)$group != "HFE",multi_omics_selected]
    group_var: "group"
    sample_var: "samplename"
    num_factors: 2
    results_name: !r mofa_dir_name
    color_vec: !r group_color_dict
    random_seed: 1234
    convergence_mode: "slow"
    ntries: 3
    score_filter: 0.7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Required packages

```{r}
library(grDevices)
library(ggplot2)
library(plotly)
library(MOFA2)
library(dplyr)
library(MultiAssayExperiment)
library(SummarizedExperiment)
library(TreeSummarizedExperiment)
source("../Utility_Functions/utilities.R")

output_dir <- paste0(params$output_dir, params$results_name, "/")
if(!dir.exists(output_dir)){dir.create(output_dir)}
```


```{r, fig.height=8, fig.width=8}
multi_omics_mofa <- create_mofa_from_MultiAssayExperiment(mae = params$multi_omics_exp)
plot_data_overview(multi_omics_mofa)
```

## Parameters

```{r}
data_opts <- get_default_data_options(multi_omics_mofa)
head(data_opts)

model_opts <- get_default_model_options(multi_omics_mofa)
model_opts$num_factors <- params$num_factors
head(model_opts)

train_opts <- get_default_training_options(multi_omics_mofa)
train_opts$convergence_mode <- params$convergence_mode
train_opts$maxiter <- 5000
head(train_opts)
```

## LIMA model {.tabset}


```{r, results='hide'}

model_list <- list()

multi_omics_mofa <- prepare_mofa(
        object = multi_omics_mofa, data_options = data_opts,
        model_options = model_opts, training_options = train_opts
)

untrained_mofa <- multi_omics_mofa

outfile_list <- list()

for(id in seq_len(params$ntries)){
    multi_omics_mofa@training_options$seed <- params$random_seed + id
    
    outfile_list[[id]] <- paste0(output_dir, 
                      paste0("model_", id, ".hdf5"))
    
    model_list[[id]] <- run_mofa(multi_omics_mofa, 
                                 outfile = outfile_list[[id]], 
                                 use_basilisk = TRUE)    
}

selected_mod_val <- seq_len(params$ntries) %in% which.max(sapply(model_list, get_elbo))
file.remove(unlist(outfile_list[!selected_mod_val]))
file.rename(from = unlist(outfile_list[selected_mod_val]), 
            to = gsub(basename(unlist(outfile_list[selected_mod_val])), "model.hdf5",
                      outfile_list[selected_mod_val]))

multi_omics_mofa <- select_model(model_list)
rm(model_list)
```

```{r, fig.width=12, fig.height=8}
# real_weights <- get_weights(multi_omics_mofa, abs = TRUE, as.data.frame = FALSE)
# 
# real_weights$factor_view <- factor(paste(real_weights$factor, real_weights$view))
# 
# real_weights$value_order <- NA
# 
# for(level_id in levels(real_weights$factor_view)){
#     matched_ids <- real_weights$factor_view == level_id
#     real_weights$value_order[matched_ids] <- order(order(real_weights$value[matched_ids], decreasing = TRUE))
# }
# 
# 
# ggplot(real_weights) + geom_point(aes(x = value_order, y = value, 
#                                     group = view, color = view)) + 
#     facet_grid(cols = vars(factor))
# 
# ggplot(real_weights) + geom_point(aes(x = order(order(value, decreasing = TRUE)), 
#                                     y = value, group = view, color = view)) + 
#     facet_grid(cols = vars(factor))

# weight_factor_1_untargeted <- get_weights(multi_omics_mofa, views = "Untargeted_Metabolomics", 
#                                           factors = 1, abs = TRUE, as.data.frame = TRUE)
# weight_factor_1_untargeted$order_value <- order(weight_factor_1_untargeted$value, decreasing = TRUE)
# 
# ggplot(weight_factor_1_untargeted) + geom_point(aes(x = order(order(value, decreasing = TRUE)), y = value))
```

```{r}
# library(ggplot2)
# real_weights <- get_weights(multi_omics_mofa, factors = 1,
#                             abs = TRUE, as.data.frame = TRUE)
# quantile(real_weights$value, c(0.75))
# table(real_weights$view[real_weights$value >= quantile(real_weights$value, 0.75)])
# 
# real_weights <- get_weights(multi_omics_mofa, factors = 2,
#                             abs = TRUE, as.data.frame = TRUE)
# quantile(real_weights$value, c(0.75))
# table(real_weights$view[real_weights$value >= quantile(real_weights$value, 0.75)])
# 
# 
# ggplot(real_weights, aes(x = factor, y = value, color = feature, group = feature)) + geom_point() + theme(legend.text = element_blank()) + geom_line()
```


```{r}
n_rand <- 10
set.seed(1234)
random_mofa_list <- lapply(seq_len(n_rand), function(x){
    set.seed(123*x)
    untrained_mofa@data <- lapply(untrained_mofa@data, function(omic_dt){
        test <- t(replicate(n = nrow(omic_dt$group1), expr = {
            rnorm(n = ncol(omic_dt$group1), mean = 0, sd = 1)
        }))
        rownames(test) <- rownames(omic_dt$group1)
        colnames(test) <- colnames(omic_dt$group1)

        omic_dt$group1 <- test
        return(omic_dt)
        # for(row_id in seq_len(nrow(omic_dt$group1))){
        #     omic_dt$group1[row_id,] <-
        # }
    })
    run_mofa(untrained_mofa, outfile = NULL, use_basilisk = TRUE)
})
```

```{r}
weight_list <- lapply(random_mofa_list, get_weights)
quantile_list <- lapply(names(experiments(params$multi_omics_exp)), function(omic_name){
    omic_weights <- lapply(weight_list, function(x){x[[omic_name]]})
    hist_dt <- do.call(rbind, omic_weights)
    lapply(as.data.frame(hist_dt), function(x){
        quantile(x, c(0.025, 0.975))
    })
})
names(quantile_list) <- names(experiments(params$multi_omics_exp))
quantile_list
```


<!-- # ```{r} -->
<!-- # omic_dt <- get_data(multi_omics_mofa) -->
<!-- # omic_dt <- lapply(omic_dt, function(x){x$group1}) -->
<!-- # omic_dt <- do.call(rbind, omic_dt) -->
<!-- # pheatmap::pheatmap(omic_dt[names(feature_max_factor)[feature_max_factor == 1],], show_rownames = FALSE) -->
<!-- #  -->
<!-- # pheatmap::pheatmap(omic_dt[names(feature_max_factor)[feature_max_factor == 2],], show_rownames = FALSE) -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r} -->
<!-- # pheatmap::pheatmap(omic_dt[real_weights$feature[real_weights$value >= 0.6],], show_rownames = FALSE) -->
<!-- # ``` -->


### Downstream Analysis

```{r, fig.height=5}
# file_path <- "./model.hdf5"
# model <- load_model(file_path)
mofa_group_var <- colData(params$multi_omics_exp)[[params$group_var]]
names(mofa_group_var) <- colData(params$multi_omics_exp)[[params$sample_var]]

# colData(multi_omics)$sample <- colData(multi_omics)$samplename

rownames(samples_metadata(multi_omics_mofa)) <- samples_metadata(multi_omics_mofa)$sample

samples_metadata(multi_omics_mofa)$groups <- droplevels(mofa_group_var[as.character(samples_metadata(multi_omics_mofa)$sample)])

p <- plot_variance_explained(multi_omics_mofa) + theme(axis.text.x = element_text(size = 8, angle = 90))
print(p)

pdf(paste0(output_dir, "mofa_explained_var.pdf"))
print(p)
dev.off()

p <- plot_factor(multi_omics_mofa, group_by = "groups", 
                factors = seq_len(params$num_factors), 
                color_by = "groups", add_violin = TRUE)

p <- p + 
  scale_color_manual(values= params$color_vec) +
  scale_fill_manual(values= params$color_vec)
print(p)

pdf(paste0(output_dir, "mofa_factors_violin.pdf"))
print(p)
dev.off()
```

```{r, fig.height=12, fig.width=12}
p <- plot_factors(multi_omics_mofa, 
  factors = seq_len(params$num_factors), 
  color_by = "groups", 
  legend = TRUE, 
) + scale_fill_manual(values = params$color_vec)

print(p)
pdf(paste0(output_dir, "mofa_factors_scatter.pdf"))
print(p)
dev.off()
```

```{r, eval=params$num_factors >= 3}
pca_dt <- MOFA2::get_factors(object = multi_omics_mofa, factors = seq_len(params$num_factors))

MOFA2::get_variance_explained(object = multi_omics_mofa, factors = seq_len(params$num_factors))

d3plot <- plot_ly(x = pca_dt$group1[,1], y = pca_dt$group1[,2], 
                    z = pca_dt$group1[,3], 
                    color = samples_metadata(multi_omics_mofa)$groups)
d3plot <- d3plot %>% add_markers()
# d3plot <- d3plot %>% layout(scene = list(xaxis = list(title = paste0('PC1', "(", pcvar[1], "%)")),
#                      yaxis = list(title = paste0('PC2', "(", pcvar[2], "%)")),
#                      zaxis = list(title = paste0('PC4', "(", pcvar[4], "%)"))))
d3plot
```

```{r}
weight_dt <- get_weights(object = multi_omics_mofa)

saveRDS(weight_dt, paste0(output_dir, "weight_list.rds"))

factor_dt <- MOFA2::get_factors(object = multi_omics_mofa)

saveRDS(factor_dt, paste0(output_dir, "factor_data.rds"))

var_dt <- MOFA2::get_variance_explained(object = multi_omics_mofa)

saveRDS(var_dt, paste0(output_dir, "var_data.rds"))

highest_weights <- weight_dt$feature[weight_dt$value >= quantile(weight_dt$value, 0.95) | weight_dt$value <= quantile(weight_dt$value, 0.05)]
```

## Factor highest weights {.tabset}


```{r fig.height=15}
# real_weight_full <- get_weights(multi_omics_mofa,
#                             abs = TRUE, as.data.frame = TRUE)
# sum(real_weight_full$value > 0.06247982)
# table(real_weight_full$factor[real_weight_full$value > 0.06247982])
# table(real_weight_full$factor[real_weight_full$value < 0.06247982])
# 
# real_weight_full <- get_weights(multi_omics_mofa,
#                             abs = TRUE, as.data.frame = FALSE)
# real_weight_full <- lapply(names(real_weight_full), function(omic_id){
#     omic_weights <- as.data.frame(real_weight_full[[omic_id]])
#     omic_weights$view <- omic_id
#     omic_weights$feature <- gsub(paste0("_", omic_id), "",
#                                  rownames(omic_weights))
#     return(omic_weights)
# })
# real_weight_full <- do.call(rbind, real_weight_full)
# 
# feature_max_factor <- apply(real_weight_full, 1, which.max)
# names(feature_max_factor) <- rownames(real_weight_full)
# 
# quantile(real_weight_full$value, c(0.95))
# 
# hist(real_weight_full$Factor1 / rowSums(real_weight_full[,1:3]))
# hist(real_weight_full$Factor2 / rowSums(real_weight_full[,1:3]))
# hist(real_weight_full$Factor3 / rowSums(real_weight_full[,1:3]))
# 
# test_props <- abs(real_weight_full[,1:3]) / rowSums(abs(real_weight_full[,1:3]))
# all.equal(unname(rowSums(test_props)), rep(1, nrow(test_props))) #All proportions add to 1
# 
# test_props$Omic <- real_weight_full$view
# test_props$Feature <- real_weight_full$feature
# library(ggtern)
# ggtern(test_props, aes(Factor1, Factor2, Factor3)) +
#     geom_point(alpha=0.05) +
#     facet_wrap(vars(Omic), ncol=5)

```

```{r}
# hist(test_props$Factor1)
# hist(test_props$Factor2)
# hist(test_props$Factor3)
```

```{r}
exp_dt <- get_data(object = multi_omics_mofa)
score_dt <- get_factors(object = multi_omics_mofa)
```

```{r}
# weight_dt <- get_weights(object = multi_omics_mofa, scale = TRUE, abs = TRUE)
# thr <- 0.5
# 
# omic_res <- lapply(names(exp_dt), function(omic_name){
#     omic_weights <- as.data.frame(weight_dt[[omic_name]])
#     lapply(omic_weights, function(x){rownames(omic_weights)[x >= thr]})
# })
# names(omic_res) <- names(exp_dt)
# 
# omic_res <- omic_res[sapply(omic_res, length) != 0]
# 
# omic_res <- lapply(seq_along(omic_res[[1]]), function(factor_id){
#     lapply(omic_res, function(omic_dt){
#         if(!length(omic_dt)){return(NULL)}
#         omic_dt[[factor_id]]
#     })    
# })

```

```{r}
thr <- params$score_filter
thr_score <- 0

weight_dt <- get_weights(object = multi_omics_mofa)

omic_res <- lapply(names(exp_dt), function(omic_name){
    omic_weights <- weight_dt[[omic_name]]
    
    omic_weight_props <- abs(omic_weights)
    
    omic_weight_props <- omic_weight_props/rowSums(omic_weight_props)
    
    apply(omic_weight_props, 2, function(x){
        names(x)[x >= thr]
    }, simplify = FALSE)
        
    # score_list <- lapply(seq_along(factor_selected), function(x){
    #     
    #     f <- factor_selected[[x]]
    #     # predicted <- (as.matrix(weight_dt[[omic_name]][,x]) %*% t(score_dt[[1]][,x]))[f,, drop = FALSE]
    #     predicted <- MOFA2::predict(multi_omics_mofa, views = omic_name, 
    #                                 factors = x)[[1]][[1]][f,, drop = FALSE]
    #     
    #     real <- exp_dt[[omic_name]][[1]][f,, drop = FALSE]
    #     residuals <- (real-predicted)
    #     
    #     # predicted_all <- (as.matrix(weight_dt[[omic_name]]) %*% t(score_dt[[1]]))[f,, drop = FALSE]
    #     predicted_all <- MOFA2::predict(multi_omics_mofa, 
    #                                     views = omic_name)[[1]][[1]][f,, drop = FALSE]
    #     
    #     residuals_all <- real - predicted_all
    #     
    #     score_vect <- rowSums((residuals_all)^2, na.rm = T) / rowSums((residuals)^2, na.rm = T)
    #     return(names(score_vect)[score_vect >= thr_score])
    # })
    
    # return(score_list)
})
names(omic_res) <- names(exp_dt)

omic_res <- omic_res[sapply(omic_res, length) != 0]

omic_res <- lapply(seq_along(omic_res[[1]]), function(factor_id){
    lapply(omic_res, function(omic_dt){
        if(!length(omic_dt)){return(NULL)}
        omic_dt[[factor_id]]
    })    
})
# test_props <- abs(weight_dt[["Untargeted_Metabolomics"]][,1:3]) / rowSums(abs(weight_dt[["Untargeted_Metabolomics"]][,1:3]))
# 
# max_factor <- apply(test_props[,1:3], 2, function(x){
#     which(x > thr)
# })
# 
# 
# score_list <- lapply(seq_along(max_factor), function(x){
#     f <- max_factor[[x]]
#     predicted <- (weight_dt[["Untargeted_Metabolomics"]][,x] %*% t(score_dt[[1]][,x]))[f,]
#     real <- exp_dt[["Untargeted_Metabolomics"]][[1]][f,]
#     residuals <- (real-predicted)
#     
#     predicted_all <- (weight_dt[["Untargeted_Metabolomics"]] %*% t(score_dt[[1]]))[f,]
#     residuals_all <- real - predicted_all
#     
#     hist(rowSums(residuals_all-residuals))
#     hist(rowSums((residuals_all-residuals)^2))
#     hist(rowSums((residuals_all)^2) / rowSums((residuals)^2))
#     
#     return(rowSums((residuals_all)^2) / rowSums((residuals)^2))
# })
# f1_09 <- names(score_list[[1]][score_list[[1]] >=0.9])
# 
# f1_09 
# length(union(names(max_factor[[1]]), f1_09))
# length(intersect(names(max_factor[[1]]), f1_09))
# sum(test_props[,1] > 0.8)


# pheatmap::pheatmap()
```


```{r, results='asis'}
var_exp_dt <- MOFA2::get_variance_explained(multi_omics_mofa)[[2]][[1]]/100

keep_var_list <- list()

multi_assay_list <- params$multi_omics_exp

for(id in seq_len(params$num_factors)){
    
    # multi_assay_list[[id]] <- multi_omics[,,multi_omics_selected]
    # keep_var_list[id] <- list(c())
    
    weight_dt <- get_weights(multi_omics_mofa, factors = id)
    cat(paste0("### Factor ", id, "\n"))
    cat("\n")
    # pdf(paste0(output_dir, "factor_", id, "_top_variable_heatmaps.pdf"))
    for(view_id in MOFA2::views_names(multi_omics_mofa)){
        cat(paste0("#### ", view_id, "\n"))
        cat("\n")
        
        
        exp_dt <- MOFA2::get_data(multi_omics_mofa, views = view_id)[[1]][[1]]
        exp_metadata <- samples_metadata(multi_omics_mofa)
        # exp_metadata <- colData(multi_omics[,,multi_omics_selected])
            
        # feature_n_percent <- var_exp_dt[id,view_id]
        # feature_n <- ceiling(min(nrow(exp_dt)*feature_n_percent, 2000))
        # feature_n <- ceiling(nrow(exp_dt)*feature_n_percent)

        factor_weight_dt <- weight_dt[[view_id]]
        rownames(factor_weight_dt) <- gsub(paste0("_", view_id), "", 
                                            rownames(factor_weight_dt))
        
        keep_vars <- omic_res[[id]][[view_id]]
        keep_vars <- gsub(paste0("_", view_id), "", keep_vars)
        
        samples_found <- !matrixStats::colAlls(x = exp_dt, value = NA)
        
        # rownames(factor_weight_dt) <- gsub(paste0("_", view_id), "", rownames(factor_weight_dt))
        rownames(exp_dt) <- gsub(paste0("_", view_id), "", rownames(exp_dt))

        # keep_vars <- rownames(factor_weight_dt)[order(abs(factor_weight_dt[,1]), 
        #                                             decreasing = TRUE)][seq_len(feature_n)]
        
        # keep_var_list[[id]] <- c(keep_var_list[[id]], keep_vars) 
        
        rowData(experiments(multi_assay_list)[[view_id]])[[paste0("Factor_", id, "_weights")]] <- factor_weight_dt[,1]
        rowData(experiments(multi_assay_list)[[view_id]])[[paste0("Factor_", id, "_weights_sig")]] <- rownames(factor_weight_dt) %in% keep_vars
        
        if(length(keep_vars) < 2){next}

        heatMapFun(exp_dt[keep_vars, samples_found], 
                metadata = exp_metadata[samples_found,], 
                stratificationVar = "groups", 
                cdQuantile = 0, 
                plot_name = paste(view_id, "Top", length(keep_vars), 
                                "Variables in factor", id, 
                                "(By absolute weight)"), 
                show_colnames = ifelse(length(keep_vars) >= 100, FALSE, TRUE), 
                show_rownames = TRUE,
                clustering_distance_rows = "euclidean")
        cat("\n")

    }
    # dev.off()
}
saveRDS(multi_assay_list, paste0(output_dir, "multi_omics_filtered.rds"))
```

## Appendix

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}

```