---
title: "16S_jan2023"
author: "Jordi Rofes Herrera"
date: "2023-01-30"
output: html_document
params:
    input_dir: "../../inputs/16S_Metagenomics/"
    output_dir: "../../outputs/16S_Metagenomics/"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages

```{r}
library(dplyr)
library(stringi)
library(mixOmics)
library(sva)
library(SummarizedExperiment)
library(mia)
library(TreeSummarizedExperiment)
```


## Initial processing

### GF/CV

```{r}
organ_dir <- list.dirs(params$input_dir, full.names = TRUE, recursive = FALSE)

organ_dt_list <- lapply(organ_dir, function(organ_dt){
    meta_files <- list.files(organ_dt, pattern = ".txt$", full.names = TRUE)
    
    meta_files_proc <- lapply(meta_files, function(meta_file_path){
        meta_f <- read.table(file = meta_file_path, sep = "\t", row.names = 1)
        meta_f <- dplyr::select(meta_f, contains(c("CM", "CF")))
        colnames(meta_f) <- gsub("X_", "", colnames(meta_f))
        meta_f <- as.data.frame(t(meta_f))
        meta_f <- meta_f %>% select_if(colSums(.) != 0)
        t(meta_f)
    })
    names(meta_files_proc) <- gsub(pattern = ".txt$", "", basename(meta_files))
    meta_files_proc
})
names(organ_dt_list) <- basename(organ_dir)

# saveRDS(organ_dt_list, "16S_data_list.rds")
```

```{r}
gfcv_16s_cond <- data.frame(samplename= colnames(organ_dt_list$cecum$feature_table_class))

gfcv_16s_cond$type_gfcv <- stri_sub(gfcv_16s_cond$samplename,1,2)

gfcv_16s_cond$group <- stri_sub(gfcv_16s_cond$samplename,1,1)

gfcv_16s_cond$sex <- stri_sub(gfcv_16s_cond$samplename,2,2)

gfcv_16s_cond$batch <- stri_sub(gfcv_16s_cond$samplename,4,4)

gfcv_16s_cond$all <- paste0(gfcv_16s_cond$type_gfcv,stri_sub(gfcv_16s_cond$samplename,4,4))

rownames(gfcv_16s_cond) <- gfcv_16s_cond$samplename

gfcv_16s_cond_cec <- dplyr::select(gfcv_16s_cond, -samplename)
```

```{r}
gfcv_16s_cond <- data.frame(samplename= colnames(organ_dt_list$colon$feature_table_class))

gfcv_16s_cond$type_gfcv <- stri_sub(gfcv_16s_cond$samplename,1,2)

gfcv_16s_cond$group <- stri_sub(gfcv_16s_cond$samplename,1,1)

gfcv_16s_cond$sex <- stri_sub(gfcv_16s_cond$samplename,2,2)

gfcv_16s_cond$batch <- stri_sub(gfcv_16s_cond$samplename,4,4)

gfcv_16s_cond$all <- paste0(gfcv_16s_cond$type_gfcv,stri_sub(gfcv_16s_cond$samplename,4,4))

rownames(gfcv_16s_cond) <- gfcv_16s_cond$samplename

gfcv_16s_cond_col <- dplyr::select(gfcv_16s_cond, -samplename)

metadata_list <- list(gfcv_16s_cond_cec, gfcv_16s_cond_col)
names(metadata_list) <- names(organ_dt_list)

metadata_list <- lapply(metadata_list, function(organ_dt){
    organ_dt$gfcv <- factor(organ_dt$group, levels = c("C", "G"))
    organ_dt$sex <- factor(organ_dt$sex, levels = c("M", "F"))
    organ_dt$group <- factor(organ_dt$type_gfcv, levels = c("CM", "CF"), labels = c("CVM", "CVF"))
    organ_dt
})

# saveRDS(metadata_list, "16S_metadata_list.rds")
```

```{r, message=FALSE}
pca_res <- lapply(seq_along(organ_dt_list), function(organ_id){
    organ <- organ_dt_list[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]
    lapply(organ, function(hierarchy){
        #pca(mat = hierarchy, metadata = organ_meta, scale = FALSE)
        mixOmics::pca(t(hierarchy), ncomp = 6, center = TRUE, scale = TRUE,
         max.iter = 500, tol = 1e-09, logratio = 'none',   ilr.offset = 0.001,
         V = NULL, multilevel = NULL)
    })
})
names(pca_res) <- names(organ_dt_list)

lapply(seq_along(pca_res), function(organ_id){
    organ <- pca_res[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]

    lapply(seq_along(organ), function(hierarchy_id){
        hierarchy <- organ[[hierarchy_id]]
        names(organ)[hierarchy_id]
        
        # biplot(pcaobj = hierarchy, x = "PC1", y = "PC2", colby = "sex", colkey = c("M" = "blue", "F" = "red"), ellipse = FALSE)
        #biplot(pcaobj = hierarchy, x = "PC1", y = "PC2", colby = "batch", ellipse = FALSE)
        plotIndiv(hierarchy, ind.names = T, group = organ_meta$batch, 
                  legend = T, title= "16S phylum 80% by gfcv",ellipse = T, ellipse.level = 0.99)
    })
})
```

```{r}
perc_thr <- 0.2
group_var <- "type_gfcv"

organ_dt_list_fil <- lapply(seq_along(organ_dt_list), function(organ_id){
    organ <- organ_dt_list[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]
    lapply(organ, function(hierarchy){
        zero_mat <- hierarchy == 0
        
        group_levels <- unique(organ_meta[[group_var]])
        
        row_keep <- matrix(nrow = nrow(hierarchy), ncol = length(group_levels))
        
        for(gr_id in seq_along(group_levels)){
            group_zero_mat <- zero_mat[,organ_meta[[group_var]] == group_levels[gr_id]]
            row_keep[,gr_id] <- rowSums(group_zero_mat) < (ncol(group_zero_mat)*perc_thr)
        }
        row_keep <- apply(row_keep, 1, any)
        hierarchy[row_keep,]
    })
})

names(organ_dt_list_fil) <- names(organ_dt_list)

# saveRDS(organ_dt_list_fil, "16S_data_list.rds")
```

```{r, message=FALSE}
pca_res <- lapply(seq_along(organ_dt_list_fil), function(organ_id){
    organ <- organ_dt_list_fil[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]
    lapply(organ, function(hierarchy){
        #pca(mat = hierarchy, metadata = organ_meta, scale = FALSE)
        mixOmics::pca(t(hierarchy), ncomp = 6, center = TRUE, scale = TRUE,
         max.iter = 500, tol = 1e-09, logratio = 'none', ilr.offset = 0.001,
         V = NULL, multilevel = NULL)
    })
})
names(pca_res) <- names(organ_dt_list)

lapply(seq_along(pca_res), function(organ_id){
    organ <- pca_res[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]

    lapply(seq_along(organ), function(hierarchy_id){
        hierarchy <- organ[[hierarchy_id]]
        # biplot(pcaobj = hierarchy, x = "PC1", y = "PC2", colby = "sex", colkey = c("M" = "blue", "F" = "red"), ellipse = FALSE)
        #biplot(pcaobj = hierarchy, x = "PC1", y = "PC2", colby = "batch", ellipse = FALSE)
        plotIndiv(hierarchy, ind.names = T, group = organ_meta$type_gfcv, 
                  legend = T, title= paste("16S", names(organ)[hierarchy_id], "80% by gfcv"),ellipse = T, ellipse.level = 0.99)
    })
})
```

### Statistical Analysis

```{r}
stat_res <- lapply(seq_along(organ_dt_list_fil), function(organ_id){
    organ <- organ_dt_list_fil[[organ_id]]
    organ_meta <- metadata_list[[organ_id]]
    
    names_comp <- t(combn(levels(organ_meta$group), 
                                m = 2))[,2:1, drop = FALSE]
    comp_mat <- as.data.frame(matrix(NA, ncol = 2, nrow = length(names_comp)))
    rownames(comp_mat) <- names_comp
    colnames(comp_mat) <- c("mean rank diff", "p.value")
    
    lapply(organ, function(hierarchy){
        hierarchy_batch <- ComBat(dat = hierarchy, batch = organ_meta$batch)
        #hierarchy <- as.data.frame(clr(t(hierarchy)))
        hierarchy_batch <- as.data.frame(t(hierarchy_batch))
        #pca(mat = hierarchy, metadata = organ_meta, scale = FALSE)
        var_results <- lapply(hierarchy_batch, function(dt_var){
            comp_res <- apply(names_comp, 1, function(comp_name){
                wil_res <- wilcox.test(x = dt_var[comp_name[1] == organ_meta$group], 
                                        y = dt_var[comp_name[2] == organ_meta$group])
                as.data.frame(wil_res[c("statistic", "p.value")])
            })
            comp_res <- as.data.frame(do.call(rbind, comp_res))
            rownames(comp_res) <- paste(names_comp, collapse = "_")
            
            comp_res
        })
        
        gf_comps <- lapply(levels(organ_meta$group), function(comp_group){
            hierarchy_subset <- hierarchy_batch[comp_group == organ_meta$group,]
            comp_res <- as.data.frame(do.call(rbind, lapply(hierarchy_subset, function(dt_var){
                as.data.frame(wilcox.test(dt_var, mu = 0)[c("statistic", "p.value")])
            })))
            comp_res$adj.p.value <- p.adjust(comp_res$p.value, "fdr")
            comp_res
        })
        names(gf_comps) <- paste0(ifelse(grepl("M", levels(organ_meta$group)), "GFM", "GFF"), 
                                    "_", levels(organ_meta$group))
        
        all_gfcv_comps <- lapply(unique(organ_meta$gfcv), function(comp_group){
            hierarchy_subset <- hierarchy_batch[comp_group == organ_meta$gfcv,]
            comp_res <- as.data.frame(do.call(rbind, lapply(hierarchy_subset, function(dt_var){
                as.data.frame(wilcox.test(dt_var, mu = 0)[c("statistic", "p.value")])
            })))
            comp_res$adj.p.value <- p.adjust(comp_res$p.value, "fdr")
            comp_res
        })
        names(all_gfcv_comps) <- "GF_CV"
        
        names_comp_paste <- apply(names_comp, 1, paste0, collapse = "_")
        comp_list <- lapply(names_comp_paste, function(idv_comp){
            results_list <- lapply(var_results, function(results_mat){
                if(idv_comp %in% rownames(results_mat)){
                    return(results_mat[idv_comp,])} 
                else{
                    return(rep(NA, 2))
                }
            })
            results_list <- as.data.frame(do.call(rbind, results_list))
            results_list$adj.p.value <- p.adjust(results_list$p.value, method = "fdr")
            results_list
        })
        names(comp_list) <- names_comp_paste
        result_dt <- do.call(cbind, c(all_gfcv_comps, gf_comps, comp_list))
        
        summ_exp <- TreeSummarizedExperiment(
            assays = list("relabundance" = hierarchy), 
            rowData = result_dt, 
            colData = organ_meta)
        summ_exp
    })
})
names(stat_res) <- names(organ_dt_list_fil)

# saveRDS(stat_res, "./16S_results_gfcv_list.rds")
```


```{r}
x16S_exp <- lapply(stat_res, function(organ){
    names(organ) <- sapply(strsplit(names(organ), "_"), function(x){x[[3]]})
    organ_tree <- lapply(names(organ), function(hierarchy_name){
        hierarchy <- organ[[hierarchy_name]]
        hierarchy_ids <- c("D_0", "D_1", "D_2", "D_3", "D_4", "D_5", "D_6")
        hierarchy_ranks <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
        
        max_rank <- grep(stringr::str_to_title(hierarchy_name), hierarchy_ranks)
        
        hierarchy_ids <- hierarchy_ids[seq_len(max_rank)]
        hierarchy_ranks <- hierarchy_ranks[seq_len(max_rank)]
        
        hierarchycal_tree <- lapply(rownames(hierarchy), function(sp_name){
            hierarchy_found <- c()
            
            for(h_id_num in seq_along(hierarchy_ids)){
                h_id <- hierarchy_ids[h_id_num]
                
                found_id <- grep(paste0("^", h_id, "__"), 
                                strsplit(sp_name, ";")[[1]], value = TRUE)
                
                if(length(found_id)){
                    found_dt <- gsub(paste0(h_id, "__"), "", found_id)
                    found_dt <- gsub("\\[|\\]", "", found_dt)

                    if(found_dt == "" || grepl("uncultured|unknown|unidentified|metagenome", found_dt, ignore.case = TRUE)){
                        hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]), 
                                                            hierarchy_found[h_id_num - 1], 
                                                            paste("Unknown", hierarchy_found[h_id_num - 1]))
                    } else{
                        hierarchy_found[h_id_num] <- found_dt
                    }
                } else{
                    hierarchy_found[h_id_num] <- ifelse(grepl("Unknown", hierarchy_found[h_id_num - 1]), 
                                                            hierarchy_found[h_id_num - 1], 
                                                            paste("Unknown", hierarchy_found[h_id_num - 1]))
                }    
            }
            return(hierarchy_found)
        })
        
        hierarchycal_tree <- do.call(rbind, hierarchycal_tree)
        colnames(hierarchycal_tree) <- hierarchy_ranks
        
        rowData(hierarchy) <- cbind(hierarchycal_tree, rowData(hierarchy))
        rowData(hierarchy)$old_names <- rownames(hierarchy)
        
        hierarchy <- mia::agglomerateByRank(x = hierarchy, rank = hierarchy_ranks[max_rank])
        hierarchy <- mia::addTaxonomyTree(hierarchy)
        
        rowData(hierarchy)$specie_names <- rownames(hierarchy)
        hierarchy
    })
    organ_tree <- names(organ)
    organ_tree
})

saveRDS(x16S_exp, paste0(params$output_dir, "16S_Metagenomics_exp_gfcv.rds"))
```

