---
title: "PTM Data Analysis"
output: html_document
date: "2023-04-18"
params: 
    input_dir: "../../inputs/Histone_Modifications_Proteomics/"
    output_dir: "../../outputs/Histone_Modifications_Proteomics/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
library(car)
library(DescTools)
library(SummarizedExperiment)
```

## LiMa

```{r}
ptm_data <- read.csv(paste0(params$input_dir, "mydataLIMAptm_relabu.csv"), row.names = 1)
rownames(ptm_data) <- ptm_data$Replicate_Name


ptm_metadata <- ptm_data[,1:2]
ptm_data <- ptm_data[,3:ncol(ptm_data)]
ptm_metadata$group <- factor(ptm_metadata$group, levels = c("C", "H", "I", "E"), 
                              labels = c("CNT", "HFD", "INT", "HFE"))

histone_names <- sapply(strsplit(colnames(ptm_data), "_"), function(x){
    histone_residues <- x[4]
    histone_residues <- stringr::str_extract_all(string = histone_residues, 
                                                pattern = "[K][[:digit:]]{1,5}|[M][[:digit:]]{1,5}|[M]{1,5}")[[1]]
    
    histone_modifications <- x[5]
    not_used <- ifelse(grepl("NOT", ignore.case = TRUE, 
                            histone_modifications), 
                        "_Not.Used", "")
    histone_modifications <- gsub("\\.Not.*", replacement = "", 
                                x = histone_modifications, ignore.case = TRUE)
    
    histone_modifications <- stringr::str_extract_all(string = histone_modifications,
                                                    pattern = "ox[[:digit:]]?|p[[:digit:]]?|ac[[:digit:]]?|m[[:digit:]]?")[[1]]
    
    if(length(histone_residues) != length(histone_modifications)){return("BAD")}
    paste0(x[1], paste0(paste0(histone_residues, 
                                histone_modifications), collapse = ""), 
            not_used)
})

histone_rd <- lapply(strsplit(colnames(ptm_data), "_"), function(x){
    histone_residues <- x[4]
    histone_residues <- stringr::str_extract_all(string = histone_residues, 
                            pattern = "[K][[:digit:]]{1,5}|[M][[:digit:]]{1,5}|[M]{1,5}")[[1]]
    histone_modifications <- x[5]
    not_used <- ifelse(grepl("NOT", ignore.case = TRUE, 
                            histone_modifications), 
                        "_Not.Used", "")
    
    histone_modifications <- gsub("\\.Not.*", replacement = "", 
                                x = histone_modifications, ignore.case = TRUE)
    
    histone_modifications <- stringr::str_extract_all(string = histone_modifications,
                                                    pattern = "ox[[:digit:]]?|p[[:digit:]]?|ac[[:digit:]]?|m[[:digit:]]?")[[1]]
    
    histone_3.3 <- grepl("3.3", x[1])
    histone_residues_K <- grep(x = histone_residues, pattern = "K", 
                                value = TRUE)
    
    data.frame("Histone_Name" = gsub("\\.3$", "", x[1]), 
               "isHistone3.3" = histone_3.3, 
               "Histone_Residues" = paste0(histone_residues, collapse = "/"),
               "Histone_Residues_K" = paste0(histone_residues_K, collapse = "/"),
               "Histone_Modifications" = paste0(histone_modifications, 
                                                collapse = "/"))
})
histone_rd <- do.call(rbind, histone_rd)

colnames(ptm_data) <- histone_names
# ptm_data <- ptm_data[,!grepl("NOT", colnames(ptm_data), ignore.case = TRUE)]

# saveRDS(list("LIMA"= list("PTM_Data" = ptm_data, "PTM_Metadata" = ptm_metadata)),"./ptm_data_list.rds")
```

```{r}
# boxplot(log(t(ptm_data)))
# 
# pheatmap::pheatmap(scale(as.matrix(ptm_data)), show_colnames = FALSE, 
#                    annotation_row = ptm_metadata[,"group", drop = FALSE])
# 


# pheatmap::pheatmap(scale(as.matrix(ptm_data)), show_colnames = FALSE, 
#                    annotation_row = ptm_metadata[,"group", drop = FALSE])
# 
# 
# ptm_data2 <- limma::normalizeMedianValues(ptm_data)
# boxplot(colSums(t(ptm_data)))
# 
# pheatmap::pheatmap(scale(as.matrix(ptm_data2)), show_colnames = FALSE, 
#                    annotation_row = ptm_metadata[,"group", drop = FALSE])

```


```{r}
# lapply(ptm_data, function(x){boxplot(x ~ ptm_metadata$group)})
# 
# lapply(ptm_data, LeveneTest, group = ptm_metadata$group)
# lapply(ptm_data, function(x){
#     tapply(x, INDEX = ptm_metadata$group, FUN = function(y){
#         qqnorm(y)
#         qqline(y)
#     })
# })

```

```{r}
# names_comp <- apply(t(combn(levels(ptm_metadata$group), m = 2))[,2:1], 1, paste, collapse = "-")
# comp_mat <- as.data.frame(matrix(NA, ncol = 4, nrow = length(names_comp)))
# rownames(comp_mat) <- names_comp
# colnames(comp_mat) <- c("difference", "lower", "upper", "pvalue")
# 
# tukey_results <- lapply(ptm_data, function(dt_var){
#     anova_res <- aov(dt_var ~ 0 + group, ptm_metadata)
#     anova_sum <- summary(anova_res)[[1]]["group","Pr(>F)"]
#     if(anova_sum <= 0.05){
#         return(TukeyHSD(anova_res, which = "group")[[1]])
#     } else{
#         return(comp_mat)
#     }
# })
# 
# comp_results_list <- lapply(names_comp, function(name_comp){
#     comp_results <- lapply(tukey_results, function(dt_var){
#         if(name_comp %in% rownames(dt_var)){
#             return(dt_var[name_comp,])
#         } else{
#             return(rep(NA, 4))
#         }
#     })
#     comp_results <- as.data.frame(do.call(rbind, comp_results))
#     names(comp_results) <-  c("difference", "lower", "upper", "p.value")
#     comp_results$adj.p.value <- p.adjust(comp_results$p.value, method = "fdr")
#     comp_results
# })
# names(comp_results_list) <- names_comp

######

comp_names <- apply(t(combn(levels(ptm_metadata$group), m = 2))[,2:1], 1, 
                    paste, collapse = "-")
comp_matrix <- matrix(NA, nrow = length(comp_names), ncol = 2)
rownames(comp_matrix) <- comp_names

tukey_results <- apply(ptm_data, 2, function(dt_var){
    anova_results <- kruskal.test(dt_var, g = ptm_metadata$group)
    anova_results <- data.frame("statistic" = anova_results$statistic,
                                "parameter" = anova_results$parameter,
                                "p.value" = anova_results$p.value)

    # anova_results2 <- aov(dt_var ~ 0 + group, data = lima_metadata)
    # comp_results <- list("Group_Test" = summary(anova_results)[[1]]["group",])
    comp_results <- list("Group_Test" = anova_results)
    #plot(anova_results)
    if(comp_results$Group_Test$p.value <= 0.05){
        comp_results$Pairwise_Tests <- DescTools::ConoverTest(dt_var, ptm_metadata$group)[[1]]
        # comp_results$Pairwise_Tests <- TukeyHSD(anova_results, which = c("group"))$group
        return(comp_results)
    } else{
        comp_results$Pairwise_Tests <- comp_matrix
        return(comp_results)
    }

})

anova_test_results <- lapply(tukey_results, function(ctrs){
    ctrs$Group_Test
})
anova_test_results <- do.call(rbind, anova_test_results)
# colnames(anova_test_results)[5] <- c("pvalue")
anova_test_results$adj.p.value <- p.adjust(anova_test_results$p.value)

contrasts_results <- lapply(comp_names, function(ctrs_row){
    ctrs_result_list <- lapply(tukey_results, function(ctrs){
        ctrs <- ctrs$Pairwise_Tests
        if(!(ctrs_row %in% rownames(ctrs))){return(rep(NA, 2))}
        ctrs[ctrs_row,]   
    })
    do.call(rbind, ctrs_result_list)
})
names(contrasts_results) <- comp_names

contrasts_results <- lapply(contrasts_results, function(ctrs){
    ctrs <- as.data.frame(ctrs)
    colnames(ctrs) <- c("difference", "pvalue")
    ctrs$adj.p.value <- p.adjust(ctrs[,"pvalue"], method = "fdr")
    ctrs
})

contrasts_results$Group_Test <-  anova_test_results

# saveRDS(comp_results_list, "./ptm_results.rds")
```

```{r}
rownames(ptm_data) <- make.names(rownames(ptm_data))

ptm_metadata <- data.frame("samplename" = make.names(ptm_metadata$Replicate_Name),
                           "group" = ptm_metadata$group)
ptm_results <- do.call(cbind, contrasts_results)

ptm_results$readable_name <- gsub("_|\\.", "-", gsub("\\.[^_]+$|\\.$", "", rownames(ptm_results)))

ptm_exp <- SummarizedExperiment(assays = as.data.frame(t(ptm_data)), 
                                 colData = ptm_metadata,
                                 rowData = cbind(histone_rd, ptm_results))


saveRDS(ptm_exp, paste0(params$output_dir, "Histone_Modifications_Proteomics_exp_lima.rds"))
```

## GFCV 

```{r}
ptm_data <- read.csv(paste0(params$input_dir, "GFCV_liv_PTMs_4_stats.csv"), row.names = 1)

ptm_metadata <- ptm_data[,1:4]
ptm_data <- ptm_data[,5:ncol(ptm_data)]
ptm_metadata$sex <- factor(ptm_metadata$sex, levels = c("M", "F"))
ptm_metadata$gfcv <- factor(ptm_metadata$gfcv, levels = c("C", "G"))
ptm_metadata$group <- factor(paste0(ptm_metadata$gfcv, 
                            ifelse(ptm_metadata$gfcv == "C", "V", "F"), 
                            ptm_metadata$sex), levels = c("CVM", "CVF", "GFM", "GFF"))
ptm_metadata$batch <- factor(ptm_metadata$batch)
# saveRDS(list("PTM_Data" = ptm_data, 
#                           "PTM_Metadata" = ptm_metadata),"./ptm_gfcv_data_list.rds")
```

```{r}
lapply(ptm_data, function(x){boxplot(x ~ ptm_metadata$group)})

lapply(ptm_data, LeveneTest, group = ptm_metadata$group)
lapply(ptm_data, function(x){
    tapply(x, INDEX = ptm_metadata$group, FUN = function(y){
        qqnorm(y)
        qqline(y)
    })
})

```

```{r}
names_comp <- apply(t(combn(levels(ptm_metadata$group), m = 2))[,2:1], 1, paste, collapse = "-")
comp_mat <- as.data.frame(matrix(NA, ncol = 4, nrow = length(names_comp)))
rownames(comp_mat) <- names_comp
colnames(comp_mat) <- c("difference", "lower", "upper", "p.value")

tukey_results <- lapply(ptm_data, function(dt_var){
    anova_results <- aov(dt_var ~ batch + sex + gfcv + sex:gfcv, data = ptm_metadata)
    anova_results_no_int <- aov(dt_var ~ batch + sex + gfcv, data = ptm_metadata)
    
    list("Interaction Term" = as.data.frame(summary(anova_results)[[1]][4,]),
         "GF_CV_Full" = as.data.frame(summary(anova_results_no_int)[[1]][3,]),
         "Pairwise-Tests" = TukeyHSD(anova_results, which = c("sex:gfcv")))
})

gf_cv_results <- do.call(rbind, lapply(tukey_results, function(x){x[[2]]}))
names(gf_cv_results)[names(gf_cv_results) == "Pr(>F)"] <- "p.value"
gf_cv_results$adj.p.value <- p.adjust(gf_cv_results$p.value, method = "fdr")


interaction_results <- do.call(rbind, lapply(tukey_results, function(x){x[[1]]}))
names(interaction_results)[names(interaction_results) == "Pr(>F)"] <- "p.value"
interaction_results$adj.p.value <- p.adjust(interaction_results$p.value, method = "fdr")

contrasts_results <- lapply(tukey_results, function(x){x[[3]]})
contrasts_results <- lapply(seq_len(nrow(contrasts_results[[1]][[1]])), function(ctrs_row){
    ctrs_result_list <- lapply(contrasts_results, function(ctrs){
        if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
        ctrs[[1]][ctrs_row,]   
    })
    do.call(rbind, ctrs_result_list)
})
names(contrasts_results) <- c("CVF_CVM", "GFM_CVM", "GFF_CVM", 
                              "GFM_CVF", "GFF_CVF", "GFF_GFM")

contrasts_results <- lapply(contrasts_results, function(ctrs){
    ctrs <- as.data.frame(ctrs)
    colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
    ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
    ctrs
})
```

```{r}
ptm_results <- do.call(cbind, contrasts_results)

ptm_exp <- SummarizedExperiment(assays = as.data.frame(t(ptm_data)), 
                                rowData = ptm_results, 
                                colData = ptm_metadata)
saveRDS(ptm_exp, paste0(params$output_dir, "Histone_Modifications_Proteomics_exp_gfcv.rds"))
```

