---
title: "DMR Enrichment Analyses"
output: html_document
date: "2024-01-16"
params: 
    dmr_exp_list: !r granges_list[[1]]
    ora_filter: !r NULL
    
    custom_gene_set: !r kegg_pathway_list
    custom_descriptions: !r kegg_description_vect
    custom_name: "custom"
    txdb_id: "TxDb.Mmusculus.UCSC.mm39.refGene"
    msigdbr_specie: "Mus musculus"
    random_seed: 1234
    output_dir: ""
    results_name: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.duplicate.label = "allow")

```

## Required Packages

```{r}
library(MultiAssayExperiment)
library(rGREAT)
library(dplyr)
library(msigdbr)
library(knitr)
library(DT)
library(GOSemSim)
library(org.Mm.eg.db)
library(SummarizedExperiment)
library(params$txdb_id, character.only = TRUE)
source("../../scripts/Utility_Functions/utilities.R")

```

```{r, include=FALSE}
datatable(iris)
```


## rGreat {.tabset}

```{r}
enrich_results_list <- list()
```

```{r}
# Get filtered granges
granges_list <- lapply(params$dmr_exp_list , function(ctrs_res){
    
    if(is(ctrs_res, "SummarizedExperiment")){
        ctrs_res <- rowRanges(ctrs_res)
    }
    
    if(length(params$ora_filter)){
        sub_granges <- ctrs_res[eval(params$ora_filter, envir = rowData(ctrs_res)),] 
    } else{
        sub_granges <- ctrs_res
    }
    
    if(length(sub_granges) == 0){return(NA)}

    mcols(sub_granges) <- mcols(sub_granges)[!colnames(mcols(sub_granges)) %in% 
                                               c("seqnames", "ranges", "strand", 
                                                "seqlevels", "seqlengths",
                                                "isCircular", "start", "end", 
                                                "width", "element")]
    return(sub_granges)
})
```

### Table results {.tabset}

```{r}
contrs_names <- names(params$dmr_exp_list)

contrs_result_sig_list <- lapply(contrs_names, function(ctrs_name){
    ctrs <- params$dmr_exp_list[[ctrs_name]]
    # as.data.frame(ctrs[order(ctrs[[params$order_column]]),])
    if(is(ctrs, "SummarizedExperiment")){
        return(as.data.frame(rowRanges(ctrs)))    
    } else{
        return(as.data.frame(ctrs))
    }
    
})
names(contrs_result_sig_list) <- contrs_names

tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list, 
                                          contrs_names = contrs_names, template = c(
    "#### `r contrs_names[{{i}}]` \n",
    "```{r, echo = FALSE}\n",
    "datatable(contrs_result_sig_list[[{{i}}]], options = list(scrollX = TRUE)) %>% formatRound(columns = colnames(contrs_result_sig_list[[{{i}}]])[sapply(contrs_result_sig_list[[{{i}}]], is.numeric)], digits = 3)",
    "```\n",
    "\n"
))
```

`r knit(text=unlist(tables_chunk))`

<!-- ### GO {.tabset} -->

```{r}
enrich_results_list$ORA <- list()
```

<!-- #### BP {.tabset} -->

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = "GO:BP", 
                tss_source = params$txdb_id))
})
```

```{r}
bp_data <- godata(OrgDb = org.Mm.eg.db, ont = "BP")

contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)

    enrich_res$ID <- enrich_res$id
    enrich_res <- clusterProfiler:::simplify_internal(
        res = enrich_res, cutoff = 0.7, by = "fold_enrichment", select_fun = max, 
        ontology = "BP", semData = bp_data)
    gr_res@table <- enrich_res
    return(list("BP" = gr_res))
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- c(enrich_results_list$ORA, contrs_result_sig_list)

template <- c(
    "#### `r contrs_names[{{i}}]` \n", "\n",
    "```{r, echo = FALSE}\n",
    "datatable(contrs_result_sig_list[[{{i}}]], options = list(scrollX = TRUE)) \n",
    "```\n",
    "\n"
)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->

<!-- #### MF {.tabset} -->

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = "GO:MF", 
                tss_source = params$txdb_id))
})
```

```{r}
mf_data <- godata(OrgDb = org.Mm.eg.db, ont = "MF")

contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)

    enrich_res$ID <- enrich_res$id
    enrich_res <- clusterProfiler:::simplify_internal(
        res = enrich_res, cutoff = 0.7, by = "fold_enrichment", 
        select_fun = max, ontology = "MF", semData = mf_data)
    gr_res@table <- enrich_res
    return(list("MF" = gr_res))
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->

<!-- #### CC {.tabset} -->

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = "GO:CC", 
                tss_source = params$txdb_id))
})
```

```{r}
cc_data <- godata(OrgDb = org.Mm.eg.db, ont = "CC")

contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)

    enrich_res$ID <- enrich_res$id
    enrich_res <- clusterProfiler:::simplify_internal(
        res = enrich_res, cutoff = 0.7, by = "fold_enrichment", 
        select_fun = max, ontology = "CC", semData = cc_data)
    gr_res@table <- enrich_res
    return(list("CC" = gr_res))
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->
        
<!-- ### KEGG {.tabset} -->

```{r}
kegg_pw <- rGREAT::getKEGGPathways("mmu")

kegg_description <- gsub("^ ", "", sapply(strsplit(names(kegg_pw), ":"), function(x){x[2]}))

names(kegg_pw) <- sapply(strsplit(names(kegg_pw), ":"), function(x){x[1]})
names(kegg_description) <- names(kegg_pw)
```

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = kegg_pw, 
                tss_source = params$txdb_id))
})
```

```{r}
contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    
    enrich_res$description <- kegg_description[enrich_res$id]
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)
    
    gr_res@table <- enrich_res
    return(list("kegg" = gr_res))
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->



<!-- ### WP {.tabset} -->

```{r, results='hide'}
wiki_pw <- GSA::GSA.read.gmt("../../inputs/wikipathways-20240101-gmt-Mus_musculus.gmt")
wiki_genesets <- wiki_pw$genesets
names(wiki_genesets) <- wiki_pw$geneset.names


wp_description <- sapply(strsplit(names(wiki_genesets), "%"), function(x){x[1]})
names(wiki_genesets) <- sapply(strsplit(names(wiki_genesets), "%"), 
                                grep, value = TRUE, pattern = "WP[[:digit:]]+")
names(wp_description) <- names(wiki_genesets)
```

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = wiki_genesets, 
                tss_source = params$txdb_id))
})
```

```{r}
contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res$description <- wp_description[enrich_res$id]
    
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)
    gr_res@table <- enrich_res
    return(list("wp" = gr_res))
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)

```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- # ### MSIGdbr H {.tabset} -->

```{r}
library(msigdbr)
h_gene_sets <- msigdbr(species = params$msigdbr_specie, 
                        category = "H")

h_gene_sets <- split(h_gene_sets$entrez_gene, h_gene_sets$gs_name)
h_gene_sets <- lapply(h_gene_sets, as.character)  # just to make sure gene IDs are all in character.
```

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = h_gene_sets, 
                tss_source = params$txdb_id))
})
```

```{r}
contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)
    gr_res@table <- enrich_res
    return(list("msigdbrORA_H" = gr_res))
})

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)

contrs_names <- names(contrs_result_sig_list)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- # ### MSIGdbr C2 {.tabset} -->

```{r}
library(msigdbr)
h_gene_sets <- msigdbr(species = params$msigdbr_specie, 
                        category = "C2")

h_gene_sets <- split(h_gene_sets$entrez_gene, h_gene_sets$gs_name)
h_gene_sets <- lapply(h_gene_sets, as.character)  # just to make sure gene IDs are all in character.
```

```{r, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    
    return(great(gr = granges_obj, 
                gene_sets = h_gene_sets, 
                tss_source = params$txdb_id))
})
```

```{r}
contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)
    gr_res@table <- enrich_res
    return(list("msigdbrORA_C2" = gr_res))
})

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)

contrs_names <- names(contrs_result_sig_list)
```

<!-- # ```{r} -->
<!-- # tables_chunk <- significant_tables_chunks(contrs_result_sig_list = contrs_result_sig_list[[1]],  -->
<!-- #                                           contrs_names = contrs_names, template = template) -->
<!-- # ``` -->
<!-- #  -->

```{r}
do_custom <- !is.null(params$custom_gene_set) & is.list(params$custom_gene_set)
```

```{r, eval = do_custom, cache=TRUE}
set.seed(params$random_seed)
great_results <- lapply(granges_list, function(granges_obj){
    if(length(granges_obj) == 0){return(NA)}
    return(great(gr = granges_obj, 
                gene_sets = params$custom_gene_set, 
                tss_source = params$txdb_id))
})
```

```{r, eval = do_custom}
contrs_result_sig_list <- lapply(great_results, function(gr_res){
    if(!is(gr_res, "GreatObject")){
        return(data.frame())
    }
    enrich_res <- getEnrichmentTable(gr_res)
    enrich_res$description <- params$custom_descriptions[enrich_res$id]
    
    enrich_res <- subset(enrich_res, p_adjust <= 0.05)
    gr_res@table <- enrich_res
    out_list <- list(gr_res)
    names(out_list) <- params$custom_name
    return(out_list)
})
contrs_names <- names(contrs_result_sig_list)

enrich_results_list$ORA <- base::Map(c, enrich_results_list$ORA, contrs_result_sig_list)
```

```{r}
saveRDS(enrich_results_list,  paste0(params$output_dir, params$results_name, 
                                    "_dmr_rgreat_enrich_results.rds"))
```

```{r, results='asis'}
for(enrich_type in names(enrich_results_list)){
    enrich_list <- enrich_results_list[[enrich_type]]
    
    cat(paste0("### ", enrich_type, " {.tabset} \n"))
    for(dt_type in names(enrich_list)){
        
        cat(paste0("#### ", dt_type, " {.tabset} \n"))
        cat("\n")
        enrich_results <- enrich_list[[dt_type]]

        for(enrich_name in names(enrich_results)){
            
            dt_to_table <- getEnrichmentTable(enrich_results[[enrich_name]])
            num_vars <- sapply(dt_to_table, is.numeric)
            cat(paste0("##### ", enrich_name, " {.tabset} \n"))
            cat("\n")
            cat(knit_print(datatable(dt_to_table,
                                    options = list(scrollX = TRUE, pageLength = 5
                                    )) %>%
                                formatRound(columns = colnames(dt_to_table)[num_vars], digits = 3)), "\n")
            cat("\n")
        }
        cat("\n")
    }
    cat("\n")
}
```

## Appendix

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}

```