---
title: "Metallomics Analysis"
output: html_document
date: "2023-04-18"
params:
    input_dir: "../../inputs/Metallomics/"
    output_dir: "../../outputs/Metallomics/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
library(openxlsx)
library(stringr)
library(DescTools)
library(SummarizedExperiment)

input_path <- paste0(params$input_dir, "metallomics_raw.xlsx")

sheet_names <- openxlsx::getSheetNames(input_path)[1:2]

metallomics_dt <- lapply(sheet_names, function(sheet_name){
    read.xlsx(xlsxFile = input_path, sheet = sheet_name)
})
names(metallomics_dt) <- sheet_names

```

## GF/CV

```{r}
gfcv_data_list <- lapply(metallomics_dt, function(organ){
    gfcv_dt <- subset(organ, model == "GFCV")
    rownames(gfcv_dt) <- gfcv_dt$samplename
    metallomics_metadata <- gfcv_dt[,1:5]
    metallomics_metadata$sex <- factor(metallomics_metadata$gender, levels = c("M", "F"))
    metallomics_metadata$gfcv <- factor(substr(metallomics_metadata$group,
                                               1,1), levels = c("C", "G"))
    metallomics_metadata$batch <- factor(metallomics_metadata$batch)
    
    metallomics_metadata$group <- factor(paste0(metallomics_metadata$group, 
                                                metallomics_metadata$sex), 
                                         levels = c("CVM", "CVF", "GFM", "GFF"))
    
    list("Metallomics_Data" = gfcv_dt[,6:ncol(gfcv_dt)], 
        "Metallomics_Metadata" = metallomics_metadata)
})

# saveRDS(gfcv_data_list, file = "./gfcv_metallomics_list.rds")
```


```{r}
organ_results <- lapply(gfcv_data_list, function(organ_dt){
    gf_data <- organ_dt[["Metallomics_Data"]]
    gf_metadata <- organ_dt[["Metallomics_Metadata"]]
    
    tukey_results <- lapply(gf_data, function(dt_var){
        anova_results <- aov(dt_var ~ batch + sex + gfcv + sex:gfcv, data = gf_metadata)
        anova_results_no_int <- aov(dt_var ~ batch + sex + gfcv, data = gf_metadata)
        
        list("Interaction Term" = as.data.frame(summary(anova_results)[[1]][4,]),
             "GF_CV_Full" = as.data.frame(summary(anova_results_no_int)[[1]][3,]),
             "Pairwise-Tests" = TukeyHSD(anova_results, which = c("sex:gfcv")))
    })
    gf_cv_results <- do.call(rbind, lapply(tukey_results, function(x){x[[2]]}))
    names(gf_cv_results)[names(gf_cv_results) == "Pr(>F)"] <- "p.value"
    gf_cv_results$adj.p.value <- p.adjust(gf_cv_results$p.value, method = "fdr")
    
    
    interaction_results <- do.call(rbind, lapply(tukey_results, function(x){x[[1]]}))
    names(interaction_results)[names(interaction_results) == "Pr(>F)"] <- "p.value"
    interaction_results$adj.p.value <- p.adjust(interaction_results$p.value, method = "fdr")
    
    contrasts_results <- lapply(tukey_results, function(x){x[[3]]})
    contrasts_results <- lapply(seq_len(nrow(contrasts_results[[1]][[1]])), function(ctrs_row){
        ctrs_result_list <- lapply(contrasts_results, function(ctrs){
            if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
            ctrs[[1]][ctrs_row,]   
        })
        do.call(rbind, ctrs_result_list)
    })
    names(contrasts_results) <- c("CVF_CVM", "GFM_CVM", "GFF_CVM", 
                                  "GFM_CVF", "GFF_CVF", "GFF_GFM")
    
    contrasts_results <- lapply(contrasts_results, function(ctrs){
        ctrs <- as.data.frame(ctrs)
        colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
        ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
        ctrs
    })
    contrasts_results
})
# saveRDS(organ_results, file = "./gfcv_metallomics_results_list.rds")

```

```{r}
metallomics_exp <- lapply(names(gfcv_data_list), function(organ_name){
    organ_dt <- as.data.frame(t(gfcv_data_list[[organ_name]][["Metallomics_Data"]]))
    organ_meta <- gfcv_data_list[[organ_name]][["Metallomics_Metadata"]]
    organ_results <- do.call(cbind, organ_results[[organ_name]])
    SummarizedExperiment(organ_dt, rowData = organ_results, colData = organ_meta)
})
names(metallomics_exp) <- names(gfcv_data_list)

saveRDS(metallomics_exp, paste0(params$output_dir, "Metallomics_exp_gfcv.rds"))
```


## LIMA 

```{r}
lima_data_list <- lapply(metallomics_dt, function(organ){
    lima_dt <- subset(organ, model == "LIMA")
    rownames(lima_dt) <- lima_dt$samplename
    
    metallomics_metadata <- lima_dt[,1:5]
    metallomics_metadata$group <- factor(metallomics_metadata$group, 
                                         levels = c("CTN", "HFD", "INT", "HFE"), 
                                          labels = c("CNT", "HFD", "INT", "HFE"))
    
    list("Metallomics_Data" = lima_dt[,6:ncol(lima_dt)], "Metallomics_Metadata" = metallomics_metadata)
})
# saveRDS(lima_data_list, file = "./lima_metallomics_list.rds")
```

```{r}
# lapply(lima_data_list, function(x){boxplot(x ~ ptm_metadata$group)})
# 
# lapply(ptm_data, LeveneTest, group = ptm_metadata$group)
# lapply(ptm_data, function(x){
#     tapply(x, INDEX = ptm_metadata$group, FUN = function(y){
#         qqnorm(y)
#         qqline(y)
#     })
# })
pdf(paste0(params$output_dir, "boxplot_metallomics.pdf"))
lapply(names(lima_data_list), function(organ_name){
    organ_dt <- lima_data_list[[organ_name]][["Metallomics_Data"]]
    organ_meta <- lima_data_list[[organ_name]][["Metallomics_Metadata"]]
    
    sapply(names(organ_dt), function(var_name){
        boxplot(organ_dt[[var_name]] ~ organ_meta$group, ylab = var_name, xlab = "Group", main = organ_name) 
    })
    
})
dev.off()
```


```{r}
# tukey_results <- lapply(names(lima_data_list), function(organ){
#     lima_data <- lima_data_list[[organ]][["Metallomics_Data"]]
#     lima_metadata <- lima_data_list[[organ]][["Metallomics_Metadata"]]
#     
#     apply(lima_data, 2, function(dt_var){
#         anova_results <- aov(dt_var ~ 0 + group, data = lima_metadata) 
#         c("Pairwise-Tests" = TukeyHSD(anova_results, which = c("group")))
#     })
# })
# names(tukey_results) <- names(lima_data_list)
# 
# 
# organ_results <- lapply(tukey_results, function(contrasts_results){
#     contrasts_results <- lapply(rownames(contrasts_results[[1]][[1]]), function(ctrs_row){
#         ctrs_result_list <- lapply(contrasts_results, function(ctrs){
#             if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
#             if(!ctrs_row %in% rownames(ctrs[[1]])){return(rep(NA, 4))}
#             ctrs[[1]][ctrs_row,]   
#         })
#         do.call(rbind, ctrs_result_list)
#     })
#     names(contrasts_results) <- c("HFD-CNT", "INT-CNT", "HFE-CNT", 
#                                 "INT-HFD", "HFE-HFD", "HFE-INT")
#     contrasts_results
# })
# 
# organ_results <- lapply(organ_results, function(contrasts_results){
#     lapply(contrasts_results, function(ctrs){
#         ctrs <- as.data.frame(ctrs)
#         colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
#         ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
#         ctrs
#     })
# })

# saveRDS(organ_results, file = "./lima_metallomics_results_list.rds")
```

```{r}
comp_names <- apply(t(combn(levels(lima_data_list$liver$Metallomics_Metadata$group), m = 2))[,2:1], 1, 
                    paste, collapse = "-")
comp_matrix <- matrix(NA, nrow = length(comp_names), ncol = 2)
rownames(comp_matrix) <- comp_names

results_list <- lapply(names(lima_data_list), function(organ_name){
    organ_list <- lima_data_list[[organ_name]]
        
    tukey_results <- apply(organ_list$Metallomics_Data, 2, function(dt_var){
        anova_results <- kruskal.test(dt_var, g = organ_list$Metallomics_Metadata$group)
        anova_results <- data.frame("statistic" = anova_results$statistic,
                                    "parameter" = anova_results$parameter,
                                    "p.value" = anova_results$p.value)
    
        # anova_results2 <- aov(dt_var ~ 0 + group, data = lima_metadata)
        # comp_results <- list("Group_Test" = summary(anova_results)[[1]]["group",])
        comp_results <- list("Group_Test" = anova_results)
        #plot(anova_results)
        if(comp_results$Group_Test$p.value <= 0.05){
            comp_results$Pairwise_Tests <- DescTools::ConoverTest(dt_var, 
                                                                organ_list$Metallomics_Metadata$group)[[1]]
            # comp_results$Pairwise_Tests <- TukeyHSD(anova_results, which = c("group"))$group
            return(comp_results)
        } else{
            comp_results$Pairwise_Tests <- comp_matrix
            return(comp_results)
        }

    })
    
    anova_test_results <- lapply(tukey_results, function(ctrs){
        ctrs$Group_Test
    })
    anova_test_results <- do.call(rbind, anova_test_results)
    # colnames(anova_test_results)[5] <- c("pvalue")
    anova_test_results$adj.p.value <- p.adjust(anova_test_results$p.value)
    
    contrasts_results <- lapply(comp_names, function(ctrs_row){
        ctrs_result_list <- lapply(tukey_results, function(ctrs){
            ctrs <- ctrs$Pairwise_Tests
            if(!(ctrs_row %in% rownames(ctrs))){return(rep(NA, 2))}
            ctrs[ctrs_row,]   
        })
        do.call(rbind, ctrs_result_list)
    })
    names(contrasts_results) <- comp_names
    
    contrasts_results <- lapply(contrasts_results, function(ctrs){
        ctrs <- as.data.frame(ctrs)
        colnames(ctrs) <- c("difference", "pvalue")
        ctrs$adj.p.value <- p.adjust(ctrs[,"pvalue"], method = "fdr")
        ctrs
    })
    
    contrasts_results$Group_Test <-  anova_test_results    
    do.call(cbind, contrasts_results)
})

names(results_list) <- names(lima_data_list)
```


```{r}
metal_exp_list <- lapply(names(lima_data_list), function(organ_name){
    organ_list <- lima_data_list[[organ_name]]
    organ_data <- organ_list[["Metallomics_Data"]]
    organ_data <- t(organ_data)
    merged_rowdata <- results_list[[organ_name]]
    # rownames(organ_data) <- paste0(organ_name, ".", rownames(organ_data))
    colnames(organ_data) <- make.names(colnames(organ_data))
    organ_metadata <- organ_list[["Metallomics_Metadata"]]
    organ_metadata$samplename <- make.names(organ_metadata$samplename)
    rownames(organ_metadata) <- organ_metadata$samplename
    merged_rowdata$readable_name <- str_replace(paste(organ_name, rownames(merged_rowdata)), 
                                                        "^\\w{1}", toupper)
    # rownames(merged_rowdata) <- paste0(organ_name, ".", rownames(merged_rowdata))
    # 
    SummarizedExperiment(assays = as.data.frame(organ_data), 
                         colData = organ_metadata[c("samplename", "group")],
                         rowData = merged_rowdata)
    
})
names(metal_exp_list) <- names(lima_data_list)

saveRDS(metal_exp_list, paste0(params$output_dir, "Metallomics_exp_lima.rds"))
```

