---
title: "Metallomics Analysis"
output: html_document
date: "2023-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data

```{r}
library(openxlsx)
sheet_names <- openxlsx::getSheetNames("./metallomics_raw.xlsx")[1:2]

metallomics_dt <- lapply(sheet_names, function(sheet_name){
    read.xlsx(xlsxFile = "./metallomics_raw.xlsx", sheet = sheet_name)
})
names(metallomics_dt) <- sheet_names

```

## GF/CV

```{r}
gfcv_data_list <- lapply(metallomics_dt, function(organ){
    gfcv_dt <- subset(organ, model == "GFCV")
    rownames(gfcv_dt) <- gfcv_dt$samplename
    metallomics_metadata <- gfcv_dt[,1:5]
    metallomics_metadata$sex <- factor(metallomics_metadata$gender, levels = c("M", "F"))
    metallomics_metadata$gfcv <- factor(substr(gfcv_data_list[["liver"]][["Metallomics_Metadata"]]$group, 1,1), levels = c("C", "G"))
    metallomics_metadata$batch <- factor(metallomics_metadata$batch)
    
    metallomics_metadata$group <- factor(paste0(metallomics_metadata$group, 
                                                metallomics_metadata$sex), 
                                         levels = c("CVM", "CVF", "GFM", "GFF"))
    
    list("Metallomics_Data" = gfcv_dt[,6:ncol(gfcv_dt)], 
        "Metallomics_Metadata" = metallomics_metadata)
})

saveRDS(gfcv_data_list, file = "./gfcv_metallomics_list.rds")
```


```{r}
organ_results <- lapply(gfcv_data_list, function(organ_dt){
    gf_data <- organ_dt[["Metallomics_Data"]]
    gf_metadata <- organ_dt[["Metallomics_Metadata"]]
    
    tukey_results <- lapply(gf_data, function(dt_var){
        anova_results <- aov(dt_var ~ batch + sex + gfcv + sex:gfcv, data = gf_metadata)
        anova_results_no_int <- aov(dt_var ~ batch + sex + gfcv, data = gf_metadata)
        
        list("Interaction Term" = as.data.frame(summary(anova_results)[[1]][4,]),
             "GF_CV_Full" = as.data.frame(summary(anova_results_no_int)[[1]][3,]),
             "Pairwise-Tests" = TukeyHSD(anova_results, which = c("sex:gfcv")))
    })
    gf_cv_results <- do.call(rbind, lapply(tukey_results, function(x){x[[2]]}))
    names(gf_cv_results)[names(gf_cv_results) == "Pr(>F)"] <- "p.value"
    gf_cv_results$adj.p.value <- p.adjust(gf_cv_results$p.value, method = "fdr")
    
    
    interaction_results <- do.call(rbind, lapply(tukey_results, function(x){x[[1]]}))
    names(interaction_results)[names(interaction_results) == "Pr(>F)"] <- "p.value"
    interaction_results$adj.p.value <- p.adjust(interaction_results$p.value, method = "fdr")
    
    contrasts_results <- lapply(tukey_results, function(x){x[[3]]})
    contrasts_results <- lapply(seq_len(nrow(contrasts_results[[1]][[1]])), function(ctrs_row){
        ctrs_result_list <- lapply(contrasts_results, function(ctrs){
            if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
            ctrs[[1]][ctrs_row,]   
        })
        do.call(rbind, ctrs_result_list)
    })
    names(contrasts_results) <- c("CVF_CVM", "GFM_CVM", "GFF_CVM", 
                                  "GFM_CVF", "GFF_CVF", "GFF_GFM")
    
    contrasts_results <- lapply(contrasts_results, function(ctrs){
        ctrs <- as.data.frame(ctrs)
        colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
        ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
        ctrs
    })
    contrasts_results
})
saveRDS(organ_results, file = "./gfcv_metallomics_results_list.rds")

```

## LIMA 

```{r}
lima_data_list <- lapply(metallomics_dt, function(organ){
    lima_dt <- subset(organ, model == "LIMA")
    rownames(lima_dt) <- lima_dt$samplename
    
    metallomics_metadata <- lima_dt[,1:5]
    metallomics_metadata$group <- factor(metallomics_metadata$group, levels = c("CTN", "HFD", "INT", "HFE"))
    
    list("Metallomics_Data" = lima_dt[,6:ncol(lima_dt)], "Metallomics_Metadata" = metallomics_metadata)
})
saveRDS(lima_data_list, file = "./lima_metallomics_list.rds")
```

```{r}
plot_dt <- lapply(names(lima_data_list), function(organ_name){
    organ_dt <- lima_data_list[[organ_name]][["Metallomics_Data"]]
    organ_meta <- lima_data_list[[organ_name]][["Metallomics_Metadata"]]
    sapply(names(organ_dt), function(var_name){
        boxplot(organ_dt[[var_name]] ~ organ_meta$group, ylab = var_name, xlab = "Group")
    })
    
})
```


```{r}
tukey_results <- lapply(names(lima_data_list), function(organ){
    lima_data <- lima_data_list[[organ]][["Metallomics_Data"]]
    lima_metadata <- lima_data_list[[organ]][["Metallomics_Metadata"]]
    
    apply(lima_data, 2, function(dt_var){
        anova_results <- aov(dt_var ~ 0 + group, data = lima_metadata) 
        c("Pairwise-Tests" = TukeyHSD(anova_results, which = c("group")))
    })
})
names(tukey_results) <- names(lima_data_list)


organ_results <- lapply(tukey_results, function(contrasts_results){
    contrasts_results <- lapply(rownames(contrasts_results[[1]][[1]]), function(ctrs_row){
        ctrs_result_list <- lapply(contrasts_results, function(ctrs){
            if(nrow(ctrs[[1]]) == 0){return(rep(NA, 4))}
            if(!ctrs_row %in% rownames(ctrs[[1]])){return(rep(NA, 4))}
            ctrs[[1]][ctrs_row,]   
        })
        do.call(rbind, ctrs_result_list)
    })
    names(contrasts_results) <- c("HFD-CNT", "INT-CNT", "HFE-CNT", "INT-HFD", "HFE-HFD", "HFE-INT")
    contrasts_results
})

organ_results <- lapply(organ_results, function(contrasts_results){
    lapply(contrasts_results, function(ctrs){
        ctrs <- as.data.frame(ctrs)
        colnames(ctrs) <- c("difference", "lower", "upper", "p.value")
        ctrs$adj.p.value <- p.adjust(ctrs[,"p.value"], method = "fdr")
        ctrs
    })
})

saveRDS(organ_results, file = "./lima_metallomics_results_list.rds")
```

